### ISSUE TITLE
`pip install -e .` broken

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#4486] opened 2023-06-16 20:32 UTC
```
pip install -e .
python -m jupyterhub
```

```python-traceback
Traceback (most recent call last):
  File "/home/erik/mambaforge/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/erik/mambaforge/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/jupyterhub/jupyterhub/__main__.py", line 1, in <module>
    from .app import main
  File "/tmp/jupyterhub/jupyterhub/app.py", line 62, in <module>
    from . import apihandlers, crypto, dbutil, handlers, orm, roles, scopes
  File "/tmp/jupyterhub/jupyterhub/apihandlers/__init__.py", line 1, in <module>
    from . import auth, groups, hub, proxy, services, users
  File "/tmp/jupyterhub/jupyterhub/apihandlers/auth.py", line 14, in <module>
    from .base import APIHandler, BaseHandler
  File "/tmp/jupyterhub/jupyterhub/apihandlers/base.py", line 14, in <module>
    from ..handlers import BaseHandler
  File "/tmp/jupyterhub/jupyterhub/handlers/__init__.py", line 1, in <module>
    from . import base, login, metrics, pages
  File "/tmp/jupyterhub/jupyterhub/handlers/base.py", line 25, in <module>
    from .. import __version__, orm, roles, scopes
ImportError: cannot import name '__version__' from 'jupyterhub' (unknown location)
```

Checkout out 4.0.1 works, but the main branch tip doesn't. Probably related to #4477

**Comment by minrk** [comment] 2023-06-19 06:51
#4477 makes sense, but it shouldn't actually have any effect at runtime or what's installed, and doesn't touch how `jupyterhub.__version__` works. I think something might be up in your path or env, because this doesn't happen in a fresh environment:

```Dockerfile
FROM python:3.11
# get CHP
RUN apt-get -y update && apt-get -y --no-install-recommends install npm
RUN npm install -g configurable-http-proxy

# standard dev install
RUN git clone https://github.com/jupyterhub/jupyterhub
WORKDIR /jupyterhub
RUN pip install -e .
CMD python3 -m jupyterhub
```

works fine. Where you might get issues is if you have a `jupyterhub` folder in the CWD, perhaps? Not sure what else could cause this.

**Comment by yuvipanda** [comment] 2023-09-06 17:15
I can also confirm that `pip install -e .` on `main` works for me.

**Comment by minrk** [comment] 2023-09-12 06:10
@consideRatio can you still reproduce this?

**Comment by minrk** [comment] 2023-11-14 09:29
closing since this editable installs are confirmed to work. @consideRatio feel free to reopen with more info if you can reproduce it.

**Closed by minrk** 2023-11-14 09:29 UTC
Labels: maintenance
