### ISSUE TITLE
Loading notebook extensions for all users on the hub

### ISSUE THREAD

**Issue by SelenaBaset** [jupyterhub/jupyterhub#305] opened 2015-09-21 12:56 UTC
Hello, 

I've been tying for a while to make some nbextensions avaliable to all users on the hub with no success so far. I've found a couple of pages on troubleshooting extensions installations for jupyter but nothing for jupyterhub and I'd really appreciate any help with this...

I am on v  4.0.4 of the hub with default PAM (local users on the server) and trying with the  <a href="https://github.com/ipython-contrib/IPython-notebook-extensions"> IPython-notebook-extensions </a> and some other extensions. 
Here is where I've got so far: 
- Installing and activating the extensions on standalone jupyter works fine. For jupyterhub, it works as well but only per user basis (i.e. I would need to install the extensions into the user local folders...)
- I've tried to install the extensions into one common path "/usr/share/jupyter" and configure the JUPYTER_CONFIG_DIR and JUPYTER_DATA_DIR to look for the extensions there but this doesn't seem to work. 
- As far as I can tell, installing the extensions for all users worked because running the following statements returns True/True: 

``` python
import notebook
notebook.nbextensions.check_nbextension('usability/search-replace', user=False)
notebook.nbextensions.check_nbextension('usability/codefolding/main.js', user=False)
```
- I managed also to change the config and data dirs for standalone Jupyter by setting the  proper values for JUPYTER_CONFIG_DIR and JUPYTER_DATA_DIR environment variables, so now running: 
  jupyter --config-dir 
  returns: /etc/jupyter
  and: 
  jupyter --data-dir 
  returns: /usr/share/jupyter

still when running: 

``` python
from traitlets.config.loader import Config, JSONFileConfigLoader
from jupyter_core.paths import jupyter_config_dir
import os.path
fname = os.path.join(jupyter_config_dir(), 'nbconfig/notebook.json')
cl = JSONFileConfigLoader(fname)
cl.load_config()
```

I get an error msg that contains: 
*\* ConfigFileNotFound: File '/home/someuser/.jupyter/nbconfig/notebook.json' does not exist in any of the search paths: ('',) **
which means the config dir for the single user server is not affected by the set environment variables...

Actually, even running `print(jupyter_config_dir())`  would reveal the same information as it will always point to the user local config dir: /home/someuser/.jupyter 

Finally, I tried setting the spawner.args value in the configuration file on the hub level. There, changes seem to impact all spwned single-user servers (Common sense...) but I still can't figure out the right configuration syntax to achieve this even after looking at jupyter --help-all and ipython/jupyter notebook --help-all.

I've tried with some variations of  `c.Spawner.args =  ['--config-dir=/etc/jupyter']`  but always ended up with either bad argument or unrecognized alias that had no effect.

Thanks a lot in advanced and sorry for the long post but I tried to cover the necessary details.

**Comment by Carreau** [comment] 2015-09-22 21:34
@jhamrick You have some experience with that, I assign you, I know you are busy so tell if you want someone else to investigate.

**Comment by jhamrick** [comment] 2015-09-22 23:23
Ah, hmm, if the environment variable is not being set, then I think probably what you need to do is modify the spawner's `env` variable in your config, e.g.:

```
c = get_config()
c.Spawner.env['JUPYTER_CONFIG_DIR'] = '/path/to/your/global/config'
```

The `env` dictionary contains environment variables that the subprocesses of the spawner (the singleuser servers) should inherit.

**Comment by SelenaBaset** [comment] 2015-10-07 11:52
Thanks for the tip. I actually haven't had the chance to come back to this before but I was just trying your suggestion right now. Still not there yet, I am not sure if I am modifying the ```env ``` variable the right way. The following config line:
 
```python
c.Spawner.env['JUPYTER_CONFIG_DIR'] = '/path/to/global/config'
```

produces a TypeError that indicates: 
``` 'LazyConfigValue' object does not support item assignment```

Any idea on how to properly modify an ```env ``` variable in the hub configuration? Thanks!

**Comment by minrk** [comment] 2015-10-07 12:39
Sorry, the `env` key isn't configurable, but it probably should be. Once configurable, you will be able to add to existing values with `update`:

    c.Spawner.env.update({'JUPYTER_CONFIG_DIR': '/path/to/global/config'})

**Comment by dsblank** [comment] 2015-10-07 14:00
As a workaround, you could edit a template to load an extension:

Changed /usr/lib/python3.4/site-packages/IPython/html/templates/

```html
<script type="text/javascript">
    sys_info = {{sys_info}};
    require(['base/js/namespace', 'base/js/events'], function (IPython, events) {
        events.on("notebook_loaded.Notebook", function () {
            IPython.load_extensions("calico-publish", 
                                    "calico-submit",
                                    "calico-spell-check",
                                    "calico-document-tools", 
                                    "calico-cell-tools");
            // INSTALL MAGIC
            // To turn off automatically creating closing parenthesis and bracket:
            // IPython.CodeCell.options_default.cm_config["autoCloseBrackets"] = "";
        });
    });
</script>
```

**Comment by SelenaBaset** [comment] 2015-10-07 14:19
@dsblank, I will try this out for sure. It would never come to my mind to do it this way actually so thank you! 
@minrk, is the configurability of the ```env``` key coming sometime soon or it's not at all on the roadmap?

**Comment by minrk** [comment] 2015-10-07 14:30
@SelenaBaset soon, just figuring out how best to do it. You can accomplish it right now by specifying the environment variable in the JupyterHub process's environment, and adding `JUPYTER_DATA_DIR` to `Spawner.env_keep`:

```python
import os
os.environ['JUPYTER_DATA_DIR'] = 'foo'
c.Spawner.env_keep.append('JUPYTER_DATA_DIR')
```

**Comment by SelenaBaset** [comment] 2015-10-07 14:43
Great! Thanks a lot!

**Comment by wangxiaoyi00** [comment] 2015-12-24 09:14
@SelenaBaset Could I ask how you get it work for jupyterhub per user basis ? My standalone jupyter works fine too. But jupyterhub logs show "404 GET /hub/nbextensions/usability/latex_envs/thmsInNb4.js". 
I use jupyterhub 0.3.0.  Thanks a lot!

**Comment by jld23** [comment] 2016-01-13 14:34
I tried @dsblank proposed workaround but I get the following error in my browser console:
Uncaught (in promise) TypeError: IPython.load_extensions is not a function(…)
(anonymous function) @ Untitled.ipynb?kernel_name=sas:440
x.event.dispatch @ jquery.min.js:5
y.handle @ jquery.min.js:5
x.event.trigger @ jquery.min.js:5
(anonymous function) @ jquery.min.js:5
x.extend.each @ jquery.min.js:4
x.fn.x.each @ jquery.min.js:4
x.fn.extend.trigger @ jquery.min.js:5
Notebook.load_notebook_success @ notebook.js:2422
x.isFunction.i @ jquery.min.js:4

For clarity, I modified ..../lib/python3.4/site-packages/notebook/templates/notebook.html areound line 320 The removed lines were commented out from failed attempts
```
321 <script type="text/javascript">
332     require(['base/js/namespace', 'base/js/events'], function (IPython, events) {
333         events.on("notebook_loaded.Notebook", function () {
334             IPython.load_extensions("calico-publish",
335                                     "calico-submit",
336                                     "calico-spell-check",
337                                     "calico-document-tools",
338                                     "calico-cell-tools");
339             // INSTALL MAGIC
340             // To turn off automatically creating closing parenthesis and bracket:
341             // IPython.CodeCell.options_default.cm_config["autoCloseBrackets"] = "";
342         });
343     });
344 </script>
```

@minrk Can you expand on your solution above? If 'foo' the directory where the extensions are stored? I'm using `/usr/local/share/jupyter/nbextensions/` for my location.

Thanks,
Jaresd

**Comment by dsblank** [comment] 2016-01-13 15:02
Looks like that function has moved:

require(['base/js/utils'],function(utils) {
    utils.load_extensions('...');
});

-Doug

**Comment by dsblank** [comment] 2016-01-13 15:13
Just successfully tried this on master, updated code base:

    require(['base/js/namespace', 'base/js/events'], function (IPython,
events) {
        events.on("notebook_loaded.Notebook", function () {
            IPython.utils.load_extensions(
                 "calico-publish",
                 "calico-submit",
                 "calico-spell-check",
                 "calico-document-tools",
                 "calico-cell-tools"
            );
        });
    });

-Doug

**Comment by jld23** [comment] 2016-01-13 16:14
@dsblank Thank you! That worked for me as well for all users in jupyterhub. Now I need to figure out why my own extensions aren't loading.

**Comment by ian-contiamo** [comment] 2016-02-11 13:04
For the record, @minrk 's solution [here](https://github.com/jupyter/jupyterhub/issues/305#issuecomment-146211413) worked for me:

```
import os
os.environ['JUPYTER_DATA_DIR'] = 'foo'
c.Spawner.env_keep.append('JUPYTER_DATA_DIR')
```

I prefer that to tampering with HTML templates :)

**Comment by danielballan** [comment] 2016-02-11 19:48
This approach worked for me also, but I believe it has to be `JUPYTER_CONFIG_DIR`, not `JUPYTER_DATA_DIR`, for nbextensions.

**Comment by ian-contiamo** [comment] 2016-02-12 09:32
@danielballan thanks, good point. I edited my response to avoid confusion.

**Comment by jld23** [comment] 2016-02-12 20:45
@danielballan @ian-contiamo 
Thanks for updating this issue. I'm confused what config path I'm supposed to use since the nbextesions are in the data path (/usr/local/etc/jupyter/nbextensions) or do I need a .py file in the config directory to load the extensions using python code like below:
```
if notebook.nbextensions.check_nbextension('usability/dragdrop', user=False):
    E = notebook.nbextensions.EnableNBExtensionApp()
    E.enable_nbextension('usability/dragdrop/main')
else:
    print ("Extension not found")
```

Thanks!

**Comment by wwwald** [comment] 2016-06-27 12:44
I've been following the above advice and have nbextensions working now for all users on our JupyterHub server, but it took me quite some additional tinkering with file permissions concerning `notebook_secret` files, `nbconfig` directories and so on. I don't think I have an optimal setup, but I haven't found any "reference" for this.
Is there some kind of "good practice" guideline available, to make all this work?

**Comment by Carreau** [comment] 2016-06-27 18:42
You likely shouldn't tinker with `notebook_secret` as this one should **not**  be systemwide. 



> Is there some kind of "good practice" guideline available, to make all this work?

We are still working on documentation, if you can describe what you did, we could try to correct what's good/bad and included it in our docs.

**Comment by Fleckenteufel** [comment] 2016-10-13 11:20
On my system `jupyter --path` says that I can put config files into `/usr/local/etc/jupyter`, which would be applied globally for every instance of jupyter. In there I created a folder `nbconfig` and can put there the usual config files where I specify the extensions to be loaded. For example in `/usr/local/etc/jupyter/nbconfig/notebook.json`:

``` json
{
  "load_extensions": {
    "contrib_nbextensions_help_item/main": true
  }
}
```

And in `/usr/local/etc/jupyter/nbconfig/tree.json`:

```
{
  "load_extensions": {
    "nbextensions_configurator/tree_tab/main": true
  }
}
```

You can check which extensions are enabled by calling:

```
> jupyter nbextension list
Known nbextensions:
  config dir: /home/ehebestreit/.jupyter/nbconfig
    notebook section
      toc2/main  enabled 
      - Validating: OK
      collapsible_headings/main disabled
      hinterland/hinterland  enabled 
      - Validating: OK
      init_cell/main  enabled 
      - Validating: OK
      spellchecker/main  enabled 
      - Validating: OK
      hide_input/main  enabled 
      - Validating: OK
      skip-traceback/main  enabled 
      - Validating: OK
      execute_time/ExecuteTime  enabled 
      - Validating: OK
      comment-uncomment/main  enabled 
      - Validating: OK
      codefolding/main  enabled 
      - Validating: OK
      scratchpad/main  enabled 
      - Validating: OK
    tree section
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      contrib_nbextensions_help_item/main  enabled 
      - Validating: OK
    tree section
      nbextensions_configurator/tree_tab/main  enabled 
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
```

The two at the end are enabled globally for every instance of jupyter running on the computer.

**Comment by willingc** [comment] 2018-06-08 14:28
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!

**Closed by willingc** 2018-06-08 14:28 UTC
Labels: enhancement

**Comment by JeffSaxeVA** [comment] 2020-09-04 16:10
Also commenting after the issue is closed, just because this few-years-old discussion _helped me to get The Littlest JupyterHub installed and maintained_ in our environment. Like many multi-step, multi-layered installers, this software performs some "apt-get", then uses some "Python requests()", then some Node.js installs, Conda installs, etc., and _several of these tools have their own independent ideas of what should be the definitive root certificate list, which (if you happen to be in a locked-down firewall environment) may not include your in-house corporate root CA, even if that is properly installed at the OS layer._ If you track down and manually edit the `cacert.pem` file buried deep in your Certifi package, then it works for a while, but then any time the `conda` package gets updated, it obliterates your edit and everything stops working again. So the best solution is to sprinkle whatever environment variables will inform each of those HTTPS handlers about your own, preferred root list.

So for instance, for our Ubuntu 18, before even starting the bootstrap.py script, I added these as system-wide Bash environment variables by editing `/etc/environment` and adding to the end...

```
# for Conda...
REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
# for Node.js Package Manager, npm...
NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
```

Then, once TLJH is installed, the JupyterHub admins are able to continue installing more Conda packages later by using `sudo -E` in a Terminal window launched inside their logged-in Jupyter session. This is great, but it's helpful to hand off these variables in that context, too, so I finally figured out the necessary syntax to add environment variables to launched single-user servers.

```
sudo nano /opt/tljh/config/jupyterhub_config.d/AdditionalEnvironmentVariablesToEachUserServer.py

c.SystemdSpawner.environment.update( {
	'REQUESTS_CA_BUNDLE': '/etc/ssl/certs/ca-certificates.crt',
	'NODE_EXTRA_CA_CERTS': '/etc/ssl/certs/ca-certificates.crt',
	} )

sudo tljh-config reload
```

This is because TLJH uses SystemdSpawner to spawn users' servers, and that is a subclass of Spawner, with similar objects and function available.

Thanks to all the Jupyter and JupyterHub authors for the fantastic work.

**Comment by consideRatio** [comment] 2020-09-04 16:33
Thanks for sharing what you learned @JeffSaxeVA! :heart:
