### ISSUE TITLE
logout from jupyterhub doesn't logout from oauth provider

### ISSUE THREAD

**Issue by chominnn** [jupyterhub/jupyterhub#4875] opened 2024-08-23 06:05 UTC
Bug description
We currently use the GenericOAuthenticator together with an internal Keycloak instance and it works reasonably well. However we noticed that a logout of JupyterHub does not clear the cookies. If the user presses Sign-in after logging out via JupyterHub they get directly taken back to the hub spawn page without going through the actual user login process.

Expected behaviour
Logout from JupyterHub deletes the Cookies and the User needs to sign-in again afterwards

Actual behaviour
Logout from JupyterHub does not delete the Cookies. A user gets directly taken to the Hub Spawn page after clicking sign in again.

**values.yaml**
hub:
  revisionHistoryLimit:
  config:
    GenericOAuthenticator:
      client_id: @@@@
(skip)
      userdata_url: http://keycloak.test.com/realms/test/protocol/openid-connect/userinfo
      logout_redirect_url: http://keycloak.test.com/auth/realms/test/protocol/openid-connect/logout?redirect_uri=http%3A%2F%2F211.39.158.203%2Fhub%2F
      login_service: keycloak
      username_claim: preferred_username

**When try to  logout**
![image](https://github.com/user-attachments/assets/87186c35-c7ba-4ed4-b2fb-213d446ae899)

**Logs of Keycloak**

024-08-23 04:52:21,440 WARN  [org.keycloak.events] (executor-thread-317) type="LOGIN_ERROR", realmId="7e01a863-9137-4108-9009-f8078ca43f6c", clientId="security-admin-console", userId="null", ipAddress="10.0.0.28", error="user_not_found", auth_method="openid-connect", auth_type="code", redirect_uri="http://keycloak.test.com/admin/master/console/", code_id="3b370311-9aa0-4bd9-8bb3-cb391be74cf1", username="test@test.com"

**Comment by minrk** [comment] 2024-08-23 06:46
Closing as duplicate of #4323  https://github.com/jupyterhub/oauthenticator/issues/472 which has explanations of why this is and how to get what you want via

```python
c.OAuthenticator.logout_redirect_url = "https:///your-keycloack/..."
```

**Comment by chominnn** [comment] 2024-08-23 06:47
> [#4323 ](https://github.com/jupyterhub/jupyterhub/issues/4323) [jupyterhub/oauthenticator#472](https://github.com/jupyterhub/oauthenticator/issues/472) 의 중복으로 닫기. 여기에는 이것이 왜 그런지와 원하는 것을 얻는 방법에 대한 설명이 있습니다.
> 
> ```python
> c.OAuthenticator.logout_redirect_url = "https:///your-keycloack/..."
> ```

i tried but.. didnt works T-T

**Closed by minrk** 2024-08-23 06:46 UTC
Labels: bug
