### ISSUE TITLE
Not able to  Spawn single-user notebook on Kubernetes cluster using kubespawner 

### ISSUE THREAD

**Issue by BShraman** [jupyterhub/jupyterhub#4025] opened 2022-08-31 13:01 UTC
### Bug description

Hi Folks!
I am trying to spawn single-user notebook on Kubernetes cluster using kubespawner . I am able to login using LDAP authenticator and I can see corresponding Kubernetes instance has been created in Kubernetes cluster. But service is not able to respond.
I tried with increasing http_timeout and start_timeout but no luck yet and hoping to get some advice what might have gone wrong.

I have seen similar post and tried with all the suggestion, but nothing seems to be working so far.

Any help would be greatly appreciated. 

#### Expected behaviour

Once login is successful, process should start the server and user should be able to see notebook

#### Actual behaviour

Spawn failed : Server at xxxxx didn't responded in 60 second

### How to reproduce

Run jupyterhub with below config 
Config:
import logging

c.JupyterHub.log_level = logging.DEBUG
c.KubeSpawner.debug = True
c.SwarmSpawner.debug = True
c.NotebookApp.allow_root=True

import os
import socket

c.JupyterHub.spawner_class = 'kubespawner.KubeSpawner'
#c.Spawner.cmd = ['start.sh', 'jupyter', 'labhub']
c.JupyterHub.ip = str('0.0.0.0')
c.JupyterHub.hub_ip = str('127.0.0.1')
c.JupyterHub.cleanup_servers = False
c.KubeSpawner.start_timeout = int(3600)
c.Spawner.http_timeout = int(60)
c.JupyterHub.tornado_settings = {'slow_spawn_timeout': 30}

if os.environ.get("CI"):
    c.JupyterHub.hub_connect_ip = "127.0.0.1"
else:
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80))
    host_ip = s.getsockname()[0]
    s.close()

    c.JupyterHub.hub_connect_ip = host_ip

c.KubeSpawner.image = str('xxxxx/bdp-jupyter-rc:7')
c.KubeSpawner.service_account = str('xxxxxx')
c.KubeSpawner.image_pull_policy = str('IfNotPresent')

c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator'
c.KubeSpawner.storage_pvc_ensure = False
c.JupyterHub.allow_named_servers = True
c.KubeSpawner.profile_list = [
    {
        'display_name': 'BDP Sandbox',
        'default': True,
        'kubespawner_override': {
            'image': 'xxxxx/xxxxx/bdp-jupyter-rc:7',
            'cpu_limit': 1,
            'mem_limit': '512M',
        }
    }
]
### Your personal set up

 - OS:
Environment:
Jupyterhub : 2.2.2
jupyterhub-kubespawner : 4.2.0

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
**Error :** 
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/49772843/187684430-e8c2db02-1b50-4687-b357-28b4de1e03fb.png">

</details>

**Comment by manics** [comment] 2022-08-31 13:10
This looks like a duplicate of https://discourse.jupyter.org/t/spawn-single-user-notebook-on-kubernetes-cluster-using-kubespawner/15569

**Closed by manics** 2022-08-31 13:10 UTC
Labels: support
