### ISSUE TITLE
Jupyter Hub embedding in Web Application Failing with cross-origin error. 

### ISSUE THREAD

**Issue by kaivalyapendse** [jupyterhub/jupyterhub#4192] opened 2022-11-01 12:09 UTC
We are trying to integrate the Jupyter Hub into our web application. The integration is based on embedding the Jupyter Hub URL using `iframe` in the HTML. We are able to embed the login page but not able to go ahead. The error we are getting is: 

`Blocked autofocusing on a <input> element in a cross-origin subframe.`

The configuration is as follows:

in **jupyterhub_config.py**:

c.JupyterHub.tornado_settings = {
“headers”: {
“Content-Security-Policy”: “frame-ancestors ‘self’ ip:port”,
“Access-Control-Allow-Origin”: “ip:port”,
}
}

in **jupyter_notebook_config.py**:

c.NotebookApp.tornado_settings = {
“headers”: {
“Content-Security-Policy”: “frame-ancestors ‘self’ ip:port”,
“Access-Control-Allow-Origin”: “ip:port”,
}
}

we have also tried the variation such as removing self, including **_*_** in the above config. But the error persists.

Kindly suggest the solution.

Thank you.

PS: I know this is not _issue_ per say, but we would really need the community help regarding this.

**Comment by manics** [comment] 2022-11-01 20:21
This is a duplicate of https://discourse.jupyter.org/t/jupyterhub-integration-in-web-application/16590

**Closed by manics** 2022-11-01 20:21 UTC
Labels: duplicate
