### ISSUE TITLE
Running Jupyterhub as a Service from a virtual env

### ISSUE THREAD

**Issue by JoshuaC3** [jupyterhub/jupyterhub#1010] opened 2017-03-07 12:32 UTC
**How to reproduce the issue**

I follow [these](https://www.youtube.com/watch?v=gSVvxOchT8Y&feature=youtu.be) instructions but as the current Anaconda release was 3.6 and there are conflicts with jupyterhub dependences. Therefore, I did
`source create -n jpserver python=3.5` and then `source activate jpserver`.
Then I installed jupyterhub within the jpserver virtual_env.

This all works nicely when running jupyterhub as a root as a logged in user (and with jpserver activated). The issue came when I was trying to run this as a service. I tried to use [this](https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service) to set it up. Unfortunatley, I do not know what to change from ### END INIT INFO to make this work.

**What happens**

The service Daemon runs but the jupyterhub is not accessible, I assume as the virtual_env is not activated, therefore there is not `jupyterhub` command to call.

**Share what version of JupyterHub you are using** - 0.8

**Comment by minrk** [comment] 2017-03-10 03:31
When it works in a shell but fails in a service, the issue is almost always related to the PATH. Services often start with the barest of bare environments, including only having a sparse PATH such as `/usr/bin:/bin`. There are a few ways to deal with this:

1. specify the absolute path to an executable
2. add environment variables to your service specification
3. launch a wrapper script that initializes the environment 

I tend to like number 3 the best in my personal use, since it means I spend the least time editing and reloading service config files, and spend more time editing more familiar (to me) shell scripts. I often have a service that looks like this:

```ini
ExecStart: /srv/jupyterhub/launch.sh
```

and `/srv/jupyterhub/launch.sh` looks like:

```bash
#!/bin/bash -l
export PATH=/opt/conda/bin:$PATH
export GITHUB_OAUTH_SECRET=...

# always end with `exec jupyterhub [...]`
exec jupyterhub

**Comment by JoshuaC3** [comment] 2017-03-10 10:20
I tried option 2 but this didn't work. I couldn't say why.

I then tried a different method of using `systemd`. This seems a lot more straight forwards. I posted my solution at the bottom of this [wiki page](https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service) for other users. Hopefully, it is ok to do that.

Thanks for your help.

**Comment by willingc** [comment] 2017-03-27 16:13
Closing this issue since it appears to be resolved. Thanks @JoshuaC3 for posting your solution. I'm going to label this as Reference too. Thanks! 🌞

**Closed by willingc** 2017-03-27 16:13 UTC
Labels: configuration, question
