### ISSUE TITLE
Empty Admin panel on JupyterHub 3.0.0

### ISSUE THREAD

**Issue by jiayuasu** [jupyterhub/jupyterhub#4231] opened 2022-11-30 07:19 UTC
### Bug description

JupyterHub 3.0.0 shows an empty Admin panel while JupyterHub 2.3.1 shows the correct panel with the same config.

#### Expected behaviour

![image](https://user-images.githubusercontent.com/10948864/204731081-5a35d29d-264a-411a-acac-f42b39f45eee.png)

#### Actual behaviour

![image](https://user-images.githubusercontent.com/10948864/204731210-f081af1e-a65d-4a55-898b-0dad12522c41.png)

### How to reproduce

Open the admin panel on JupyterHub

### Your personal set up

Content in `Dockerfile`:

```
FROM jupyterhub/jupyterhub:3.0.0

MAINTAINER Project Jupyter <ipython-dev@scipy.org>

RUN python3 -m pip install jupyterlab

# Add JupyterNotebook config
WORKDIR /etc/jupyter/
ADD jupyter_notebook_config.py jupyter_notebook_config.py

# Create oauthenticator directory and put necessary files in it
RUN mkdir /etc/jupyterhub/
WORKDIR /etc/jupyterhub/
ADD jupyterhub_config.py jupyterhub_config.py

```

Content in `jupyerhub_config.py`

```
import os
import sys

c = get_config()

c.Spawner.args = ['--NotebookApp.tornado_settings={"headers":{"Content-Security-Policy": "frame-ancestors * self "}}']   

c.JupyterHub.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors * self "
  }
}

c.JupyterHub.log_level = 10
c.JupyterHub.admin_access = True
c.JupyterHub.shutdown_on_logout = True

c.Authenticator.admin_users = {'XXX'}
c.LocalAuthenticator.create_system_users = True
c.LocalAuthenticator.add_user_cmd = ['adduser', '-q', '--gecos', '', '--disabled-password', '--force-badname']
```

**Comment by minrk** [comment] 2022-11-30 13:11
This is a duplicate of #4033, fixed by #4034. We're planning to make a new release in the next week.

**Closed by minrk** 2022-11-30 13:11 UTC
Labels: bug
