### ISSUE TITLE
[Help] Randomly getting 403 while opening spawned notebook

### ISSUE THREAD

**Issue by akhilputhiry** [jupyterhub/jupyterhub#2351] opened 2018-12-06 10:30 UTC
I am getting 403 error randomly while opening the spawned notebooks. I checked the logs, it says the state param present within the query param and the cookie is not matching. I tried decoding the params and they were different.

```
# Query Param
{"uuid": "e6f21e8e32ea4e46b5e0ee631e41cc27", "next_url": "/notebooks/proxy/user/2304677352/384a45b8-2e0c-4503-9862-da7871272e0b/notebooks/untitled-3.ipynb"}

# Cookie
{"uuid": "a396011eb857419ca67513e365ac794a", "next_url": "/notebooks/proxy/user/2304677352/384a45b8-2e0c-4503-9862-da7871272e0b/api/kernelspecs"}
```

This is happening only in safari, I tried to replicate the same in chrome, but was not able to reproduce.

Can someone helps me to understand this behaviour. @yuvipanda @minrk any thoughts?

I am assuming that this is what happening there..

* Two requests from the same container reaches jupyter hub
  - one from `/notebooks/proxy/user/2304677352/384a45b8-2e0c-4503-9862-da7871272e0b/notebooks/untitled-3.ipynb`
  - other from `/notebooks/proxy/user/2304677352/384a45b8-2e0c-4503-9862-da7871272e0b/api/kernelspecs`
* Both of them are assigned different states
* Since both of them belongs to the same domain, cookie gets rewritten
* Resulting in the state mismatch

**Comment by akhilputhiry** [comment] 2018-12-06 10:54
My confusion is I am trying to open notebook via `/notebooks/proxy/user/2304677352/384a45b8-2e0c-4503-9862-da7871272e0b/notebooks/untitled-3.ipynb` and how this `/notebooks/proxy/user/2304677352/384a45b8-2e0c-4503-9862-da7871272e0b/api/kernelspecs` is also getting triggered.

**Comment by akhilputhiry** [comment] 2018-12-06 10:56
One possibility is that by the time jupyter identifies that the user is not logged in and tries to redirect request to `kernelspecs` has already happened.

**Comment by minrk** [comment] 2018-12-06 10:57
How are you getting the `/notebooks/proxy/user/...` url? That's not a normal jupyterhub url.

**Comment by minrk** [comment] 2018-12-06 10:59
This error is from the login process. Is there a chance that your server got restarted while you were using it? Do you have your jupyterhub configuration? Is there an nginx or apache in front? How are you deploying jupyterhub (kubernetes, which spawner, authenticator, etc.)?

**Comment by akhilputhiry** [comment] 2018-12-06 11:00
> How are you getting the `/notebooks/proxy/user/...` url? That's not a typical jupyterhub url.

I have my `CHP` configured in `/notebooks/proxy` and I am creating user servers. So it create routes in the format `/user/<userid>/<serverid>`

**Comment by minrk** [comment] 2018-12-06 11:01
ah, ok. So named servers are enabled. This may be relevant!

**Comment by minrk** [comment] 2018-12-06 11:01
I believe oauth can get a little confused if there are multiple login processes happening at the same time in the same browser with the same server. Could there be multiple tabs or windows connected to the same server? This isn't normally an issue, but it can be if two tabs are trying to *login* at the same time.

**Comment by akhilputhiry** [comment] 2018-12-06 11:01
> This error is from the login process. Is there a chance that your server got restarted while you were using it? Do you have your jupyterhub configuration? Is there an nginx or apache in front? How are you deploying jupyterhub (kubernetes, which spawner, authenticator, etc.)?

I have an nginx in front of jupyterhub and I have deployed it on top of a kubernetes.

**Comment by akhilputhiry** [comment] 2018-12-06 11:02
> I believe oauth can get a little confused if there are multiple login processes happening at the same time in the same browser with the same server. Could there be multiple tabs or windows connected to the same server? This isn't normally an issue, but it can be if two tabs are trying to _login_ at the same time.

Yes. I have multiple servers opened in multiple tabs

**Comment by akhilputhiry** [comment] 2018-12-06 11:03
@minrk This happens when I spawn multiple notebooks and tries to open them in multiple tabs. With just one or one after the other things works fine

**Comment by minrk** [comment] 2018-12-06 11:03
ok, I'm guessing it's the multiple servers in multiple tabs. Can you try to isolate the sequence of actions that causes the issue? i.e. clear cookies, login to one server, do a few things, then login to another server, then try to use the first one, etc.

**Comment by minrk** [comment] 2018-12-06 11:04
Can you also share the path on which the login cookies are set? It should be `/notebooks/proxy/user/:user/:server/`. If it's `/notebooks/proxy/user/:user/` then that would probably be the cause.

**Comment by akhilputhiry** [comment] 2018-12-06 11:06
I did that what I am seeing is

* hit the notebook URL
* 302 to `/authrorize`
* Callback from `/oauth_callback`

> Can you also share the path on which the login cookies are set? It should be `/notebooks/proxy/user/:user/:server/`. If it's `/notebooks/proxy/user/:user/` then that would probably be the cause.

Verified cookie path. Its in `/notebooks/proxy/user/2304677352/384a45b8-2e0c-4503-9862-da7871272e0b/`

which is effectively `/notebooks/proxy/user/:user/:server/`

**Comment by minrk** [comment] 2018-12-06 11:07
ok, that's right at least

**Comment by akhilputhiry** [comment] 2018-12-06 11:07
This is the flow

* hit the notebook URL
* 302 to `/authorize`
* Callback from `/oauth_callback` => results in 403

**Comment by minrk** [comment] 2018-12-06 11:08
That's the right sequence of events if oauth state is inconsistent, i.e. another oauth started before that one finished.

**Comment by minrk** [comment] 2018-12-06 11:09
Can you reproduce this by connecting to one server, closing that tab, then connecting to the second, then closing that tab, then connecting to the first again?

**Comment by akhilputhiry** [comment] 2018-12-06 11:19
> Can you reproduce this by connecting to one server, closing that tab, then connecting to the second, then closing that tab, then connecting to the first again?

@minrk I am able to open and close in the order you mentioned. No issues.

**Comment by minrk** [comment] 2018-12-06 11:41
OK. And if you do the same thing, but leave the second server open can you access the first server again?

**Comment by akhilputhiry** [comment] 2018-12-06 12:17
> OK. And if you do the same thing, but leave the second server open can you access the first server again?

That too is working..

**Comment by minrk** [comment] 2018-12-10 14:34
If the last thing worked, that means you are authenticated to both servers and they both work. Is that the case?

**Comment by akhilputhiry** [comment] 2018-12-11 03:56
@minrk yes.

This 403 happens only if I try to open multiple servers in multiple tabs very quickly. Even if the 403 occur, if I close and reopen then it works normally. As you mentioned earlier while performing multiple oauth at the same time, cookies are being replaced.

**Comment by minrk** [comment] 2018-12-11 13:42
ah, ok. If it happens only if both logins occur very quickly, then I think there are no issues here. I'm not sure if we can make simultaneous oauth to multiple endpoints work, but I'm comfortable saying that it doesn't work right now and waiting a few seconds to login again will fix it.

**Comment by akhilputhiry** [comment] 2018-12-11 15:53
Thanks a lot @minrk 

Let me know if someone has innovative ideas on getting rid of this 403. Happy to work on this one.

**Comment by akhilputhiry** [comment] 2018-12-12 09:33
@minrk Please have a look at this one https://github.com/p2/OAuth2/issues/79 May shed some light on our problem

**Comment by manics** [comment] 2021-02-17 21:23
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!

**Closed by manics** 2021-02-17 21:23 UTC
