### ISSUE TITLE
Spawner / ProgressAPI only flushing events once the server is ready

### ISSUE THREAD

**Issue by nibheis** [jupyterhub/jupyterhub#4043] opened 2022-09-15 10:05 UTC
Hello JupyterHub community,

We are running a custom spawner here at EPFL - a kind of mix between `systemd` and `ssh` spawner (our hub spawns jupyterlab containers as systemd units on remote servers). It's been running great for the last 3 years now.

This week, we made custom html/css templates for our Hub and I thought it was a good time to also pimp up the event log on the spawning page. Currently, the two events:
- `Server requested`
- `Server ready at ...`

both emitted by JupyterHub (our spawner did not implement the `progress()` method yet) arrive in one shot when the server is ready. The progress bar stays at 0 for ~10 seconds and then blinks to 100 and the user is redirected.

I implemented a proper `progress()` method (by having a look at different spawner implementation), but still all events won't show until the very end. I added delays and traced from the hub side and from the browser's console side too. While the events are emitted asynchronously and periodically (respecting the delays) by the Spawner, on the browser side they all arrive in one shot when the server is ready.

I also noticed that when the `progress()` method raises an exception, the events are flushed - and then `_generate_progress(self)` is called again (the `Server requested` event is sent again).

The only way I found to have SpawnProgressAPIHandler (from `jupyterhub/apihandlers/users.py`) actually flush the messages systematically has been to change the `send_event()` method from:
```
    async def send_event(self, event):
        try:
            self.write(f'data: {json.dumps(event)}\n\n')
            await self.flush()
        except StreamClosedError:
            self.log.warning("Stream closed while handling %s", self.request.uri)
            # raise Finish to halt the handler
            raise web.Finish()
```
to:
```
    async def send_event(self, event):
        try:
            self.write(f'data: {json.dumps(event)}\n\n')
===>        raise web.Finish()
            #await self.flush()
        except StreamClosedError:
            self.log.warning("Stream closed while handling %s", self.request.uri)
            # raise Finish to halt the handler
            raise web.Finish()
```

By raising `web.Finish()`, the handler is actually flushed. I know, this is certainly not the proper way of doing it - I'm just testing things.
So, what should I do now? JupyterHub (both 2.3.1 and 3.0.0) do not flush events until the server is ready.
Am I overlooking some jupyterhub settings or something else?

Thanks for your help!

**Comment by manics** [comment] 2022-09-15 20:43
Hi! I've just tested progress events with JupyterHub 3.0.0, and they're working fine for me.

If you think you've found a bug please could you give us a minimal reproducible example? If you don't think it's a bug then we usually try and handle support on the [Jupyter Community Forum](https://discourse.jupyter.org/), the big advantage of that forum is that others can benefit from the discussions.

**Comment by nibheis** [comment] 2022-09-16 08:09
Hi @manics,

Thanks for the tips. Yes, I should probably have asked in the forum. However, I did my homework and searched everywhere before reporting this bug :
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1090
https://discourse.jupyter.org/t/custom-spawner-spawn-progress-troubleshooting/11846
...
all I found was not providing much clues and solutions.

Also, I am using a spawner that does not override the defaut progress() method from spawner.py - there is no reason jupyterhub progress events should not work right out of the pip box.

**Comment by nibheis** [comment] 2022-09-16 08:13
Anyway, I'll join the forum and start a new discussion on the topic.

**Comment by manics** [comment] 2022-09-22 14:36
Closing, this is being answered on https://discourse.jupyter.org/t/spawner-progressapi-only-flushing-events-once-the-server-is-ready/15867

**Closed by manics** 2022-09-22 14:36 UTC
Labels: bug

**Comment by lflis** [comment] 2023-08-26 14:14
@nibheis did you manage to solve the issue on your side?
I am trying to resolve it with wrapspawner + batchspawner right now

**Comment by nibheis** [comment] 2023-08-26 18:34
Hi! Nope, not resolved on my side.
I guess I must be doing something wrong in my spawner.

**Comment by lflis** [comment] 2023-08-26 19:47
For the record, which pytnon version are you running for this setup? 
Is your jupyterhub running behind a proxy? (nginx?)

**Comment by lflis** [comment] 2023-08-30 09:04
In my case problem with late progress flushing was caused by python implementation of configurable-http-proxy. Switching to np solved the problem. Bug was confirmed by CHP team:
https://github.com/corridor/configurable-http-proxy/issues/17
