### ISSUE TITLE
Best way for sharing notebook files [*.ipynb] between between jupyterhub users.

### ISSUE THREAD

**Issue by hemantasingh** [jupyterhub/jupyterhub#1644] opened 2018-02-02 16:22 UTC
Hi Team,

I'm looking for best way for sharing notebook files [*.ipynb] between between jupyterhub users.
I was trying to install some example like nbexamples, but end up with installation [issue](https://github.com/danielballan/nbexamples/issues/31).  
Please suggest me something similar. thanks

Hemant

**Comment by RaRam** [comment] 2018-03-19 14:19
Hi,
I actually have the same problem.
Did you solve it?

**Comment by willingc** [comment] 2018-05-02 04:14
Closing as a duplicate of #394 

Following the JupyterHub and Hubshare releases as well as viewing the Jupyter mailing list, would be the places to keep up to date on sharing. We agree it's an important feature ☀️

**Closed by willingc** 2018-05-02 04:14 UTC

**Comment by hemantasingh** [comment] 2018-05-02 05:45
Hi RaRam,
I did it in very simple way.
1. Create a public folder 
2. Place all the reviewed file in this folder.
3. Create a UI nbextension with a modal popup which list all the files
4. User select [input box] the particular file.
5. Then copy the file using Server extension to home/dashboard page.   

Just copy those file . that all
