### ISSUE TITLE
How could I run JupyterHub without root?

### ISSUE THREAD

**Issue by qingzhouzhen** [jupyterhub/jupyterhub#1061] opened 2017-04-07 07:36 UTC
How could I run JupyterHub with normal user?
 https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges  
This guide still use sudo to run the JupyterHub. If I customed the Authenticator, then I can run Jupyterhub with normal user?

**Comment by minrk** [comment] 2017-04-07 09:50
> This guide still use sudo to run the JupyterHub

The guide uses sudo, but never to become root. It sets up restricted sudo permissions to allow the Hub user to become specific other users only to launch their notebook servers, nothing else.

**Comment by willingc** [comment] 2017-04-07 11:35
@minrk I made the guide on the wiki highlight the restricted purpose.

I'm going to recommend closing this. @qingzhouzhen, I hope @minrk's response helps.

**Closed** 2017-04-12 00:00 UTC
Labels: question, reference

**Comment by stanleyxu2005** [comment] 2017-06-09 10:41
The problem is I even dont have sudo permission. I just want to run Jupyter under a normal user account. Is is possible? Otherwise I have to leave jupyterhub community and seek for other solutions.. Really dont understand.

**Comment by tundratim** [comment] 2017-07-16 13:10
@stanleyxu2005  Can you say more about how you got Jupyterhub running without root, sudo, or docker.  I have a corporate client that wants to run the entire thing inside an nonprivileged account and their policy forbids docker on servers.

**Comment by stanleyxu2005** [comment] 2017-07-16 14:56
@tundratim We run Jupyter as a corporate client (unprivileged account). The current workaround is using the SimpleSpawner https://github.com/yuvipanda/jupyterhub-simplespawner

**Comment by ola-t** [comment] 2017-11-08 20:26
SimpleWpawner is not recomanded on Production, is there any work around? I would like to use jupyter for training purpuse
