### ISSUE TITLE
Have login redirect, redirect back to original uri after login.

### ISSUE THREAD

**Issue by jstrength** [jupyterhub/jupyterhub#664] opened 2016-07-26 17:23 UTC
Hello,
This is more of a feature request rather than an issue, but it would be cool if when you are not logged in and you click a linked that requires a login that it redirects you back to that original link after you've logged in.

**Comment by minrk** [comment] 2016-07-27 15:01
That is in fact already the intended behavior, and what I see when I test it out. Can you give an example where this doesn't happen?

**Comment by jstrength** [comment] 2016-07-27 22:24
Say someone sends me a link to localhost/user/me/notebooks/somenb.ipynb and I click it when I am not logged in, it will take me to the login screen. After I login it takes me to localhost/usr/me/tree instead of the link I originally clicked on.

**Comment by minrk** [comment] 2016-07-28 08:48
okay, thanks. That case is allegedly covered in the tests, so I'll have to investigate what's going wrong. What version of JupyterHub are you using?

**Comment by jstrength** [comment] 2016-07-28 16:36
I'm currently running version 0.6.1 
I have the --no-ssl flag on, but besides that I think everything is default.

**Comment by ch41rmn** [comment] 2016-08-03 02:58
I have run into this problem, and have figured out a reproducible case:

- Have at least 2 users (userA, userB) in JupyterHub
- Log in as userA, in control panel, make sure userB's server is stopped
- URL `/user/userB/foo/bar` redirects to `/user/userA/foo/bar`
- URL `/user/userB/tree/foo/bar` redirects to `/user/userA/tree/foo/bar`
- URL `/user/userB/notebooks/foo/bar` redirects to `/user/userA/notebooks/foo/bar`
- in control panel, start userB's server (still logged in as userA)
- URL `/user/userB/foo/bar` does not redirect
- URL `/user/userB/tree/foo/bar` redirects to `/user/userA/tree`
- URL `/user/userB/notebooks/foo/bar` redirects to `/user/userA/tree`

**Comment by ch41rmn** [comment] 2016-08-03 04:12
On `master`:

- Have at least 2 users (userA, userB) in JupyterHub
- userA logged in, userB server is stopped
    - URL `/user/userB/foo/bar` redirects to `/user/userA/foo/bar`
    - URL `/user/userB/tree/foo/bar` redirects to `/user/userA/tree/foo/bar`
    - URL `/user/userB/notebooks/foo/bar` redirects to `/user/userA/notebooks/foo/bar`
- userA logged in, userB server is running
    - URL `/user/userB/foo/bar` does not redirect
    - URL `/user/userB/tree/foo/bar` redirects to `/user/userA/tree/foo/bar`
    - URL `/user/userB/notebooks/foo/bar` redirects to `/user/userA/notebooks/foo/bar`
- userA logged out, userB server is stopped
    - URL `/user/userB/foo/bar` redirects to `/login?next=<prefix>%2Fuser%2FuserB%2Ffoo%2Fbar`
    - URL `/user/userB/tree/foo/bar` redirects to `/login?next=<prefix>%2Fuser%2FuserB%2Ftree%2Ffoo%2Fbar`
    - URL `/user/userB/notebooks/foo/bar` redirects to `/login?next=<prefix>%2Fuser%2FuserB%2Fnotebooks%2Ffoo%2Fbar`
- userA logged out, userB server is running
    - URL `/user/userB/foo/bar` does not redirect
    - URL `/user/userB/tree/foo/bar` redirects to `/login?next=<prefix>%2Fuser%2FuserB%2Ftree%2Ffoo%2Fbar`
    - URL `/user/userB/notebooks/foo/bar` redirects to `/login?next=<prefix>%2Fuser%2FuserB%2Fnotebooks%2Ffoo%2Fbar`

**Comment by minrk** [comment] 2016-08-03 09:23
@ch41rmn thanks for the detailed coverage! I think we can write a test case for each one, if we don't have them already.

In master, what does `/user/userB/foo/bar` do instead of redirecting?

**Comment by eburgueno** [comment] 2016-10-25 03:05
Hello, I was running into this issue recently, which is similar to #424. I couldn't get it to work until I found this coverage.

One thing I noticed is that all of the test cases above assume that userA server is not running. In my tests, redirection *only* works when userA server is not running.

is this the intended/expected behaviour? would it be possible to make the URL redirection work even if the server for userA is running?

**Comment by minrk** [comment] 2016-10-25 11:48
@eburgueno are you running from master? I believe the case of both logged in and not is fixed in master (0.7), but there are still issues in 0.6.1. I'm working on release notes and docs for 0.7 now.

**Comment by eburgueno** [comment] 2016-10-25 19:38
@minrk I was using both the master branch and 0.6.1. If userA has a server running, redirection won't work on either version.

**Comment by minrk** [comment] 2016-10-26 12:14
@eburgueno thanks, I'll make sure that exact case is tested, and track down the bug. Just to be clear, the case is:

- userA is logged in, server running
- userB is logged in, server running
- userB tries to visit `/user/userA/foo/bar`

correct?

**Comment by eburgueno** [comment] 2016-10-26 21:06
Here's the coverage for that case:
* userA is logged in, server running. userB is logged in, server running
  * userB tries to visit `/user/userA/foo/bar`: URL does not redirect.
  * userB tries to visit `/user/userA/tree/foo/bar`: URL redirects to `/user/userB/tree`.
  * userB tries to visit `/user/userA/notebooks/foo/bar`: URL redirects to `/user/userB/tree`

**Comment by willingc** [comment] 2017-02-13 21:37
Closing as resolved.

**Closed by willingc** 2017-02-13 21:37 UTC
Labels: enhancement, help wanted, needs: testing
