### ISSUE TITLE
PAM ERROR

### ISSUE THREAD

**Issue by guoxiangyang12** [jupyterhub/jupyterhub#670] opened 2016-07-29 07:19 UTC
when i want to re-login after logout,there will be a mistake "[PAM Error 7] Authentication failure ",why?

**Comment by willingc** [comment] 2016-08-29 20:26
@guoxiangyang12 This appears to be a duplicate of https://github.com/jupyterhub/jupyterhub/issues/486.

**Closed by willingc** 2016-08-29 20:26 UTC
Labels: duplicate
