### ISSUE TITLE
cannot connect to X server

### ISSUE THREAD

**Issue by sacmehta** [jupyterhub/jupyterhub#698] opened 2016-08-20 00:01 UTC
Whenever I create an empty notebook in JupyterHub, I get the following error (irrespective of the python version):

: cannot connect to X server

I logged into the server with ssh + X11 forwarding.
P.S.: I am starting the jupyterhub with --no-ssl command

**Comment by willingc** [comment] 2016-08-21 15:27
Duplicate of mailing list post: https://groups.google.com/forum/#!topic/jupyter/LyaKA5SF52s

@takluyver response on mailing list:
Is it possible that something when a kernel starts is loading matplotlib (or pylab)? IPython itself shouldn't need an X server, but some matplotlib backends might.

**Comment by willingc** [comment] 2016-08-23 08:20
## [Resolution from mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jupyter/LyaKA5SF52s/qOHmERDTDQAJ)

@sacmehta:
We found the issue.

When we are running Jupyter notebook, DISPLAY variable was set, but when we running JupyterHub DISPLAY variable was empty and thus we were getting this error.

We checked the Display variable as:
```
import os
print os.environ['DISPLAY']
```
Many thanks for your responses and help. Really appreciate that.

@takluyver:
I'm still not sure why it needs DISPLAY at all; the IPython kernel should run in a headless environment. But I'm glad you worked it out.

**Closed by willingc** 2016-08-23 08:20 UTC
Labels: question
