### ISSUE TITLE
OAuth state missing from cookies

### ISSUE THREAD

**Issue by umar-sik** [jupyterhub/jupyterhub#1668] opened 2018-02-21 00:23 UTC
I am using kubernetes with jupyterhub. When I use Auth0 as an authentication API, I always get the error "OAuth state missing from cookies" after choosing my google account to log in.

What could be the issue?

Thanks

**Comment by umar-sik** [comment] 2018-02-21 00:23
I am using kubernetes with jupyterhub. When I use Auth0 as an authentication API, I always get the error "OAuth state missing from cookies" after choosing my google account to log in.

What could be the issue?

Thanks

**Comment by betatim** [comment] 2018-03-13 12:09
Duplicate of #1682

**Closed by betatim** 2018-03-13 12:09 UTC
