### ISSUE TITLE
Supporting the deployment of multiple hub services

### ISSUE THREAD

**Issue by icankeep** [jupyterhub/jupyterhub#3522] opened 2021-06-20 03:47 UTC
### Proposed change
Because the hub is a stateful service, we cannot deploy multiple hubs for load balancing, which will have a greater impact on users when the hub is restarted or updated. Can we consider supporting the deployment of multiple hub services?

**Comment by minrk** [comment] 2021-07-09 08:06
To avoid fragmenting the conversation, I'll close this as a duplicate of #1932 which has some points on what steps are required. I also presented this [as a poster at JupyterCon](https://figshare.com/articles/poster/The_cloud_is_the_limit_scaling_limits_of_JupyterHub/14937954) last year.

Short answer: it requires major changes to how the Hub works and necessarily losing several single-Hub-assuming performance optimizations, but it's doable and we will definitely try to tackle it when we have some resources.

**Closed by minrk** 2021-07-09 08:06 UTC
Labels: enhancement
