### ISSUE TITLE
Proxy redirects static|images|js|css to /hub/...

### ISSUE THREAD

**Issue by mpekalski** [jupyterhub/jupyterhub#643] opened 2016-07-15 13:11 UTC
I get a lot of 404, after redirects (302), and in the result the notebook does not work. The initial JupyterHub page works, I can also login using my system credentials. What I see in the log is basically

```
[I 2016-07-15 14:37:28.492 JupyterHub log:100] 302 GET /static/base/images/logo.png?v=7c4597ba713d804995e8f8dad448a397 (@127.0.0.1) 5.97ms
[W 2016-07-15 14:37:28.496 JupyterHub log:100] 404 GET /hub/static/base/images/logo.png?v=7c4597ba713d804995e8f8dad448a397 (@127.0.0.1) 2.50ms
14:37:28.528 - debug: [ConfigProxy] PROXY WEB /static/base/images/logo.png?v=7c4597ba713d804995e8f8dad448a397 to http://172.17.42.1:8081
```

When I go to directly the address (http://127.0.0.1:32778) the proxy should redirect me to everything works fine.
`14:40:48.503 - debug: [ConfigProxy] PROXY WEB /user/marcin to http://127.0.0.1:32778
`

When I go through JupyterHub (http://127.0.0.1:8000) I get a message

> 
Jupyter Notebook
404 : Not Found
You are requesting a page that does not exist!

The image I am using comes from
`docker pull jupyter/all-spark-notebook:latest`

On the host machine I have

```
marcin@vb:~$ npm --version
1.4.21
marcin@vb:~$ docker --version
Docker version 1.6.2, build 7c8fca2
marcin@vb:~$ jupyter --version
4.1.0
marcin@vb:~$ which -a jupyterhub
/usr/local/bin/jupyterhub
marcin@vb:~$ configurable-http-proxy --version
1.2.0
marcin@vb:~$ node --version
v0.10.25

```

and the docker image
```
jovyan@vb:~/work$ jupyter notebook --version
4.2.1
jovyan@vb:~/work$ jupyter --version
4.1.0
```

**Comment by mpekalski** [comment] 2016-07-15 14:49
I also tried different docker image, systemuser as described https://recordnotfound.com/dockerspawner-jupyterhub-119183, but I got exactly the same problem.

**Comment by mpekalski** [comment] 2016-07-15 16:07
I tried downgrading JupyterHub to 0.6.0 or 0.5.0 and it did not help.

**Comment by mpekalski** [comment] 2016-07-15 23:28
I tired building docker from https://github.com/jupyterhub/dockerspawner/tree/master/singleuser, but still the same problem. I tried explicitly providing env JPY_HUB_PREFIX = hub or /hub/ but it did not work either.

**Comment by willingc** [comment] 2016-07-22 05:55
@mpekalski I'm sorry for the delay in responding. Our core team was at SciPy conference and are in process of returning home.

I appreciate the details that you provided here. I'm wondering if the security or default SSL support is configured properly for your deployment. Here's a link to the section in our documentation on [Security, SSL, and the Proxy authentication token](http://jupyterhub.readthedocs.io/en/latest/getting-started.html#security).

@minrk, From the behavior that @mpekalski is seeing, do you have a suggestion on what to troubleshoot first?

**Comment by minrk** [comment] 2016-07-22 09:23
Can you share your jupyterhub_config.py and conda/pip list output for the Hub? Can you also show the full command being executed in the container (`ps aux`)? This suggests that the single-user server is not getting its `--base-url` set correctly because the static URL should be `/user/username/static`, not `/static/`.

**Comment by mpekalski** [comment] 2016-07-22 09:58
I run JupyterHub just by typing jupyterhub. At the moment for test/poc I build it without ssl support. 

What jupyter* is running on my VM
```
marcin@vb:~$ ps aux | grep jupyter
marcin    3460  0.1  1.7 201148 45416 pts/0    Sl+  11:42   0:01 /usr/bin/python3 /usr/local/bin/jupyterhub
marcin    3688  0.1  1.8 181000 48720 ?        S    11:44   0:01 /opt/conda/bin/python /opt/conda/bin/jupyter-notebook
marcin    3812  0.0  0.0  10716  2344 pts/2    S+   11:55   0:00 grep --color=auto jupyter
```

JupyterHub's **pip**
```
marcin@vb:~$ pip install jupyterhub
Requirement already satisfied (use --upgrade to upgrade): jupyterhub in ./Downloads/jupyterhub
Requirement already satisfied (use --upgrade to upgrade): alembic in /usr/local/lib/python3.4/dist-packages (from jupyterhub)
Requirement already satisfied (use --upgrade to upgrade): traitlets>=4.1 in /usr/local/lib/python3.4/dist-packages (from jupyterhub)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.1 in /usr/local/lib/python3.4/dist-packages (from jupyterhub)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/local/lib/python3.4/dist-packages (from jupyterhub)
Requirement already satisfied (use --upgrade to upgrade): pamela in /usr/local/lib/python3.4/dist-packages (from jupyterhub)
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy>=1.0 in /usr/local/lib/python3.4/dist-packages (from jupyterhub)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python3.4/dist-packages (from jupyterhub)
Requirement already satisfied (use --upgrade to upgrade): Mako in /usr/local/lib/python3.4/dist-packages (from alembic->jupyterhub)
Requirement already satisfied (use --upgrade to upgrade): python-editor>=0.3 in /usr/local/lib/python3.4/dist-packages (from alembic->jupyterhub)
Requirement already satisfied (use --upgrade to upgrade): decorator in /usr/local/lib/python3.4/dist-packages (from traitlets>=4.1->jupyterhub)
Requirement already satisfied (use --upgrade to upgrade): ipython-genutils in /usr/local/lib/python3.4/dist-packages (from traitlets>=4.1->jupyterhub)
Requirement already satisfied (use --upgrade to upgrade): backports_abc>=0.4 in /usr/local/lib/python3.4/dist-packages (from tornado>=4.1->jupyterhub)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/local/lib/python3.4/dist-packages (from jinja2->jupyterhub)
```

That is all I have got uncommented in **jupyterhub_config.py**

```
c.JupyterHub.cleanup_servers = False
c.JupyterHub.confirm_no_ssl = True
c.JupyterHub.debug_proxy = True
c.Spawner.debug = True
c.DockerSpawner.container_image = 'jupyter/all-spark-notebook:latest'
c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
```



Jupyter container's **ps aux**
```
marcin@vb:~$ docker ps
CONTAINER ID        IMAGE                               COMMAND                CREATED             STATUS              PORTS                       NAMES
fec6f291e91a        jupyter/all-spark-notebook:latest   "tini -- start-noteb   7 days ago          Up 4 days           127.0.0.1:32768->8888/tcp   jupyter-marcin
marcin@vb:~$ docker exec -it jupyter-marcin bash     
jovyan@fec6f291e91a:~/work$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
jovyan       1  0.0  0.0   4224   652 ?        Ss   09:44   0:00 tini -- start-notebook.sh
jovyan       5 11.6  1.8 181000 48720 ?        S    09:44   0:01 /opt/conda/bin/python /opt/conda/bin/jupyter-notebook
jovyan       9  0.1  0.1  21836  3456 ?        Ss   09:44   0:00 bash
jovyan      15  0.0  0.0  19100  2476 ?        R+   09:44   0:00 ps aux
```


Jupyter container's /usr/local/bin/**start-notebook.sh** 
```
jovyan@fec6f291e91a:~/work$ more /usr/local/bin/start-notebook.sh 
#!/bin/bash

# Handle special flags if we're root
if [ $UID == 0 ] ; then
    # Change UID of NB_USER to NB_UID if it does not match
    if [ "$NB_UID" != $(id -u $NB_USER) ] ; then
        usermod -u $NB_UID $NB_USER
        chown -R $NB_UID $CONDA_DIR .
    fi

    # Enable sudo if requested
    if [ ! -z "$GRANT_SUDO" ]; then
        echo "$NB_USER ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/notebook
    fi

    # Start the notebook server
    exec su $NB_USER -c "env PATH=$PATH jupyter notebook $*"
else
    # Otherwise just exec the notebook
    exec jupyter notebook $*
fi
```

Jupyter container's **environment** variables
```
jovyan@fec6f291e91a:~/work$ env 
SPARK_HOME=/usr/local/spark
HOSTNAME=fec6f291e91a
NB_USER=jovyan
SHELL=/bin/bash
JPY_USER=marcin
JPY_API_TOKEN=05ca4dc99d8f49d78007dfe85e0fcf62
JPY_BASE_URL=/user/marcin
SPARK_OPTS=--driver-java-options=-Xms1024M --driver-java-options=-Xmx4096M --driver-java-options=-Dlog4j.logLevel=info
LC_ALL=en_US.UTF-8
LS_COLORS=
PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/home/jovyan/work
APACHE_SPARK_VERSION=1.6.1
JPY_HUB_PREFIX=/hub/
MESOS_NATIVE_LIBRARY=/usr/local/lib/libmesos.so
LANG=en_US.UTF-8
JPY_HUB_API_URL=http://127.0.0.1:8081/hub/api
JPY_COOKIE_NAME=jupyter-hub-token-marcin
SHLVL=1
HOME=/home/jovyan
LANGUAGE=en_US.UTF-8
PYTHONPATH=/usr/local/spark/python:/usr/local/spark/python/lib/py4j-0.9-src.zip
DEBIAN_FRONTEND=noninteractive
CONDA_DIR=/opt/conda
R_LIBS_USER=/usr/local/spark/R/lib
NB_UID=1000
_=/usr/bin/env
```

**Comment by minrk** [comment] 2016-07-22 10:43
Aha! You should actually use the `jupyter/all-spark-singleuser` image instead of `all-spark-notebook` to run the singleuser launch script.

**Comment by mpekalski** [comment] 2016-07-22 11:15
I guess that was causing the proxy issue. Now after logging in to the hub it shows:

`500 : Internal Server Error`

but that is because notebook cannot communicate with the hub. It is easily solvable by setting the hub's ip number in the **jupyterhub_config.py**

`c.JupyterHub.hup_ip = ....`

Thanks again for helping me out!

**Comment by willingc** [comment] 2016-07-22 13:52
@mpekalski I'm glad that you have it working. Thanks @minrk for spotting the root cause.

I'm going to close this issue, but please feel free to reopen if needed.

**Closed by willingc** 2016-07-22 13:52 UTC
Labels: question

**Comment by minrk** [comment] 2016-07-22 13:59
I opened #651 to give a better error when the single-user server can't connect to the Hub, pointing directly to `hub_ip` config. I'm not sure what the best way to catch the wrong entrypoint error would be, though.

**Comment by willingc** [comment] 2016-07-22 14:29
Thanks @minrk for #651. Perhaps adding a help message in the Dockerspawner https://github.com/jupyterhub/dockerspawner/blob/master/dockerspawner/dockerspawner.py#L76 would help with the  entrypoint error. It wouldn't catch it but could guide users to selecting a single user image.
