### ISSUE TITLE
Share notebooks between users

### ISSUE THREAD

**Issue by akansal1** [jupyterhub/jupyterhub#631] opened 2016-07-06 17:58 UTC
Hi,

Thanks for creating this project, I have hosted a jupyterhub on a server and have two users configured currently, I would like to know, is it possible to share notebooks between multiple users or groups ?

I am not able to figure out, how to go about it 

Till now I manage syncing of notebooks between users through google drive sync, but it would be great if, I can achieve it using hub

Thnx

**Comment by kitsirota** [comment] 2016-07-12 16:09
+1  We are also running into this problem, shared notebooks would be a HUGE help for us.  

Currently, I have a symlinked "shared_notebooks" directory in users' home directories.  This only works if users open the notebook in the shared space, download it and then re-upload it into their home dir.

**Comment by matteoipri** [comment] 2016-07-25 12:21
Using DockerSpawner, in the jupyterhub_config.py file you can add options to achieve something like read-only sharing.

```
# Map from host file/directory to container (guest) file/directory
# mount point and (optionally) a mode. When specifying the
# guest mount point (bind) for the volume, you may use a
# dict or str. If a str, then the volume will default to a
# read-write (mode="rw"). With a dict, the bind is
# identified by "bind" and the "mode" may be one of "rw"
# (default), "ro" (read-only), "z" (public/shared SELinux
# volume label), and "Z" (private/unshared SELinux volume
# label). If you use {username} in either the host or guest
# file/directory path, it will be replaced with the current
# user name.
c.DockerSpawner.volumes = {"/host/path/to/users/data/{username}": "/home/jovyan/work/"}

# Map from host file/directory to container file/directory.
# Volumes specified here will be read-only in the container.
# If you use {username} in the host file / directory path, it will be
# replaced with the current user name.
c.DockerSpawner.read_only_volumes = {"/host/path/to/shared/folder/": "/home/jovyan/work/shared-readonly-notebooks"}
```

Obviously you have to adjust the paths and play with them a little.
I think of these like a workaround, but I wouldn't know where to start to handle things like race conditions and two users editing at the same time like Google Docs.

**Comment by waldo1979** [comment] 2016-09-20 01:04
This works for me with "c.Dockerspawner.volumes" options. I'm using this as a starting point:
https://github.com/jupyterhub/jupyterhub-deploy-docker

I've created a docker volume "jupyterhub-sharednotebooks":
 38 c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir,
 39     'jupyterhub-sharednotebooks': {
 40         'bind': '/home/jovyan/work/shared',
 41         'mode': 'rw' }

$ docker volume ls
DRIVER              VOLUME NAME
local               XXXXXX
local               jupyterhub-data
local               jupyterhub-sharednotebooks

Make sure you create the docker volume with the appropriate user otherwise you could have file permission issues.

**Comment by barrachri** [comment] 2017-01-08 14:14
Consider also using NFS or something similar (https://github.com/jupyterhub/jupyterhub/issues/839)

**Comment by jiamicu** [comment] 2017-07-11 02:49
@waldo1979 Hi, I am new to JupyterHub . I have added the 
```
c.DockerSpawner.volumes = { 'jupyterhub-user-{username}': notebook_dir,
                            'jupyterhub-sharednotebooks': {
                            'bind': '/home/jovyan/work/share',
                            'mode': 'rw' }}
```
to  my config file ,and then I create the docker volume "jupyterhub-sharednotebooks" use `docker volume create jupyterhub-sharednotebooks` , but I get a 403 forbidden . I guess there is file permission issues, but I don't know how to solve it.
Thank you .

**Comment by gutow** [comment] 2020-06-21 11:56
A [repository](https://github.com/gutow/tljh_grp_utils) with some scripts for a workaround I am using on a littlest jupyter hub. Maybe this will be useful to someone.

**Comment by consideRatio** [comment] 2020-10-18 12:05
This is a very common request, and it is quite complicated for JupyterHub that supports various user environments to configure sharing as it cannot make assumptions about the user environments and the storage options available.

I'll close this as a duplicate of #394 - but in short, this is an unresolved feature request that is probably going to need to be solved outside of the main JupyterHub project, for example in specific distributions like tljh.jupyter.org, z2jh.jupyter.org, or even mroe opinionated distributions that derive from these like quansights qhub distribution.

**Closed by consideRatio** 2020-10-18 12:05 UTC
Labels: enhancement
