### ISSUE TITLE
Mounting a shared folder for each user

### ISSUE THREAD

**Issue by jpdus** [jupyterhub/jupyterhub#429] opened 2016-02-15 23:31 UTC
With reference to #394 and #424 : 

Is there any way to mount a folder for each user of a jupyterhub server, so that each user has read/write rights to all notebook in that shared folder?

If I mount a folder in the jupyter notebook home directory of each jupyterhub user (and add rw rights for all users for that folder), I am able to read notebooks created by other users - however they are always read-only.

Is there any way to circumvent this issue if the server is only used internally by trusted users? I already tried setting different user rights, umask 000 and so on - no success. However I am no linux admin, so sorrry if I am missing anything obvious, did not find any helpful tips on SO/google.
Or do I have to resort to a single notebook user (without jupyterhub) for this usecase?

**Comment by minrk** [comment] 2016-02-17 10:32
I'm not sure if there's a way to set the default permissions for new files based on the folder in which it is created. My understanding is that it's a process-wide setting for the files it creates. But this is a bit outside my Linux-fu, as well. Access Control may provide a solution, but I don't have experience with that.

**Comment by evanlinde** [comment] 2016-02-17 18:07
As long as the permission problem isn't being caused by a umask and your filesystem has ACL support, then setting a default ACL with `setfacl` should work.

Granting permission for a group named "jupyterhub_users" would look something like this:

`setfacl -m d:g:jupyterhub_users:rw `*`shared_folder`*

**Comment by willingc** [comment] 2016-06-06 14:08
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!

**Closed by willingc** 2016-06-06 14:08 UTC

**Comment by MarkAWard** [comment] 2016-11-08 23:36
The solution that @evanlinde provided worked for me

For any one coming here to solve a similar issue, I also ran in to the problem that a .ipynb_checkpoints/ had already been created by one of the users. I had to chown to my group and chmod 770 for that directory to allow other users access.

**Comment by dclong** [comment] 2017-09-25 14:41
@evanlinde @MarkAWard 

I tried both approaches here and the one in [issue 1402](https://github.com/jupyterhub/jupyterhub/issues/1402), however, both of them have the problem that the `.ipynb_checkpoints` do not have the right permission.

**Comment by evanlinde** [comment] 2017-09-25 17:05
@dclong Setting the ACL recursively may resolve your issue.

For example: `setfacl -R -m d:g:jupyterhub_users:rw`_`shared_folder`_


It may also be necessary to set the ACL mask: `setfacl -R -m d:mask:rwx`_`shared_folder`_

**Comment by dclong** [comment] 2017-09-26 14:41
@evanlinde 
It doesn't work for me. Newly created directories `.ipynb_checkpoints` still do not have the right permission. Which version of Jupyter Notebook and JupyterHub are you using? And your operating system? I'm using JupyterHub in Docker. Not sure whether that's the reason.

**Comment by evanlinde** [comment] 2017-09-26 17:45
My setup is on CentOS 7 and doesn't use Docker.

```
jupyter                   1.0.0                    py36_3
jupyter_client            5.0.1                    py36_0
jupyter_console           5.1.0                    py36_0
jupyter_core              4.3.0                    py36_0
jupyterhub                0.7.2                     <pip>
```

Here's some more info on the umask and ACLs (edited down to the relevant parts). These commands were run in the jupyter terminal.

```
$ umask
0022

$ getfacl .
group:my_group:rwx
mask::rwx
default:mask::rwx

$ getfacl ./.ipynb_checkpoints
group:my_group:rwx      #effective:r-x
mask::r-x
default:mask::rwx

$ getfacl ./.ipynb_checkpoints/Untitled-checkpoint.ipynb
group:my_group:rwx      #effective:rw-
mask::rw-
```

**Comment by dclong** [comment] 2017-09-27 15:32
@evanlinde 
Thank you! I'll try to setup JupyterHub without using Docker to whether the file permission issue can be resolved.

**Comment by nijisakai** [comment] 2022-01-11 15:53
> The solution that @evanlinde provided worked for me
> 
> For any one coming here to solve a similar issue, I also ran in to the problem that a .ipynb_checkpoints/ had already been created by one of the users. I had to chown to my group and chmod 770 for that directory to allow other users access.

Is it like manually exec `setfacl -Rm g:jupyterhub_users:rwx .ipynb_checkpoints` at every subfolder of the shared folder?
