### ISSUE TITLE
Simplying install and configuration

### ISSUE THREAD

**Issue by xmehaut** [jupyterhub/jupyterhub#657] opened 2016-07-25 13:25 UTC
Hello,

I would suggest to symplify the installation and configuration of jupyterhub through for instance a question/answer workflow (scaffolding) because it is difficult for non expert to make jupyterhub working easily.... I fo instance struggle with a "500: internal error" whn trying to run jupyterhub for a user and I can't find the way to make the tool working :-( (even after reading many forums like stackoverflow).

For your interest, I've a "Unhandled error starting <user>'s server : [errno 13] Permission denied" cryptic error ... 
The traceback finish on .../tornado/web.py, line 1445...

regards

**Comment by GISDev01** [comment] 2016-07-27 02:14
I do agree that there's a few things that could be improved on simplifying things, but it is actually pretty complicated under the hood, after all.

We might be able to help you out a bit better if you're able to give more information on your current configuration and what you've done so far. Are you able to post the whole error traceback?

**Comment by xmehaut** [comment] 2016-07-27 07:26
Thanks for your help

To give the context, i created an ansible playbook to industrialize the
installation of anaconda3 and 2 and jupyterhub too.

The install seems to work well, and Jupyterhub is able to be launched...
But once I try to connect with vm user (created with adduser), I've got the
following trace stack :
any clue?

regards

==================
09:22:33.491 - info: [ConfigProxy] Proxy API at
http://10.244.214.82:8889/api/routes
[I 2016-07-27 09:22:33.577 JupyterHub app:1075] JupyterHub is now running
at http://10.244.214.82:8888/
[I 2016-07-27 09:22:40.487 JupyterHub log:100] 302 GET / (@10.251.95.5)
1.73ms
[I 2016-07-27 09:22:40.494 JupyterHub log:100] 302 GET /hub (@10.251.95.5)
0.35ms
[I 2016-07-27 09:22:40.503 JupyterHub log:100] 302 GET /hub/ (@10.251.95.5)
0.70ms
[I 2016-07-27 09:22:40.544 JupyterHub log:100] 200 GET /hub/login (@
10.251.95.5) 29.89ms
[I 2016-07-27 09:22:58.454 JupyterHub spawner:409] Spawning
jupyterhub-singleuser --user=la18907 --port=33407
--cookie-name=jupyter-hub-token-la18907 --base-url=/user/la18907
--hub-prefix=/hub/ --hub-api-url=http://10.244.214.82:8081/hub/api
--ip=localhost
[E 2016-07-27 09:22:58.731 JupyterHub user:192] Unhandled error starting
la18907's server: [Errno 13] Permission denied
[E 2016-07-27 09:22:58.748 JupyterHub web:1524] Uncaught exception POST
/hub/login?next= (10.251.95.5)
    HTTPServerRequest(protocol='http', host='10.244.214.82:8888',
method='POST', uri='/hub/login?next=', version='HTTP/1.1',
remote_ip='10.251.95.5', headers={'Accept-Language': 'fr-FR',
'Accept-Encoding': 'gzip, deflate', 'X-Forwarded-Port': '8888', 'Accept':
'text/html, application/xhtml+xml, */*', 'Connection': 'close',
'X-Forwarded-For': '10.251.95.5', 'X-Forwarded-Proto': 'http', 'Host': '
10.244.214.82:8888', 'Cache-Control': 'no-cache', 'Content-Length': '38',
'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0)
like Gecko', 'Content-Type': 'application/x-www-form-urlencoded',
'Referer': 'http://10.244.214.82:8888/hub/login'})
    Traceback (most recent call last):
      File
"/apps/analytics/Anaconda3-2.5.0-Linux-x86_64/lib/python3.5/site-packages/tornado/web.py",
line 1445, in _execute
        result = yield result
      File
"/apps/analytics/Anaconda3-2.5.0-Linux-x86_64/lib/python3.5/site-packages/jupyterhub/handlers/login.py",
line 72, in post
        yield self.spawn_single_user(user)
      File
"/apps/analytics/Anaconda3-2.5.0-Linux-x86_64/lib/python3.5/site-packages/jupyterhub/handlers/base.py",
line 296, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout),
f)
      File
"/apps/analytics/Anaconda3-2.5.0-Linux-x86_64/lib/python3.5/site-packages/jupyterhub/user.py",
line 202, in spawn
        raise e
      File
"/apps/analytics/Anaconda3-2.5.0-Linux-x86_64/lib/python3.5/site-packages/jupyterhub/user.py",
line 183, in spawn
        yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File
"/apps/analytics/Anaconda3-2.5.0-Linux-x86_64/lib/python3.5/types.py", line
243, in wrapped
        coro = func(*args, **kwargs)
      File
"/apps/analytics/Anaconda3-2.5.0-Linux-x86_64/lib/python3.5/site-packages/jupyterhub/spawner.py",
line 412, in start
        start_new_session=True, # don't forward signals
      File
"/apps/analytics/Anaconda3-2.5.0-Linux-x86_64/lib/python3.5/subprocess.py",
line 950, in __init__
        restore_signals, start_new_session)
      File
"/apps/analytics/Anaconda3-2.5.0-Linux-x86_64/lib/python3.5/subprocess.py",
line 1544, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    PermissionError: [Errno 13] Permission denied
[E 2016-07-27 09:22:58.760 JupyterHub log:99] {
      "Accept-Language": "fr-FR",
      "Accept-Encoding": "gzip, deflate",
      "X-Forwarded-Port": "8888",
      "Accept": "text/html, application/xhtml+xml, */*",
      "Connection": "close",
      "X-Forwarded-For": "10.251.95.5",
      "X-Forwarded-Proto": "http",
      "Host": "10.244.214.82:8888",
      "Cache-Control": "no-cache",
      "Content-Length": "38",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0;
rv:11.0) like Gecko",
      "Content-Type": "application/x-www-form-urlencoded",
      "Referer": "http://10.244.214.82:8888/hub/login"
    }
[E 2016-07-27 09:22:58.760 JupyterHub log:100] 500 POST /hub/login?next= (@
10.251.95.5) 1015.88ms

2016-07-27 4:14 GMT+02:00 GISDev01 <notifications@github.com>:

**Comment by xmehaut** [comment] 2016-07-27 07:30
(...)
maybe to help...Once I unterrupt jupyter (ctrl C :) ), I've the following
msg :

..
[W 2016-07-27 09:28:47.685 JupyterHub auth:390] Failed to close PAM session
for 8: [PAM Error 10] User not known to the underlying authentication module
[W 2016-07-27 09:28:48.186 JupyterHub auth:390] Failed to close PAM session
for l: [PAM Error 10] User not known to the underlying authentication module
[W 2016-07-27 09:28:48.443 JupyterHub auth:390] Failed to close PAM session
for a: [PAM Error 10] User not known to the underlying authentication module
[W 2016-07-27 09:28:48.743 JupyterHub auth:390] Failed to close PAM session
for 9: [PAM Error 10] User not known to the underlying authentication module
[W 2016-07-27 09:28:48.789 JupyterHub auth:390] Failed to close PAM session
for 0: [PAM Error 10] User not known to the underlying authentication module
[W 2016-07-27 09:28:48.847 JupyterHub auth:390] Failed to close PAM session
for 1: [PAM Error 10] User not known to the underlying authentication module
[W 2016-07-27 09:28:48.863 JupyterHub auth:390] Failed to close PAM session
for 7: [PAM Error 10] User not known to the underlying authentication module
[I 2016-07-27 09:28:48.863 JupyterHub app:955] Cleaning up proxy[9618]...
[I 2016-07-27 09:28:48.864 JupyterHub app:981] ...done

2016-07-27 9:25 GMT+02:00 Xavier M. <xavier.mehaut@gmail.com>:

**Comment by minrk** [comment] 2016-07-27 15:05
PermissionError is often caused by JupyterHub being installed in an env where the individual users don't have access. You need to make sure that the `jupyterhub-singleuser` script that users execute is accessible and executable by all your users. It's common for people to install JupyterHub in an env they own, which is by default only readable by them. If you do this, you must make the env world-readable. You also need to make sure that the jupyterhub-singleuser script in particular is world-executable.

The simplest test for this is to do:

    sudo -u someuser /path/to/jupyterhub-singleuser -h

which should run for any of your users.

**Comment by willingc** [comment] 2016-08-29 18:58
Closing this issue. There is a [JupyterHub tutorial](https://github.com/jupyterhub/jupyterhub-tutorial) which helps guide new users with deploying JupyterHub. @xmehaut, please feel free to ask additional questions if needed.

**Closed by willingc** 2016-08-29 18:58 UTC
Labels: question
