### ISSUE TITLE
cull_idle_servers causes hub to go unresponsive in environments with 50,000 users

### ISSUE THREAD

**Issue by sdague** [jupyterhub/jupyterhub#2954] opened 2020-02-27 15:43 UTC
**Describe the bug**

After addressing #2928 , we discovered there is another issue when the hub starts in a kubernetes environment. 

The cull_idle_servers script does a GET /api/users, then iterates through the users to find servers. In our environment we typically have 100 to 300 servers, with 50,000+ users. The GET /api/users call takes minutes to return. That means that all other requests to the hub are blocked, because the asyncio handler for /users is blocking on the database. 

In a kubernetes environment this also means we miss 3 /api/health heartbeats, which means the service is marked not ready, and the ingress controller no longer has a route to the hub, and starts throwing 503 errors back to the user.

** Options **

It seems like there are a couple of approaches. 

1. Add pagination to the /api/users interfaces. This could work off of the progress in #2929 . 
2. Expose an /api/servers admin interface, because for culling servers we really only care about actual servers. Getting all the servers would be much faster than getting all Users.

**Compute Information**
 - Operating System
 - JupyterHub Version master bc7bb5076ff2deabc7702c75dce208166d14568e

**Comment by sdague** [comment] 2020-02-27 15:44
@minrk @cbjuan

**Comment by betatim** [comment] 2020-02-28 11:40
I like the idea of allowing the culler to be inverted the same way as the startup process (so expose a `/api/servers` end point). We could also transition slowly to it for existing culler scripts. The current culler scripts will keep working (for small number of users) and we can add a new culler that uses the new servers endpoint. This is nice because there are several copies/variations of the culler script floating around and people might have even forked it for their own use case.

Maybe another option to think about is if the `/api/users` endpoint could return a random subset of all users (when asked to do so). That way we'd have the culler only see (say) 300 users at a time, the call would be fast and we'd not have to change much in the culler script (maybe make it submit a new parameter in its request specifying that it wants a random subset).

**Comment by sdague** [comment] 2020-02-28 11:55
Yeah, I think my generally preference is to expose /api/servers as an admin API. I think it might be generally valuable long term as well. And that would provide an alternate cull script that uses that instead.

**Comment by mriedem** [comment] 2020-02-28 14:14
I'll start working on exposing a `GET /api/servers` admin API PR (first time contributor to this project so it might be a bit slow going to get setup).

**Comment by mriedem** [comment] 2020-02-28 14:29
Also, to be clear, my initial plan for this issue was once we have a `GET /api/servers` API available I plan on using that in `cull_idle` to just get the servers (not the users) if `cull_users=False` which is the default on that script (and how we use it in our deployment). From there it looks like some refactoring work to to bypass `handle_user` and use `handle_server` directly without a `user` argument being available (not sure if `user` should become a kwarg or not if `handle_server` should just handle `user == None`, guess it will depend on how messy the refactor gets). I guess the tricky thing is going to be this `DELETE` request to cull (delete) a server resource which is currently scoped to a user resource:

https://github.com/jupyterhub/jupyterhub/blob/7cf230ec1f2cc654403d4733849cbf81a9f008f3/examples/cull-idle/cull_idle_servers.py#L198

How do we want to handle that? Does the `server` resource in the API have a reference to `users` for that `server`? If not, do we also need a `DELETE /api/servers/{server_id}` API?

**Comment by sdague** [comment] 2020-02-28 14:32
Yes, we need a DELETE for servers as well. Probably LIST, GET, DELETE functions. 

I would also say in reference to @betatim 's suggestion, the existing cull_idle example is not changed, but a new script example is added that only uses the servers API, probably with comments that this will work better for high user account installations.

**Comment by mriedem** [comment] 2020-02-28 14:35
> Yes, we need a DELETE for servers as well. Probably LIST, GET, DELETE functions.

Ack.

> I would also say in reference to @betatim 's suggestion, the existing cull_idle example is not changed, but a new script example is added that only uses the servers API, probably with comments that this will work better for high user account installations.

Yeah, good point, that avoids risk in regressing the existing `cull_idle_servers.py` script and makes the new server-specific culler cleaner. I'm not sure what we'll call it since `cull_idle_servers` is already taken 😃 .

> This is nice because there are several copies/variations of the culler script floating around and people might have even forked it for their own use case.

Maybe this is something I should float on the mailing list to see if anyone already has a version of what we're trying to do in a forked repo and would like to collaborate on this?

**Comment by betatim** [comment] 2020-02-28 15:15
I think we can rewrite the internals of the `cull_idle_servers.py` script that is in JupyterHub (instead of adding a new script which would double the maintenance effort). I think the internals of the script are an "implementation detail". However we can't change the CLI, functionality and the outcome of setting those arguments.

A new `/api/servers` endpoint could deliver with it information about the user that owns the server so that the culler can then explicitly check those users and potentially cull them as well.

My point was that adding this new API endpoint means that all the existing copies/modified versions/forks/clones of `cull_idle_servers.py` will continue to work. Places that I think (potentially) have copies are the zero2jupyterhub chart, binderhub, the littlest jupyterhub, and an example in this repo. Not breaking those is important/saves us a lot of work.

It is probably worth starting a PR (marked a `[WIP] `) that sketches things out to get some feedback before spending a large amount of time building stuff.

**Comment by mriedem** [comment] 2020-02-28 15:49
> A new /api/servers endpoint could deliver with it information about the user that owns the server so that the culler can then explicitly check those users and potentially cull them as well.

OK. And looking at the data model users is 1:M with servers, but it also looks like servers can exist without user references?

https://github.com/jupyterhub/jupyterhub/blob/7cf230ec1f2cc654403d4733849cbf81a9f008f3/jupyterhub/objects.py#L24

Though maybe the only servers resources in the database are _user_ servers and I don't need to worry about ^ for the Server (non-ORM) object.

> It is probably worth starting a PR (marked a [WIP] ) that sketches things out to get some feedback before spending a large amount of time building stuff.

Will do, thanks for the direction. I'm currently trying to just get the dev environment setup to the point where I can get tests passing before I start coding.

**Comment by mriedem** [comment] 2020-03-02 18:40
How much do we want to return the `user` information for a given `server` resource (Spawner under the covers) from the `GET /servers` API? It looks like the `handle_server` function in the `cull_idle` flow only needs the user name for (1) logging and (2) building the path to delete the server, either using `DELETE /users/{user_name}/server/{server_name}` or `DELETE /users/{user_name}/server`, but if we have a dedicated `DELETE /servers/{server_id}` API then we don't need to go through the `users` resource API at all.

Note that it's not hard to return the `User.name` in the `GET /servers` response since I already have to get the User object to create the Spawner object which is used in the API `server_model` function to build the response so maybe it's fine to just include a `user_name` field? Or would you want a `user` object with just a `name` field for now (could be built on later in the API)?

Also note that the `GET /servers` API will need to include the actual `servers.id` value from the DB so that we can do a `DELETE /servers/{server_id}` API (`GET /users` does not include the server ID in it's `servers` field).

**Comment by mriedem** [comment] 2020-03-02 21:12
Pull #2962 is ready for review.

**Comment by mriedem** [comment] 2020-03-03 19:01
@betatim @minrk Reading up on how `cull_idle_servers` is invoked here [1] am I correct in saying that nothing within `jupyterhub` itself runs `cull_idle_servers` as a hub-managed service by default? And if not, the only way to run it would be via an external service, correct?

I'm trying to figure out just how `cull_idle_servers` is even running in our environment because I don't see it configured in our helm charts nor do I see anything related to it in the Dockerfile we're using (which is based on `jupyterhub/k8s-hub:0.9.0-beta.3`). The only thing I can think is that the `jupyterhub_config.py` that the Dockerfile is using:

```docker
CMD ["jupyterhub" "--config" "/etc/jupyterhub/jupyterhub_config.py"]
```

Has the `cull_idle_servers` config in it and I'm not sure where that config is coming from.

Are you aware of anything standard (helm charts, jupyterhub docker images, etc) outside of jupyterhub itself that automatically configures `cull_idle_servers` as a hub-managed service?

[1] https://jupyterhub.readthedocs.io/en/stable/getting-started/services-basics.html

**Comment by mriedem** [comment] 2020-03-03 21:27
> Are you aware of anything standard (helm charts, jupyterhub docker images, etc) outside of jupyterhub itself that automatically configures `cull_idle_servers` as a hub-managed service?

OK it looks like we're getting it from the zero-to-jupyerhub-k8s helm chart values:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/bc907f72d293236c792480b8b14a11c609cd8090/jupyterhub/values.yaml#L357

Sorry for the noise.

**Comment by minrk** [comment] 2020-03-06 21:06
I think there are going to be lots of issues with 50k users; as each one is addressed, we will find new ones. 50k is really outside the intended scope of a single Hub (deployments for this many users generally operate several hubs), but that doesn't mean we shouldn't address performance issues as we find them.

In general, I believe to support large numbers of users/servers/etc. we need to implement paging in the API, as we have in #2389 for a non-API page.

Similarly, adding a query param like `GET /users?active=true` would perhaps allow a much simpler solution to the problem than #2962, because it filters down to the same results.

**Comment by mriedem** [comment] 2020-03-09 18:14
> I think there are going to be lots of issues with 50k users; as each one is addressed, we will find new ones. 50k is really outside the intended scope of a single Hub (deployments for this many users generally operate several hubs), but that doesn't mean we shouldn't address performance issues as we find them.

Yeah agree.

> In general, I believe to support large numbers of users/servers/etc. we need to implement paging in the API, as we have in #2929 for a non-API page.

Agree, and more on this below.

> Similarly, adding a query param like `GET /users?active=true` would perhaps allow a much simpler solution to the problem than #2962, because it filters down to the same results.

I'm assuming by `active=true` you're thinking of how `GET /users` works in the `user_model` method to only show a user's servers that are active where active == pending or ready. In the case of the `cull_idle_servers.py` script it filters out servers that are pending and not ready so I'm not sure that is a granular enough filter. The other thing I'm not sure about is how much of those values in the API on the `Server` resource are directly filterable in the DB / ORM or if they can only reliably get their values from the `spawner.Spawner` object itself which has logic for things like `ready` and `pending` which are not maybe necessarily 1:1 with the ORM. My point being, if we want fast filtering it should be as close to the DB as possible otherwise we still could be iterating thousands of wrapper objects in the API.

----

Regarding pull #2962 I think we might as well abandon it. In our case we had ~50K `users` table records in our production hub DB but only about 300-400 notebook servers (records in the `spawners` table). We were running the `cull-idle` script as a hub-managed service because it's enabled by default from the helm chart in `jupyterhub/zero-to-jupyterhub-k8s` but that runs by default without `--cull-users` so we were culling servers but not users, which is how that table got so huge.

Over the weekend we ran `cull_idle_servers.py` with `--cull-users` externally and that got our `users` table back into a realistic range of a few hundred users. We are now running the hub with the hub-managed `cull-idle` service and with `--cull-users` enabled and we have (relatively) much better restart times of the hub (~18 seconds). So our immediate issue is worked around.

At this point I'm happy to take direction from the maintainers as to what should happen with this issue and pull #2962 - do you want to abandon that change and replace it with something else like paging for `GET /users` or some other kind of filtering on the users that are returned? Or just abandon it and close this issue as working as designed knowing that there could be optimizations to be made in the server-side filtering we could do so that `cull_idle_servers.py` could be a bit faster (doing less client-side filtering)?

**Comment by minrk** [comment] 2020-03-09 20:01
@mriedem thanks for the info! mybinder.org faced exactly that issue, and is why the `--cull-users` flag was introduced. Indeed, it should be used for ~all similar deployments using JupyterHub with "temporary" users that correspond to launches instead of humans. I think this is perhaps a documentation task, addressing "so you want to use JupyterHub, but don't really want its concept of 'users'..."

I'd be happiest with adding paging and/or filtering to the existing endpoints, because those will solve known scaling problems. Paging alone will help the responsiveness of the Hub when there are large numbers of users, but for a case like cull-idle, the culling task will still take a *super* long time without filtering since it still has to visit the same number of users, but this time over the course of several requests.

> I'm assuming by active=true you're thinking of how GET /users works in the user_model method to only show a user's servers that are active where active == pending or ready.

Not in the user_model method so much as implementing the appropriate query as a first-pass filter. I think we should implement whatever filtering would be useful. I expect the three states of "ready", "active" (ready or pending), and "inactive" would make sense. From what you mention, it sounds like cull-idle would use "ready" but even if only "active" were available, that would limit the number of results to "ready" plus the very small number (often zero) with pending transactions to be skipped. The performance problem would be solved, if not the removal of the filter step in the client.

**Comment by mriedem** [comment] 2020-03-10 18:04
> Not in the user_model method so much as implementing the appropriate query as a first-pass filter. I think we should implement whatever filtering would be useful. I expect the three states of "ready", "active" (ready or pending), and "inactive" would make sense.

Does it seem weird to filter user resources by the state of their servers? Or are users and servers (spawners) historically munged together a bit, at least in the default no-named-servers case? Thought I guess the `User` resource in the API model already has a `pending` field based on the user's default spawner's `pending` value [1][2].

> From what you mention, it sounds like cull-idle would use "ready" but even if only "active" were available, that would limit the number of results to "ready" plus the very small number (often zero) with pending transactions to be skipped.

Yeah doing `GET /users?ready=true` would filter out pending or inactive users based on their spawners status. What if the user has multiple spawners because the hub is configured to allow named servers? Then would a user be returned if at least one of it's spawners is ready? That's where the user resource filtering based on the status of one of it's sub-resources is kind of odd semantically but in the normal / default user:spawner 1:1 case it's probably not bad.

The performance problem with a lot of users and `cull-idle` isn't probably totally solved unless the `users` table record filtering on the server side could be done in the database but I'm not sure how possible that is because like I said earlier it looks like the `ready` flag is based on the `Spawner` implementation rather than the DB, and spawners are pluggable (correct?) so that means we can't filter in the DB and instead have to filter the ORM-wrapper objects in the API. Server side filtering would still be better than doing it in `cull_idle_servers.py` but we're still filtering in code rather than the DB where it would be fastest.

[1] https://jupyterhub.readthedocs.io/en/stable/_static/rest-api/index.html#/definitions/User
[2] https://github.com/jupyterhub/jupyterhub/blob/1.1.0/jupyterhub/apihandlers/base.py#L200

**Comment by meeseeksmachine** [comment] 2020-07-23 23:17
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/scheduler-insufficient-memory-waiting-errors-any-suggestions/5314/4

**Comment by meeseeksmachine** [comment] 2020-08-17 16:23
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/core-component-resilience-reliability/5433/2

**Comment by minrk** [comment] 2020-09-17 10:33
> Does it seem weird to filter user resources by the state of their servers? Or are users and servers (spawners) historically munged together a bit, at least in the default no-named-servers case?

It may seem weird since users and servers are technically separate resources, but I don't think it's weird in the context of JupyterHub for two reasons:

1. a User really only exists to run a Server, and
2. the *vast* majority of requests to `GET /api/users` are done for the purposes of collecting information about the users and their servers, which is where this filtering would be most useful.

> What if the user has multiple spawners because the hub is configured to allow named servers? Then would a user be returned if at least one of it's spawners is ready?

Yes, I would think you return a user if any of the associated last_activity timestamps matches the filter


> The performance problem with a lot of users and `cull-idle` isn't probably totally solved unless the `users` table record filtering on the server side could be done in the database but I'm not sure how possible that is because like I said earlier it looks like the `ready` flag is based on the `Spawner` implementation rather than the DB, and spawners are pluggable (correct?) so that means we can't filter in the DB and instead have to filter the ORM-wrapper objects in the API.

Almost. `ready` is not governed by the Spawner implementation, it's controlled by JupyterHub itself, but it is true that this does not live in the database. But we can still get 90% there there because Spawners in the database are distinguishable between *active* and *inactive*. We can't filter down to 'ready' from 'active' in the database, since that's only in memory, but the difference between those is very small (only those in a pending state), so should not be so expensive as a post-processing step once the query is limited. For instance, to check 'ready' for 10,000 'active' spawners takes 4ms on my laptop, which I think is within tolerances for what one Hub can reasonably handle

**Comment by manics** [comment] 2022-05-22 14:03
https://github.com/jupyterhub/jupyterhub/pull/3413 added pagination, and the culler is in its own repo https://github.com/jupyterhub/jupyterhub-idle-culler

**Closed by manics** 2022-05-22 14:03 UTC
