### ISSUE TITLE
jupyterhub linux subsystem on windows 10 - permission denied

### ISSUE THREAD

**Issue by denfromufa** [jupyterhub/jupyterhub#703] opened 2016-08-25 22:04 UTC
```
jupyterun@JUPYTER:/mnt/c/Windows/System32$ sudo jupyterhub
[I 2016-08-25 14:59:46.641 JupyterHub app:643] Writing cookie_secret to /mnt/c/Windows/System32/jupyterhub_cookie_secret
[E 2016-08-25 14:59:46.644 JupyterHub app:1296]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1293, in launch_instance_async
        yield self.initialize(argv)
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 1098, in initialize
        self.init_secrets()
      File "/usr/local/lib/python3.4/dist-packages/jupyterhub/app.py", line 645, in init_secrets
        with open(secret_file, 'w') as f:
    PermissionError: [Errno 13] Permission denied: '/mnt/c/Windows/System32/jupyterhub_cookie_secret'
```

**Comment by denfromufa** [comment] 2016-08-25 22:10
related? https://github.com/jupyterhub/jupyterhub/issues/178

**Comment by katsar0v** [comment] 2016-08-28 16:23
Try docker, I guess you won't use windows 10 on your production environment. Also System32 access requires admin I guess...

**Comment by DavidPowell** [comment] 2016-08-29 06:51
I have successfully run jupyterhub on Ubuntu for Windows.

The only difference was that I did not use sudo. Probably the cause of the problem is that it tries to write the cookie secret to the local directory, which in your case is a protected windows location.

Have you tried running from a location where you do have write permission?

**Comment by willingc** [comment] 2016-08-29 08:43
@DavidPowell Would you have any interest in writing up a quick doc (or a bullet list of steps) on how you were able to configure and run jupyterhub on Ubuntu for Windows? It would be a helpful addition to the wiki for others.

**Comment by denfromufa** [comment] 2016-08-29 12:55
@willingc I think this issue below needs to be re-opened, potentially there 3 ways to run jupyterhub on windows: win 10 linux subsystem, cygwin/mingw, and docker:

https://github.com/jupyterhub/jupyterhub/issues/7

**Comment by willingc** [comment] 2016-08-29 14:16
@denfromufa Thanks for the suggestion. I do believe that it would be best to leave the issue referenced closed. For both technical and sustainability reasons, there are currently no plans to support deployment of JupyterHub on a native Windows operating system.

The three ways that you mention are ways to run JupyterHub on Linux, though they can be accessed by a Windows system. If you wish to blog about them or submit a page for the wiki, that seems to be a good approach to foster knowledge about them. This approach is much like how the project has handled custom authenticators and custom spawners. Thanks! :sunny: 

cc/ @minrk @fperez

**Comment by DavidPowell** [comment] 2016-08-29 14:53
@willingc getting to the login screen was pretty trivial, but now that I check carefully, I see that the kernel **doesn't run properly and has trouble restarting**.

I don't recall exactly what I did, but it was something like this:
* `sudo aptitude update`
* `sudo aptitude upgrade`
* Download and install miniconda for Linux, 64 bit, python 3
* `conda install jupyter`
* `conda config --add channels conda-forge`
* `conda install jupyterhub`
* `jupyterhub --no-ssl` (just to check it quickly)
* open up a browser window at `localhost:8000`

I'm able to get through the jupyterhub login screen, and create a notebook, however the kernel never starts. It gives errors like the following, repeatedly:

`[I 2016-08-30 00:49:46.304 dap124 restarter:103] KernelRestarter: restarting kernel (1/5)
Invalid argument (src/tcp_address.cpp:172)`

Sorry I didn't check this more carefully before posting first.

**Comment by willingc** [comment] 2016-08-29 16:05
@DavidPowell Thanks for taking the time to write up your notes. No worries about the post; we're all hear to share tips and information ;-) A while back the networking support, especially sockets, in Ubuntu on Windows was still a WIP https://github.com/Microsoft/BashOnWindows/issues/134.

**Comment by willingc** [comment] 2016-08-29 16:10
Closing this issue as out of scope but tagging as reference re: Ubuntu on Windows.

cc/ @minrk

**Closed by willingc** 2016-08-29 16:10 UTC
Labels: out of project scope, reference

**Comment by fperez** [comment] 2016-08-29 17:47
Agreed @willingc, thanks! If in the long run, the new ubuntu support in Windows (which is stilly *highly* experimental) becomes a rock-solid, daily-usage tool that integrates really well with the rest of Windows, we can revisit the question of native Windows support for JupyterHub.  I can imagine that becoming an accepted route for lots of server tools on Windows.

But we're probably at least a year away from that being (potentially) viable, so I agree that for now this should be kept as blog/community docs for custom setups.

**Comment by minrk** [comment] 2016-08-30 08:18
The underlying issue appears to be that zeromq socket don't work yet in Ubuntu-on-Windows, but it's good to know that everything up to there is working. Thanks for digging in, @DavidPowell!

I believe this affects all Jupyter tools (and everything else) that talk zmq. It's possible that building zeromq yourself on the system, and then building pyzmq on that would result in something that works, but I'm not sure. I really don't know what magic is going on when it comes to sockets, but it doesn't surprise me too much that if something's going to go wrong that would be it.

**Comment by denfromufa** [comment] 2016-08-30 10:57
@minrk according to this comment from Microsoft team member, TCP/UDP sockets should work on WSL. So can pyzmq be configured to use only tcp for jupyter(hub)?

https://github.com/Microsoft/BashOnWindows/issues/69#issuecomment-208574945

also people have much luck getting just ipython/jupyter on WSL since July 2016 with a patched zmq:

https://github.com/Microsoft/BashOnWindows/issues/185#issuecomment-234756527

**Comment by minrk** [comment] 2016-08-30 11:18
@denfromufa Jupyter only uses pyzmq with tcp connections by default. It never uses UDP.
