### ISSUE TITLE
Authenticator config to toggle allowing users by default (when no other allow config is specified)

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#4484] opened 2023-06-15 06:57 UTC
If `Authenticator.allowed_users` isn't specified, and for example `GitHubOAuthenticator.allowed_organizations` isn't specified either, we have currently in OAuthenticator defaulted to allowing all users not part of `Authenticator.blocked_users`.

I think this behavior should change by default for at least some authenticators, and I wonder if we should introduce a flag in `Authenticator` that for the various OAuthenticator classes could make use of to toggle this with explicit config. I think explicit config tends to be more self-explanatory config, and I think self-explanatory config is the best kind of documentation for config.

### Idea for new Authenticator base class config

- **Naming and option**
  - Draft name proposal `Authenticator.allow_users_by_default`
  - Allowed values are None, False/True
- **Partial misconfiguration protection**
  We introduce a validation of the config value, making False/True only be something that works if the specific authenticator declared it supports it. This protects users from assuming this config works with an authenticator not supporting it, but it doesn't protect users of old versions of JupyterHub using an authenticator that doesn't support it.
- **Behavior modes**
  - None (default config value), the current behavior is retained
  - True, the current behavior is retained
  - False, users are required to configure explicitly what users are allowed because otherwise no users will have access

### Adoption in other Authenticators

If we go for this we it will be available in JupyterHub 4.x.y, but we can support it in authenticators like various OAuthenticator classes with JupyterHub versions older than JupyterHub 4.x.y.

### Action points

- Comment with feedback

**Comment by consideRatio** [comment] 2023-06-15 10:20
I agree, but even if its entirely authenticator dependent, it could be helpful to establish a common interface for it in the base class. This makes authenticators use the same name to configure this kind of change, which also makes other properties not overridden be able to document things correctly.

For example [`Authenticator.allowed_users` is documented](https://jupyterhub.readthedocs.io/en/stable/tutorial/getting-started/authenticators-users-basics.html#create-a-set-of-allowed-users-allowed-users) like below, which the OAuthenticator.allowed_users would need to update also unless Authenticator itself was aware of the config option.

![image](https://github.com/jupyterhub/jupyterhub/assets/3837114/a50a13a9-e642-4ef4-881f-0225443330fc)``

**Comment by minrk** [comment] 2023-06-15 10:45
That makes sense, and it also lets us communicate to authors of similar authenticators that it's something they should consider.

**Comment by consideRatio** [comment] 2023-06-15 11:18
@minrk okay, transitioning to thinking about the implementation!

**Naming**

I've only come up with the idea of `allow_users_by_default` so far.

- I appreciate that it starts with `allow` to sort next to `allowed_users` and `allowed_organizations` etc.
- I appreciate that it clarifies that its a default thing, and can be ignored by something being made explicit. In this case if for example `allowed_users` or `allowed_organizations` is specified, that would make this irrelevant. If we would named it `allow_all_authenticated_users`, and then not allow all authenticated users when `allowed_users` was specified, it would feel misleading as compared to if we had `_by_default` or similar in the name.

**Partial misconfiguration protection**

I think since it could be a false sense of trust to see config like `allow_users_by_default = False` if that config didn't work out, I think it would be good to try fail hard when its configured but not supported. Due to that, I think we should provide a default behavior that errors in JupyterHub 4.x+ with use with an authenticator that doesn't support configuring this.

I'm currently thinking that we do that by declaring a traitlet validator function that checks for something that the derivative class can set, which would make us confident its supported. To avoid introducing surplus things, maybe we should let the validator function check for if a function is available defining the default value for the traitle? Then we may fail to capture situations when the authenticator class opted to re-define the traitlet to set the default value though... So hmmm, maybe we can have code inspecting the specific class used and see if that specific class defines either the traitlet or the default value? Hmmm... but then we fail in situations when class B implements it and we inspect class C...

So, maybe we just search for a specific class variable called `_implements_allow_users_by_default` or similarly?

**Comment by minrk** [comment] 2023-06-15 11:49
>  think we should provide a default behavior that errors in JupyterHub 4.x+ with use with an authenticator that doesn't support configuring this.

I suspect that's going to be _very_ complicated and brittle to get right. I'm not sure it's worth taking that path, since it's only relevant for the subset of subclasses that _also_ fully override `check_allowed`, and only affects deployments _that nobody can use_ because no users are allowed.

Cases where the new config is not handled:

- True (current default behavior), if not handled, behavior will be correct, as intended. Or, if the authenticator chose its own opt-in for allow all, no user will be allowed and other config will be required. No real problem.
- False (proposed change, possible default in e.g. oauthenticator)
  - some users allowed, config has no effect
  - no users allowed, users permitted who shouldn't be
 
It's only the last case where a user is permitted who shouldn't be, and that config is only for a hub that literally nobody is allowed to use, which doesn't make a lot of sense so I'm not sure we should add complex logic to warn about it.


Re: naming, another option would be to add a three-state `allow_all_users`, with values:

- True - explicitly allow all (takes precedence over all other allow config, any successful authentication is allowed)
- False - other explicit allow config is required
- 'if-none-allowed' - this is your True behavior and the current default, where it's behaves as True _if_ no other allow config is specified.

I particularly like the very clear:

```
c.Authenticator.allow_all = True
```

vs

```
c.Authenticator.allow_all_users_by_default = True
```

which may not have any effect, depending on other config. When set in user config, it's only really going to make sense to use True or False, whereas _classes_ or _distros_ may use the `if-none-allowed` as a default. The `if-none-allowed` should always resolve to True or False via validation anyway. There's no reason I can see that the 'if-none-allowed' case would appear in _user_-specified config.

I might have a slight preference for this because it's explicit and _independent_ of other config options, and only interacts with config options when a value is given as an explicit value that says so. WDYT?

**Comment by consideRatio** [comment] 2023-06-15 13:32
`allow_all` sounds perfect, I have a few question on implementation details:

> The `if-none-allowed` should always resolve to True or False via validation anyway.

Do you mean traitlets validation, or always providing a True or False like behavior in the end?

I'm a bit worried that if we opt to resolve a "if-none-allowed" string to True / False, we will loose that intent if conditions change by subsequent config, REST API calls, or similar. I also figure that the Authenticator class can't know everything to validate/observe based on, such as `GitHubOAuthenticator.allowed_organizations` and that could be a restriction.

Not confident about the technical details, I'm inclined about preserving the three state values instead of resolving the third state only to store two states. And practically I'm considering a Union of Bool and Unicode, a Bool traitlet with allow_none, or an UseEnum traitlet.

What do you think should be done?

**Comment by minrk** [comment] 2023-06-15 14:14
> Do you mean traitlets validation, or always providing a True or False like behavior in the end?

I do mean traitlets validation. The only values that make sense are True and False, while 'if-none-allowed' means taking other configuration into account before resolving to True or False.

> I also figure that the Authenticator class can't know everything to validate/observe based on, such as GitHubOAuthenticator.allowed_organizations and that could be a restriction.

Yes, I'd propose that it's the responsibility of subclasses to implement that validator. Alternately, we could define a _public_ method that's called in the base validator that is the responsibility of the subclasses to implement, so they don't need to deal with traitlets syntax. It's the same logic that the same classes are responsible for in all cases, it's mostly a matter of where/when they are called or specified.

> What do you think should be done?

I'd use Enum with `True, False, 'if-none-allowed'`. Something like:

```python
# const for import
ALLOW_ALL_IF_NONE_ALLOWED = "if-none-allowed"


class Authenticator(Configurable):
    allow_all = Enum(
        values=[True, False, ALLOW_ALL_IF_NONE_ALLOWED],
        default_value=ALLOW_ALL_IF_NONE_ALLOWED,
        help="...",
        config=True,
    )

    @default("allow_all")
    def _default_allow_all(self):
        # default is 'if-none-allowed'
        return self.get_allow_all_if_none_allowed()

    @validate("allow_all")
    def _validate_allow_all(self, proposal):
        if proposal.value == ALLOW_ALL_IF_NONE_ALLOWED:
            return self.get_allow_all_if_none_allowed()

    def get_allow_all_if_none_allowed(self) -> bool:
        """
        Implement the meaning of allow_all = 'if-none-allowed'

        Should always return True or False.
        Override in Authenticator subclasses if there are more ways to specify
        that some users are allowed, other than .allowed_users (e.g. groups and other sources of 'allow').
        Should return True if the user has not specified any particular users or groups of users should be allowed,
        False otherwise.
        """
        return len(self.allowed_users) == 0

```

**Comment by minrk** [comment] 2023-06-15 14:21
If we didn't do it in validation, we'd still need the `get_allow_all_if_none_allowed()` logic, it would just have to go directly in `check_allowed`.

**Closed** 2024-04-15 08:57 UTC
Labels: new
