### ISSUE TITLE
Recover from 504 bad gateway with busy singleuser server

### ISSUE THREAD

**Issue by clkao** [jupyterhub/jupyterhub#1785] opened 2018-04-09 15:25 UTC
**How to reproduce the issue**

Make the single user server very busy so it stops to respond to port 8888. for example moving lots of files over nfs.

**What you expected to happen**

User can still access the singleuser server, or be prompted about server stopped responding and options to manually restart it.

**What actually happens**

Proxy ended up with 504 bad gateway.

**Share what version of JupyterHub you are using**

0.9-dev & kubespawner

**Comment by minrk** [comment] 2018-04-12 12:01
I'm not sure what we can do about this. If a server becomes unresponsive, a proxy should give an error if the upstream service can't be reached. We should already be recovering from this, in that when a server becomes responsive it will show up again. Though CHP gives 503 when things like this happens, I think, and the error page is served by the Hub. Are you running additional layers, such as nginx? What does the error page look like? If it's jupyterhub as configured by default and the error is raised by CHP, the page should look like a jupyterhub page with an error message. If the error occurs at a level higher than CHP, there's nothing to be done, I think.

**Comment by clkao** [comment] 2018-04-12 13:10
This is just regular z2jh deployment.  the error is 504 from the proxy pod's nginx container.  I think the chp has not found the server irresponsive yet, hence no 503 raised from hub in this case.

**Comment by minrk** [comment] 2018-04-13 08:08
Ah, ok. So the problem is that nginx is giving up before CHP gets a chance to handle the error. Maybe it's an nginx configuration issue in z2jh, then?

CHP is configured to serve error pages from JupyterHub (if available), which lets us give informative errors (and links to "try restarting from the Hub"). Maybe nginx could be configured to do the same? Or at least be loaded with its own versions of these pages.

This 504 error, though, is a little different from CHP's 503, which happens when it can't connect at all (I don't know what happens with a hung connection, it might just wait forever until the client, in this case nginx, drops the connection). Since with a 504, if it's a case as you said of the notebook server being busy in a blocking operation, waiting might be better than killing the process.

Another potential fix for this *particular* situation is to make the notebook's FileContentsManager async, so that it can avoid blocking the server when doing expensive operations. This can be done by putting large file operations in a background thread.

**Comment by clkao** [comment] 2018-04-16 04:15
Ok created a separate issue for async FileContentsManager in jupyter/notebook.

Is it possible to add a rather short timeout that would delete (or mark temporarily unavailable) the chp route. Then let jupyterhub inform the user it is being slow for x seconds already, and offer an option to stop it in addition to wait indefinitely.

To reproduce this, try `kill -STOP 7` (the ususal pid for the notebook process).

**Comment by yee379** [comment] 2018-04-24 05:43
i think i see something similar. i am also on 0.9-dev with kubespawner. [troubleshoot output](https://pastebin.com/raw/grgVQ73i).

**Comment by clkao** [comment] 2018-11-08 14:06
We've seen another user notebook server 504 case, but this probably belongs to the notebook code:

- the user ran to_pickle for a large dataframe in a notebook, resulting in the python kernel process stuck in D state. strace showed the write syscalls are 3G in size.
- somehow the notebook server process, not the kernel, was also in D state. we didn't manage to get strace output for this.

The user notebook becomes responsive again once the write completes.

**Comment by minrk** [comment] 2018-11-09 09:18
That's very strange! I haven't seen kernel activity making a notebook server unresponsive before. Maybe it was running into pooled resource limits

**Comment by manics** [comment] 2021-02-17 19:55
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!

**Closed by manics** 2021-02-17 19:55 UTC
Labels: bug
