### ISSUE TITLE
ERROR:tornado.general:Uncaught exception in ZMQStream callback

### ISSUE THREAD

**Issue by mdivk** [jupyterhub/jupyterhub#2380] opened 2019-01-15 23:19 UTC
Hello,

We already implemented JupyterHub in our production environment, it was working prior to the holiday started (just before Christmas 2018), yesterday was the first time I found it is NOT working now. 
I don't believe there were changes made to a production environment as that would requires going through admin team and need root privilege.

1. There are 4 kernels: spark 1.6 and 2.3 kernel with Anaconda python 2.7, Scala, SparklyR
Scala and SparklyR are still working as usual, the other two are not working, it is seen from the log the following error message:

> ERROR:tornado.general:Uncaught exception in ZMQStream callback

2. We tried to install a new kernel with the following steps, the new kernel is NOT showing up:
Create a customized environment file:

> cat 20190115.yml
> name: 20190115
> dependencies:
>   - numpy
>   - pandas

Create an environment based on the newly created environment file
`conda env create -f 20190115.yml`

Activate the new environment
`source activate 20190115`

Create kernel based on the conda env
` (20190115) [xxxx@cedgeprod03 bin]$ sudo ./python -m ipykernel install --name 20190115--display-name "spark 1.6"`

The kernel is seen in the `jupyter kernelspec list`

The new kernel's env is updated to match the production environment and it is the same as the previous one:

```
cat /usr/local/share/jupyter/kernels/spark-1.6/kernel.json
{
 "display_name": "spark1.6_conda_python2",
 "language": "python",
 "argv": [
  "/opt/cloudera/parcels/Anaconda/bin/python",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ],
 "env": {
  "HADOOP_CONF_DIR":"{{ hadoop_conf_dir }}",
  "PYSPARK_PYTHON":"/opt/cloudera/parcels/Anaconda/bin/python",
  "SPARK_HOME": "/opt/cloudera/parcels/CDH/lib/spark",
  "WRAPPED_SPARK_HOME": "/opt/cloudera/parcels/CDH/lib/spark",
  "PYTHONPATH": "{{ app_packages_home }}/lib/python2.7/site-packages:{{ jupyter_extension_venv }}/lib/python2.7/site-packages:/opt/cloudera/parcels/CDH/lib/spark/python:/opt/cloudera/parcels/CDH/lib/spark/python/lib/py4j-0.9-src.zip",
  "PYTHONSTARTUP": "/opt/cloudera/parcels/CDH/lib/spark/python/pyspark/shell.py",
  "PYSPARK_SUBMIT_ARGS": "--master yarn-client --jars /opt/cloudera/parcels/CDH/lib/spark/lib/spark-examples.jar pyspark-shell",
  "JAVA_HOME": "/usr/java/latest"
 }

}

```

Restart JupyterHub, open browser, log into the JupyterHub,  **the new kernel is not there.** what am I missing here?

Tonardo is 4.3 here, but there is another toanado in the same host from another advently installed anaconda3 which is version 5.1, here is the screenshot:
[https://snag.gy/2LIn0B.jpg](https://snag.gy/2LIn0B.jpg)

As this is a showstopper issue in Production, it would be greatly appreciated if anyone can help to sort it out. Thank you very much in advance.

**Comment by minrk** [comment] 2019-01-16 09:35
To be clear, "the new kernel is not here" means it's not in the New notebook or change kernel dropdown lists? If you start a terminal, do you see it in `jupyter kernelspec list`? What is the output of `jupyter kernelspec list`? Make sure you run `jupyter kernelspec list` in the env that the notebook *server* runs in (this will not be Python 2).

Do you perhaps have `KernelSpecManager.whitelist` configuration set or a custom kernel_spec_manager_class configured?

**Comment by minrk** [comment] 2019-01-16 09:39
For the error, can you include the log context? The fact that there was an error of some kind isn't enough to see what happened.

**Comment by mdivk** [comment] 2019-01-16 12:11
Thank you very much @minrk 

"the new kernel is not there" means it's not in the New notebook or change kernel dropdown list.

But I see it in the jupyter kernel list.

> Available kernels:
>   python3               /usr/local/lib/python3.6/site-packages/ipykernel/resources
>   apache_toree_scala    /usr/local/share/jupyter/kernels/apache_toree_scala
>   ir                    /usr/local/share/jupyter/kernels/ir
>   spark-1.6             /usr/local/share/jupyter/kernels/spark-1.6
>   spark16-conda         /usr/local/share/jupyter/kernels/spark16-conda
>   spark23-conda         /usr/local/share/jupyter/kernels/spark23-conda

spark1.6 is the new kernel just created:
```
$ cat /usr/local/share/jupyter/kernels/spark-1.6/kernel.json
{
 "display_name": "spark1.6_conda_python2",
 "language": "python",
 "argv": [
  "/opt/cloudera/parcels/Anaconda/bin/python",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ],
 "env": {
  "HADOOP_CONF_DIR":"{{ hadoop_conf_dir }}",
  "PYSPARK_PYTHON":"/opt/cloudera/parcels/Anaconda/bin/python",
  "SPARK_HOME": "/opt/cloudera/parcels/CDH/lib/spark",
  "WRAPPED_SPARK_HOME": "/opt/cloudera/parcels/CDH/lib/spark",
  "PYTHONPATH": "{{ app_packages_home }}/lib/python2.7/site-packages:{{ jupyter_extension_venv }}/lib/python2.7/site-packages:/opt/cloudera/parcels/CDH/lib/spark/python:/opt/cloudera/parcels/CDH/lib/spark/python/lib/py4j-0.9-src.zip",
  "PYTHONSTARTUP": "/opt/cloudera/parcels/CDH/lib/spark/python/pyspark/shell.py",
  "PYSPARK_SUBMIT_ARGS": "--master yarn-client --jars /opt/cloudera/parcels/CDH/lib/spark/lib/spark-examples.jar pyspark-shell",
  "JAVA_HOME": "/usr/java/latest"
 }

}
```

We do not have a kernel_spec_manager_class configured.

log is here:

> Jan 15 13:34:56 nydc-pcdhedg02 jupyterhub[2426]: ERROR:tornado.general:Uncaught exception in ZMQStream callback
> 
> Jan 15 14:05:14 nydc-pcdhedg02 jupyterhub[155389]: 14:05:14.311 [ConfigProxy] error: 404 GET /user/rxie/api/kernels/20602563-85e6-47d4-bd28-d8bd66ef09cf/channels?session_id=2bbe977f4c394656893d01143239efb4
> Jan 15 14:05:14 nydc-pcdhedg02 jupyterhub[155389]: [I 2019-01-15 14:05:14.318 JupyterHub log:158] 200 GET /hub/error/404?url=%2Fuser%2Frxie%2Fapi%2Fkernels%2F20602563-85e6-47d4-bd28-d8bd66ef09cf%2Fchannels%3Fsession_id%3D2bbe977f4c394656893d01143239efb4 (@127.0.0.1) 1.99ms
> Jan 15 14:05:14 nydc-pcdhedg02 jupyterhub[155389]: 14:05:14.335 [ConfigProxy] error: 404 GET /user/rxie/api/kernels/685f8315-35d2-41f9-9b7c-656db618a474/channels?session_id=2e91602ba71d4c6b9bd801e4e9d2aa19
> Jan 15 14:05:14 nydc-pcdhedg02 jupyterhub[155389]: [I 2019-01-15 14:05:14.339 JupyterHub log:158] 200 GET /hub/error/404?url=%2Fuser%2Frxie%2Fapi%2Fkernels%2F685f8315-35d2-41f9-9b7c-656db618a474%2Fchannels%3Fsession_id%3D2e91602ba71d4c6b9bd801e4e9d2aa19 (@127.0.0.1) 1.94ms
> 
> Jan 15 14:07:21 nydc-pcdhedg02 python36[155389]: pam_loginuid(login:session): set_loginuid failed
> Jan 15 14:07:21 nydc-pcdhedg02 python36[155389]: pam_selinux(login:session): Error sending audit message.
> Jan 15 14:07:21 nydc-pcdhedg02 python36[155389]: pam_keyinit(login:session): Unable to change GID to 1377000513 temporarily
> Jan 15 14:07:21 nydc-pcdhedg02 python36[155389]: pam_keyinit(login:session): Unable to change GID to 1377000513 temporarily
> Jan 15 14:07:21 nydc-pcdhedg02 python36[155389]: pam_systemd(login:session): Failed to create session: Access denied
> Jan 15 14:07:21 nydc-pcdhedg02 python36[155389]: pam_unix(login:session): session opened for user twickram by (uid=968)
> Jan 15 14:07:22 nydc-pcdhedg02 python36[155389]: pam_lastlog(login:session): unable to open /var/log/btmp: Permission denied
> 
> 3:18 PM
> 
> 
> 
> Jan 15 15:17:01 nydc-pcdhedg02 jupyterhub[169091]: WARNING: User-defined SPARK_HOME (/opt/cloudera/parcels/SPARK2-2.2.0.cloudera1-1.cdh5.12.0.p0.142354/lib/spark2) overrides detected (/opt/cloudera/parcels/SPARK2/lib/spark2).
> Jan 15 15:17:01 nydc-pcdhedg02 jupyterhub[169091]: WARNING: Running spark-class from user-defined location.
> Jan 15 15:17:01 nydc-pcdhedg02 jupyterhub[169091]: Setting default log level to "WARN".

**Comment by minrk** [comment] 2019-01-16 12:35
Can you include the logs from the single-user server, including the request to list kernels?

**Comment by mdivk** [comment] 2019-01-16 15:42
Thank you so much.

The log has been sent to your email directly, kindly check there.

**Comment by minrk** [comment] 2019-01-17 09:52
The logs show the reason the kernelspec isn't showing up:

```
... jupyterhub[23521]: json.decoder.JSONDecodeError: Expecting ',' delimiter: line 20 column 1 (char 889)
```

It's kernel.json is not valid json. Fix the syntax error in the kernel.json and it should show up. Looks like perhaps a missing trailing comma on a dict or list.

The other error:

```
Jan 16 13:21:10 nydc-pcdhedg02 jupyterhub[23521]: self.saved_sigint_handler = signal(SIGINT, default_int_handler)
Jan 16 13:21:10 nydc-pcdhedg02 jupyterhub[23521]: ValueError: signal only works in main thread
```

is strange. it suggests that the IPython is not being run in the main thread. However, IPython *must* be run in the main thread. This may have something to do with the pyspark startup in $PYTHONSTARTUP. You might try removing the $PYTHONSTARTUP env to see if that's the issue. If it's not, try removing environment variables one by one to see if any of them are the cause.

Also it's helpful to include a full environment list to the kernel env:

    conda list -p /path/to/env

in case it's related to a possibly outdated package.

**Comment by manics** [comment] 2021-02-17 21:21
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!

**Closed by manics** 2021-02-17 21:21 UTC
Labels: support
