### ISSUE TITLE
Configuring Groups

### ISSUE THREAD

**Issue by pgierz** [jupyterhub/jupyterhub#4711] opened 2024-02-19 14:38 UTC
Hello together,

I have a (hopefully not too complicated) use-case which might be transformed into an example deployment, once I figure out how to actually do it.

Assume you have configured a kernel, and additionally want to offer a web-proxy-service that is available to launch if (and only if) the specified kernel is allowed to be used. I would like to be able to configure the following:

An admin prepares a globally available kernel with a bunch of packages. This kernel is called Class1234_Semester02.

An instructor, Professor X, username profx, can add and remove individual users from a group. From my understanding, this fits into the roles, and a set of users instructors can be allowed to use that role, ergo this is a scope (I think).

A student, Maxime Mustermann, username mmuster and wants to belong to a group PythonForMorons101. She registers for the class, the instructor gets an email, and clicks a few buttons to add the user to that group

When the Spawner launches, which happens after the authentication is complete, it notices that mmuster is in the group PythonForMorons101. When launching the actual jupyterlab session, it then adds an argument to it’s cmd which is likely something like jupyter lab --<some cool argument>

This jupyterlab sesssion, which is now aware of the groups of the logged in user, also offers separate web services. If the user is not in the correct group, the launcher button which creates a new tab with the web application (not a notebook), is not shown.

So, from that scenario, two questions: How do I go about implementing this? I am getting rather stuck about how all the pieces fit together. And: Once I’ve figured this out, would this be an example others are interested in, and where would I document that for the community to find?

Cheers,
@pgierz

**Comment by manics** [comment] 2024-02-19 14:57
This is a duplicate of https://discourse.jupyter.org/t/scopes-roles-groups-users-examples-needed/24015

**Closed by manics** 2024-02-19 14:57 UTC
Labels: bug

**Comment by pgierz** [comment] 2024-02-19 15:11
Yes, it is, however I would like to ask this question to as many potential community members as possible in case someone sees it here and not on the discourse forum.
