### ISSUE TITLE
helm charts and k8s images not up-to-date?

### ISSUE THREAD

**Issue by adriendelsalle** [jupyterhub/jupyterhub#3012] opened 2020-04-06 16:22 UTC
Thanks a lot for JupyterHub, you're doing a great job!
It's maybe more a question rather than a bug.

### Description
I'm expecting to get the latest version of JupyterHub using k8s and it seems that the latest stable version available is 0.8.2. I followed the zero-to-kubernetes tutorial using helm chart available [here](https://jupyterhub.github.io/helm-chart/).

#### Helm charts
Development releases are up to 0.9.0-beta.4, consistent with images hosted on dockerhub such as [k8s-hub](jupyterhub/k8s-hub:0.9.0-beta.4) but **not** up-to-date.

#### Dockerhub
In the same time, the jupyterhub/jupyterhub 1.2 tag is available.

I can't figure out how it's possible since there is no tag on github and no trace of the build in the `build` tab of the [dockerhub page](https://hub.docker.com/r/jupyterhub/jupyterhub/builds).

#### Conda/Pypi
pypi and conda repo seem consistent with github latest tag/release = v1.1.0

### Expected
Consistency between all the artefacts.

---
Thank you for your advice!

**Comment by consideRatio** [comment] 2020-04-06 16:37
This is probably a duplicate of #2848 - I have not yet investigated this.

**Closed** 2020-04-06 16:49 UTC

**Comment by adriendelsalle** [comment] 2020-04-06 16:54
Hi @consideRatio ! Thanks for this incredibly fast response !

Sure I'm using the k8s images to try this kind of deployment.
I'm closing the issue since it's maybe not the right place: I will search on the  jupyterhub/zero-to-jupyterhub-k8s repo.

And thanks in advance for the jupyterhub/jupyterhub dockerhub issue!

**Comment by consideRatio** [comment] 2020-04-06 16:59
@adriendelsalle your welcome!

The z2jh images are rebuilt if the code that would influence the Dockerfile has changed, or if a tagged release has been made. So a statement like `pip install mypackage` within them may have an outdated version.

**Comment by adriendelsalle** [comment] 2020-04-20 07:26
Hi @consideRatio 

I think I understood my mistake: I expected the same version number between the helm-chart and JHub itself.

Could you confirm they are managed separately?
In that case, why the 0.9.0 helm-charts deploys a 1.1.0 JHub and you don't follow the JHub version tags?
I also quite don't understand why the Z2JH project is used to manage k8s recipes instead of this (jupyterhub/jupyterhub) repo? Helm charts and associated containers are they not usual artefacts (as pypi or conda packages, or docker image) ?

Z2JH sounds much more like a tutorial repo where we expect documentation and it's very confusing!

**Comment by betatim** [comment] 2020-04-20 07:35
Helm chart versions and the version of the software they package are almost always completely "out of sync". The version tag of the chart tells you which version of the chart you are using, not the version of the software in it.

For a while the Z2JH chart version was very close to the JupyterHub version. This caused a lot of confusion. Now they are drifting apart which will hopefully reduce the chances of people assuming they should be in sync.

The chart lives in a separate repository because not every JupyterHub is deployed on Kubernetes. There are many ways to operate a JupyterHub and using kubernetes is just one of them.

**Comment by adriendelsalle** [comment] 2020-04-20 08:11
Thanks @betatim for your explanations !
I expected that *all* versions of JHub available on k8s, so the question about a different handling of these artefacts.
Since the helm charts and JHub versions are not synced, how we are supposed to know what version of JHub is used? Maybe I missed the info somewhere.

If not, I will ask for the more explicit display of the Jhub version on the Z2JH issue tracker, on the main readme file but also at https://jupyterhub.github.io/helm-chart/

**Comment by manics** [comment] 2020-04-20 08:46
`Charts.yaml` includes an `appVersion` field: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/51b4cf87d48f09b27601355279aad336e2aad92f/jupyterhub/Chart.yaml#L4
This is part of the Helm specification: https://helm.sh/docs/topics/charts/#the-appversion-field

**Comment by adriendelsalle** [comment] 2020-04-20 08:57
Thank you @manics .
I found the relevant info at https://github.com/jupyterhub/helm-chart (not up-to-date with the 0.9.0 JHub helm chart).
I missed the note in the tutorial (https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub/setup-jupyterhub.html) mentioning it.
