### ISSUE TITLE
Option to allow implicit server spawn

### ISSUE THREAD

**Issue by charnpreetsingh** [jupyterhub/jupyterhub#2924] opened 2020-02-07 19:06 UTC
JupyterHub version 1.0.0 introduced a change to no longer implicitly spawn a user user if it's not running. A number of users find the "Server not Running" page confusing, especially coming from a non-technical audience or from past JupyterHub versions where servers launched in the background. It would be nice to add an option to the JupyterHub config to disable/enable implicit spawning of servers.

**Comment by stevegore** [comment] 2020-02-20 05:56
I'd like to echo that this is a really jarring experience for users. I've had numerous requests to get rid of what is perceived as a completely superfluous extra step.

(I'd also raised an issue [here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1579) but realise now this is probably a JupyterHub issue.)

**Comment by minrk** [comment] 2020-02-20 11:33
I'm mixed on whether we should allow this as an option, versus attempting to improve the interstitial page, since this behavior is known to cause lots of very hard to resolve issues (hence the change). It is, however, an easy option to add, so we could punt and make it an option, but that means not improving the default experience for most users and reintroducing known problems for those who opt in to the old behavior.

One option for improving the existing page would be to allow the launch to happen automatically via *javascript* redirect. The advantage of a javascript redirect is that it requires a browser to actually visit the page, which should mitigate the launch triggered by 302-style redirect which is triggered even for e.g. API requests. That was one of the many problems caused by the implicit spawn, which shouldn't be an issue if it's triggered by javascript instead of a Location redirect.

From the other issue:

> However, we have users accessing direct links to notebooks. When they do so, no instance is spawned, and they are presented with the question:

"direct links to notebooks" is ambiguous. Whose notebook server was the link to? Was it user A sharing to user B a link to `/user/a/my/notebook` or `/user/b/my/notebook`? If it was `/user/a/my/notebook` (common, and the result of user A sharing a link from their URL bar), then the answer for what to do is ambiguous: sharing this URL *should* mean offering access to user B to user A's server (that's what the URL means). The "right" way to share a link to a notebook is to share `/hub/user-redirect/path/to/notebook` which does not have this issue at all. There is an issue about making the jupyterlab "get shareable link" behavior create these links properly, but I don't think it's happened yet.

**Comment by minrk** [comment] 2020-02-20 11:52
I've opened #2941 which implements the javascript redirect, which means that the user interaction step is indeed eliminated (basically the button is clicked automatically), but no other changes, which should leave in-tact most of the issues solved by the removal of the Location-based redirect.

**Comment by stevegore** [comment] 2020-02-20 23:14
Many thanks @minrk - we were automatically generating links with `/user/b/my/notebook` in them. Changing to use `/hub/user-redirect` seems to fix the problem - which is awesome. It would be great if this feature were more easily discoverable.

For other applications, the javascript-base redirect idea sounds great.

**Comment by inverts** [comment] 2020-02-21 01:28
Thank you! We also were unaware of the `user-redirect` path (I do blame myself to some extent for not looking hard enough) and were automatically modifying links to shared resources. We built our own nbextension (non-jupyterlab) for link sharing that modified the address bar URL accordingly as well 😄. We have a lot of non-technical (and often first-time) users viewing and sharing content that technical users create, so these seemingly minor bumps turn into larger roadblocks that we have to find ways to smooth out unfortunately. 
Using the `user-redirect` path addresses most of our use cases, but I can certainly see the js redirect as useful to make things simpler for users.

**Comment by minrk** [comment] 2020-02-21 09:45
> It would be great if this feature were more easily discoverable.

I know! It has been surprisingly hard to find a good place where people discover this. Maybe a general FAQ page in the docs is in order.

**Comment by betatim** [comment] 2020-02-22 06:28
Should we close this now that the "implicit spawn by auto redirect" has been merged and FAQ item added?

**Comment by minrk** [comment] 2020-02-22 15:05
Yeah, I think so. Thanks!

**Closed by minrk** 2020-02-22 15:05 UTC
