### ISSUE TITLE
400: Bad Request - OAuth state missing from cookies

### ISSUE THREAD

**Issue by cmseal** [jupyterhub/jupyterhub#2044] opened 2018-07-17 08:28 UTC
**Describe the bug**
When using Oauth2 (Google), after successful logging out, logging in again causes "400 : Bad Request
OAuth state missing from cookies"

**To Reproduce**
* JupyterHub 0.9.1 on Centos 7
* DockerSpawner
* Oauth2 configured for Google, with specific domain
* Login successfully, Logout, then Login again

**Expected behavior**
Should be able to login again without issue.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser: tried with Safari 11.1.1 and Chrome 67

**Additional context**
Jul 17 08:19:58 hub.domain.com jupyterhub[3042]: [I 2018-07-17 08:19:58.697 JupyterHub log:158] 200 GET /hub/api/authorizations/token/[secret] (chris.seal@172.17.0.6) 308.25ms
Jul 17 08:20:00 hub.domain.com jupyterhub[3042]: [I 2018-07-17 08:20:00.497 JupyterHub login:19] User logged out: chris.seal
Jul 17 08:20:00 hub.domain.com jupyterhub[3042]: [I 2018-07-17 08:20:00.782 JupyterHub log:158] 302 GET /hub/logout -> /hub/login (chris.seal@::ffff:127.0.0.1) 447.40ms
Jul 17 08:20:00 hub.domain.com jupyterhub[3042]: [I 2018-07-17 08:20:00.811 JupyterHub log:158] 200 GET /hub/login (@::ffff:127.0.0.1) 2.52ms
Jul 17 08:20:05 hub.domain.com jupyterhub[3042]: [W 2018-07-17 08:20:05.466 JupyterHub web:1667] 400 GET /hub/oauth_callback?state=eyJzdGF0ZV9pZCI6ICJhMWU1NDI1NDJiZGQ0MWQ1YmViYTFmOTllNTA1MDk2NSIsICJuZXh0X3VybCI6ICIifQ%3D%3D&code=4/AABGZ7VcfIz8MsbISZYXEhUSGsXld37l_2i-YGF-1XsLDPGzcB0hDnABR3z7B10RNaJEBKQAauGX2DzTuX_T-OQ&authuser=0&hd=domain.com&session_state=0f4e3873d22d44f40494c9271f8118b59e3dc7fb..fb74&prompt=none (::ffff:127.0.0.1): OAuth state missing from cookies

**Comment by betatim** [comment] 2018-07-18 20:23
Does https://github.com/jupyterhub/jupyterhub/issues/1519#issuecomment-342806150 help fix your problem? Specifically are the domain name the same when you are being redirected to google and when you return? One of them HTTP the other HTTPS?

**Comment by regina-priyanka** [comment] 2018-08-21 12:34
Describe the bug
When using Oauth2 (Google), after successful logging out, logging in again causes "400 : Bad Request
OAuth state missing from cookies"

To Reproduce

JupyterHub 0.9.2 on RedHat Linux 7
DockerSpawner
Oauth2 configured for Google, with specific domain
Login successfully, Logout, then Login again

Expected behavior
Should be able to login again without issue.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: Windows 10
Browser: Chrome

Additional Context
[W 2018-08-21 12:04:04.001 JupyterHub web:1667] 400 GET /hub/oauth_callback?state=eyJzdGF0ZV9pZCI6ICI5ZGNlZmM5NDQ2NjI0NTVkODFkYjQ0MmU0ODc1ZDQyMCIsICJuZXh0X3VybCI6ICIifQ%3D%3D&code=4/QgAAm7JSWPkX
p1Bpk7PiADEgQpbVxV-X9FNXuV2GYIUUNbdDSoWzF2X9vFbZWzB6RqOuwnPV0tcsxD7o37nEhaY&scope=https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/plus.me&authuser=2&hd=maplequad.c
om&session_state=ffb57edc3867eb145eb477b8da84e3583c833d4b..45db&prompt=none (27.110.79.204): OAuth state missing from cookies
2018-08-21 12:04:04,004 INFO sqlalchemy.engine.base.Engine SELECT 1
INFO:sqlalchemy.engine.base.Engine:SELECT 1
2018-08-21 12:04:04,004 INFO sqlalchemy.engine.base.Engine ()
INFO:sqlalchemy.engine.base.Engine:()
2018-08-21 12:04:04,004 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
INFO:sqlalchemy.engine.base.Engine:BEGIN (implicit)
2018-08-21 12:04:04,005 INFO sqlalchemy.engine.base.Engine SELECT users.id AS users_id, users.name AS users_name, users.admin AS users_admin, users.created AS users_created, users.last_activity 
AS users_last_activity, users.cookie_id AS users_cookie_id, users.state AS users_state, users.encrypted_auth_state AS users_encrypted_auth_state 
FROM users 
WHERE users.cookie_id = ?
 LIMIT ? OFFSET ?
INFO:sqlalchemy.engine.base.Engine:SELECT users.id AS users_id, users.name AS users_name, users.admin AS users_admin, users.created AS users_created, users.last_activity AS users_last_activity, 
users.cookie_id AS users_cookie_id, users.state AS users_state, users.encrypted_auth_state AS users_encrypted_auth_state 
FROM users 
WHERE users.cookie_id = ?
 LIMIT ? OFFSET ?
2018-08-21 12:04:04,005 INFO sqlalchemy.engine.base.Engine ('de7f98653f934f9d849f7e6a9a89093f', 1, 0)
INFO:sqlalchemy.engine.base.Engine:('de7f98653f934f9d849f7e6a9a89093f', 1, 0)
2018-08-21 12:04:04,008 INFO sqlalchemy.engine.base.Engine UPDATE users SET last_activity=? WHERE users.id = ?
INFO:sqlalchemy.engine.base.Engine:UPDATE users SET last_activity=? WHERE users.id = ?
2018-08-21 12:04:04,008 INFO sqlalchemy.engine.base.Engine ('2018-08-21 12:04:04.006129', 5)
INFO:sqlalchemy.engine.base.Engine:('2018-08-21 12:04:04.006129', 5)
2018-08-21 12:04:04,009 INFO sqlalchemy.engine.base.Engine COMMIT
INFO:sqlalchemy.engine.base.Engine:COMMIT
[W 2018-08-21 12:04:04.023 JupyterHub log:158] 400 GET /hub/oauth_callback?state=[secret]&code=[secret]&scope=https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/plus.
me&authuser=[secret]&hd=maplequad.com&session_state=[secret]&prompt=none (priyanka4.singh@maplequad.com@27.110.79.204) 23.26ms
[W 2018-08-21 12:04:48.426 JupyterHub web:1667] 400 GET /hub/oauth_callback?state=eyJzdGF0ZV9pZCI6ICI5ZGNlZmM5NDQ2NjI0NTVkODFkYjQ0MmU0ODc1ZDQyMCIsICJuZXh0X3VybCI6ICIifQ%3D%3D&code=4/QgAAm7JSWPkX
p1Bpk7PiADEgQpbVxV-X9FNXuV2GYIUUNbdDSoWzF2X9vFbZWzB6RqOuwnPV0tcsxD7o37nEhaY&scope=https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/plus.me&authuser=2&hd=maplequad.c
om&session_state=ffb57edc3867eb145eb477b8da84e3583c833d4b..45db&prompt=none (27.110.79.204): OAuth state missing from cookies

**Comment by cmseal** [comment] 2018-08-21 12:44
@betatim Apologies for the delay responding, but the comment you proposed didn't made any difference re: pre- and post-redirect URLs.  I'm glad someone else has experienced the same issue above though.

**Comment by goenning** [comment] 2018-09-04 06:16
I don't use jupyterhub and don't know how it works, but I have a similar behaviour with another application and I landed here after some google searches. 

Have a look on your client current date/time and make sure it's in sync with a NTP server. If the client is out of sync and way ahead of the GMT, you can have the browser expiring the cookie before it's even set.

**Comment by betatim** [comment] 2018-09-08 21:47
@cmseal could you check (via your browsers developer tools) if a cookie gets set when you start the login process on your hub, and if these cookies get sent when you arrive back at the hub after the redirect to google?

If this doesn't bring up anything I am out of ideas.

**Comment by cmseal** [comment] 2018-09-11 10:53
@betatim When going to/on the accounts.google.com page, there's about 18 cookies with various short names in caps. When I then choose an account to login with, it redirects back to JupyterHub, logged in.  At this point there are 4 specific cookies (jupyterhub-user-{username}, jupyterhub-session-id, jupyterhub-hub-login, _xsrf).

If I logout, they all disappear except _xsrf.  When I go to log back in again (same window etc.), the 18 cookies appear again for the accounts.google.com page, selecting the same account to login with, I then get back to the JupyterHub but only the _xsrf cookie is there and the message "400: Bad Request.  Oauth state missing from cookies".

No idea why the other Jupyterhub cookies aren't there this time.  I've got the process screen captured, so I can go through the cookies and values etc., if more specific information will help.  It doesn't seem to do it with Chrome, but does with Safari, if that also helps.

Much appreciated!!

**Comment by betatim** [comment] 2018-09-14 18:10
No idea why Safari shows this behaviour. Could it be some kind of tracking/adblocker extension?

When you press "login with Google" (or what ever your login service is) JupyterHub will set a cookie, then redirect you. When you return from accounts.google.com and make a request to the hub again it should send those cookies that were set before you left. If they are missing you get the error you describe.

**Comment by anton-khodak** [comment] 2018-11-19 16:29
Hi, @betatim, I have exactly the scenario that you described (browser independent): cookies get set, but they disappear once google redirects back to JupyterHub. The expiration time is set one day ahead. What could be the reasons for such behaviour? The only difference I spotted is that `oauthenticator` cookies are http-only, whereas other cookies don't have this property.

**Comment by betatim** [comment] 2018-11-19 17:13
No good idea really. In my experience 80% of times when this happens is that the URL you are on when you "click login with ..." is (subtly) different from the one you get sent to after Google (or other Oauth app) redirects you.

I'd start with https://github.com/jupyterhub/jupyterhub/issues/2044#issuecomment-419675031a and https://github.com/jupyterhub/jupyterhub/issues/1519#issuecomment-342806150 which explain what should happen. Then carefully compare that to what actually happens. In particular which cookies get set and sent when.

**Comment by jwhitwo** [comment] 2018-11-21 20:12
I'm having the same issue but I'm using Azure AD instead of Google. Here's what I'm seeing in the logs:

Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/oauth2.py", line 182, in get
        user = yield self.login_user()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 473, in login_user
        authenticated = await self.authenticate(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/auth.py", line 257, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/usr/local/lib/python3.6/dist-packages/oauthenticator/azuread.py", line 96, in authenticate
        resp = yield http_client.fetch(req)
    tornado.httpclient.HTTPClientError: HTTP 400: Bad Request

I've been able to get it to work using the generic oAuth instead of azuread, but then I have scope problems.

**Comment by pratik-lal** [comment] 2019-01-25 15:34
I'm facing same error as @jwhitwo with Azure AD Oauth plugin. Is there any resolution for this?

trace:
Jan 25 15:27:15 localhost jupyterhub[7391]:     raise web.HTTPError(400, "OAuth state missing from cookies")
Jan 25 15:27:15 localhost jupyterhub[7391]: tornado.web.HTTPError: HTTP 400: Bad Request (OAuth state missing from cookies)
Jan 25 15:27:15 localhost jupyterhub[7391]: During handling of the above exception, another exception occurred:
Jan 25 15:27:15 localhost jupyterhub[7391]: Traceback (most recent call last):
Jan 25 15:27:15 localhost jupyterhub[7391]:   File "/anaconda/envs/py35/lib/python3.5/logging/__init__.py", line 986, in emit
Jan 25 15:27:15 localhost jupyterhub[7391]:     msg = self.format(record)
Jan 25 15:27:15 localhost jupyterhub[7391]:   File "/anaconda/envs/py35/lib/python3.5/logging/__init__.py", line 836, in format
Jan 25 15:27:15 localhost jupyterhub[7391]:     return fmt.format(record)
Jan 25 15:27:15 localhost jupyterhub[7391]:   File "/anaconda/envs/py35/lib/python3.5/site-packages/tornado/log.py", line 193, in for                                                                                                        mat
Jan 25 15:27:15 localhost jupyterhub[7391]:     formatted = self._fmt % record.__dict__
Jan 25 15:27:15 localhost jupyterhub[7391]: KeyError: 'highlevel'
Jan 25 15:27:15 localhost jupyterhub[7391]: Call stack:
Jan 25 15:27:15 localhost jupyterhub[7391]:   File "/anaconda/envs/py35/bin/jupyterhub", line 4, in <module>
Jan 25 15:27:15 localhost jupyterhub[7391]:     main()
Jan 25 15:27:15 localhost jupyterhub[7391]:   File "/anaconda/envs/py35/lib/python3.5/site-packages/jupyterhub/app.py", line 1968, in                                                                                                         launch_instance
Jan 25 15:27:15 localhost jupyterhub[7391]:     loop.start()
Jan 25 15:27:15 localhost jupyterhub[7391]:   File "/anaconda/envs/py35/lib/python3.5/site-packages/tornado/platform/asyncio.py", lin                                                                                                        e 127, in start
Jan 25 15:27:15 localhost jupyterhub[7391]:     self.asyncio_loop.run_forever()
Jan 25 15:27:15 localhost jupyterhub[7391]:   File "/anaconda/envs/py35/lib/python3.5/asyncio/base_events.py", line 421, in run_forev                                                                                                        er
Jan 25 15:27:15 localhost jupyterhub[7391]:     self._run_once()
Jan 25 15:27:15 localhost jupyterhub[7391]:   File "/anaconda/envs/py35/lib/python3.5/asyncio/base_events.py", line 1425, in _run_onc                                                                                                        e
Jan 25 15:27:15 localhost jupyterhub[7391]:     handle._run()
Jan 25 15:27:15 localhost jupyterhub[7391]:   File "/anaconda/envs/py35/lib/python3.5/asyncio/events.py", line 127, in _run
Jan 25 15:27:15 localhost jupyterhub[7391]:     self._callback(*self._args)
Jan 25 15:27:15 localhost jupyterhub[7391]:   File "/anaconda/envs/py35/lib/python3.5/site-packages/tornado/platform/asyncio.py", lin                                                                                                        e 117, in _handle_events
Jan 25 15:27:15 localhost jupyterhub[7391]:     handler_func(fileobj, events)
Jan 25 15:27:15 localhost jupyterhub[7391]:   File "/anaconda/envs/py35/lib/python3.5/site-packages/tornado/stack_context.py", line 2                                                                                                        76, in null_wrapper
Jan 25 15:27:15 localhost jupyterhub[7391]:     return fn(*args, **kwargs)
Jan 25 15:27:15 localhost jupyterhub[7391]:   File "/anaconda/envs/py35/lib/python3.5/site-packages/tornado/netutil.py", line 252, in                                                                                                         accept_handler
Jan 25 15:27:15 localh

**Comment by willingc** [comment] 2020-03-24 04:28
Closing this issue as it's been inactive for several months and the current JupyterHub version is 1.1. Please feel free to ask on the [discourse site](https://discourse.jupyter.org/c/jupyterhub/10) or request that we reopen this issue. Thanks! 🌻

**Closed by willingc** 2020-03-24 04:28 UTC
Labels: question

**Comment by stephen-a2z** [comment] 2020-06-11 04:25
I solve the error by the following command:
```
sudo tljh-config set hub.db.upgrade Ture
```
hope it's helpful for you

**Comment by RyanQuey** [comment] 2021-05-25 08:51
I was able to get around this issue when on localhost by making sure that I was using http://localhost:32757 throughout the entire process. 

I got the error when I started with http://127.0.0.1:32757 and redirected to http://localhost:32757/hub/oauth_callback, but if user is on http://localhost:32757 from the start of the authentication process, the error did not appear

**Comment by MaisamMD** [comment] 2021-09-09 14:41
Hi,

I have the same problem with error 400:Bad request. The interesting part is that this problem shows up when I am trying to log in from firefox/chrome on ubuntu and I don't have a problem with the windows machine. I checked the logs of the browser and it seems the cookies expire when the OIDC server redirects me back to the Jupyterhub. It seems to me a browser-independent problem. Any idea to tackle this issue?
