### ISSUE TITLE
Can not execute any cell,the state of  cell is always busy.

### ISSUE THREAD

**Issue by foxlisimulation** [jupyterhub/jupyterhub#2325] opened 2018-11-23 02:26 UTC
I can not execute any cell,and the state of  cell is always busy.Any suggestion for me ?

**Comment by minrk** [comment] 2018-11-23 15:54
Can you share the logs from the browser's javascript console and the notebook server?

Sometimes this is caused by a firewall or proxy not handling websockets.

Where is your JupyterHub? Is it on the same network, over the public internet? Is it behind nginx or apache? Do you perhaps have a corporate VPN or proxy?

**Comment by foxlisimulation** [comment] 2018-11-24 02:58
[I 2018-11-24 10:56:53.347 JupyterHub spawner:1100] Spawning jupyterhub-singleuser --port=49636
Traceback (most recent call last):
  File "/jupyterhub/anaconda3/bin/jupyterhub-singleuser", line 3, in <module>
    from jupyterhub.singleuser import main
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/jupyterhub/singleuser.py", line 34, in <module>
    from notebook.notebookapp import (
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 40, in <module>
    ioloop.install()
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'
[W 2018-11-24 10:57:03.321 JupyterHub web:1667] 500 GET /hub/user/test/ (::ffff:117.152.201.120): Spawner failed to start [status=1]. The logs for test may contain details.
[E 2018-11-24 10:57:03.323 JupyterHub log:150] {
      "X-Forwarded-Host": "47.99.206.133:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "::ffff:117.152.201.120",
      "Cookie": "jupyterhub-hub-login=\"2|1:0|10:1543028012|20:jupyterhub-hub-login|44:NDk2MGRhZjg3ZGU4NDUzZTljZjU3ZTQyNDI0YjQ3OTU=|4ec66a89a2b102248dbed47606b4ff777092c7e47f03a5b00bef098931568d8d\"; _xsrf=2|ed6a15db|73cd5cbd085dedd669f21064f75fa9e2|1542461218; jupyterhub-session-id=521cb6b736b74d298cb3376430c411c3",
      "Accept-Language": "zh-CN,zh;q=0.9",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://47.99.206.133:8000/hub/home",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36",
      "Upgrade-Insecure-Requests": "1",
      "Connection": "close",
      "Host": "47.99.206.133:8000"
    }
[E 2018-11-24 10:57:03.324 JupyterHub log:158] 500 GET /hub/user/test/ (test@::ffff:117.152.201.120) 10011.13ms

**Comment by foxlisimulation** [comment] 2018-11-24 03:09
now , it  turns to the error below
`Traceback (most recent call last):
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'loop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/notebook/base/handlers.py", line 516, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 75, in post
    type=mtype))
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 94, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 258, in start_kernel
    self.start_restarter()
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/jupyter_client/ioloop/manager.py", line 49, in start_restarter
    kernel_manager=self, loop=self.loop,
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 591, in _validate
    value = self.validate(obj, value)
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 1677, in validate
    self.error(obj, value)
  File "/jupyterhub/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 1524, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'loop' trait of an IOLoopKernelManager instance must be a ZMQIOLoop, but a value of class 'tornado.platform.asyncio.AsyncIOMainLoop' (i.e. <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fd24b6a0588>) was specified.
`

**Comment by manics** [comment] 2021-02-17 21:11
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!

**Closed by manics** 2021-02-17 21:11 UTC
