### ISSUE TITLE
Error when attempting to shut down

### ISSUE THREAD

**Issue by pmarcellino** [jupyterhub/jupyterhub#3236] opened 2020-10-30 15:31 UTC
### Bug description
When I go to the admin pannel and click "Shutdown Hub" I get an error "API request failed (500): Internal Server Error
![image](https://user-images.githubusercontent.com/46568443/97724533-08832e80-1a9b-11eb-89d5-60f8ce70a681.png)

#### Expected behaviour
I thought it would shut down

#### Actual behaviour
I get an error and it does not shut down

### How to reproduce
Click the "Shutdown Hub" button
### Your personal set up
LitlistHub distribution on a linux box

 - OS:
linux
 - Version:
1.0.0

**Comment by minrk** [comment] 2020-12-02 10:39
Can you get the jupyterhub logs around the error?

**Comment by minrk** [comment] 2020-12-03 10:16
I'm going to assume this is a duplicate of #3297 which has more information and a fix in #3298. If you can reproduce it with Python < 3.9 and share a log of the error, feel free to reopen or open a new Issue.

**Closed by minrk** 2020-12-03 10:16 UTC
Labels: bug
