### ISSUE TITLE
port should be an int, not a string

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterhub/jupyterhub#1153] opened 2017-05-25 04:06 UTC
After updating to the latest master I'm seeing the below error from JupyterHub:
![image](https://cloud.githubusercontent.com/assets/881019/26435335/ec18fec6-4151-11e7-8a54-883a0b2facb7.png)
...after changing that to `self.user.server.port = int(port)` I then see the below error:
![image](https://cloud.githubusercontent.com/assets/881019/26435511/0648076e-4153-11e7-8351-2f6c967883c8.png)

I'm posting to JupyterHub as I was up to date with DockerSpawner master so it must've been a change in JupyterHub which has triggered the problem

**Comment by willingc** [comment] 2017-05-25 12:59
Hi @dhirschfeld, 

> after changing that to self.user.server.port = int(port)

Just to clarify, where are you making this change?

**Comment by minrk** [comment] 2017-05-25 18:22
Can you show the raw command or `sys.argv` being launched?

**Comment by dhirschfeld** [comment] 2017-05-26 01:00
I just changed the [line which threw the error](https://github.com/jupyterhub/dockerspawner/blob/master/dockerspawner/dockerspawner.py#L464)

**Comment by minrk** [comment] 2017-05-28 01:06
oh, I misunderstood the message. What Spawner are you using? This means that it's returning `('ip', 'port')` instead of `('ip', port)`, which should be fixable in the Spawner.

**Comment by dhirschfeld** [comment] 2017-05-28 07:26
It's DockerSpawner, but I'm pretty sure I only updated JupyterHub and not DockerSpawner. Did JupyterHub get stricter on type checking?

Anyway, I'll see if I can get it working by *only* changing the DockerSpawner code...

**Comment by minrk** [comment] 2017-05-30 17:31
might have been a change in the docker API where ports are returned as strings instead of numbers. Can you try inspecting your containers with the docker Python client and see what types you get for the port info?

**Comment by dhirschfeld** [comment] 2017-05-30 23:30
Ah, I did also upgrade docker to 2.3. Will look into that and report back...

**Comment by cekees** [comment] 2017-06-02 19:15
I'm hitting this too now.  I think it started when I rebuilt my docker container. I don't think I changed docker versions, however.

**Comment by cekees** [comment] 2017-06-02 20:35
Here's a temporary fix for me: https://github.com/jupyterhub/dockerspawner/pull/164

**Comment by minrk** [comment] 2017-06-06 10:56
Fixed by jupyterhub/dockerspawner#164

root cause still a mystery.

**Closed by minrk** 2017-06-06 10:56 UTC
Labels: needs: more user information, question
