### ISSUE TITLE
Cull_Idle Instructions

### ISSUE THREAD

**Issue by whitead** [jupyterhub/jupyterhub#765] opened 2016-09-20 03:10 UTC
I'm having trouble using the [cull_idle example](https://github.com/jupyterhub/jupyterhub/tree/master/examples/cull-idle#configure-cull-idle-to-run-as-a-hub-managed-service) as a managed service. I added the [example config section](https://github.com/jupyterhub/jupyterhub/blob/master/examples/cull-idle/jupyterhub_config.py) to the bottom of my existing `jupyterhub_config.py` file:

```python
c = get_config()
docker_ip = '172.17.0.1' 
hub_name='127.0.0.1'

c.JupyterHub.ip = hub_name
c.JupyterHub.hub_ip = docker_ip
c.JupyterHub.debug_proxy = True
c.JupyterHub.port = 8000

c.JupyterHub.cleanup_servers = False
c.JupyterHub.cleanup_proxy = True
c.JupyterHub.ssl_key = '/etc/jupyterhub/ssl/jhub.key'
c.JupyterHub.ssl_cert = '/etc/jupyterhub/ssl/jhub.crt'


c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.hub_ip_connect = docker_ip
c.DockerSpawner.container_ip = docker_ip 


c.JupyterHub.cookie_secret_file = '/srv/jupyterhub/jupyterhub_cookie_secret'
c.JupyterHub.log_level = 'DEBUG'

#CULL_IDLE SECTION
c.JupyterHub.services = [{
    'name': 'cull-idle',
    'admin': True,
    'command': 'python cull_idle_servers.py --timeout=3600'.split()}]
```

I see the resulting error:
```
[C 2016-09-20 02:28:37.026 JupyterHub app:1444] Failed to start service cull-idle
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/app.py", line 1442, in start
        yield service.start()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/services/service.py", line 228, in start
        env['JUPYTERHUB_SERVICE_PREFIX'] = self.server.base_url
    AttributeError: 'NoneType' object has no attribute 'base_url'
```

Any ideas of what could be causing this? Thank you!

**Comment by willingc** [comment] 2016-09-20 04:02
@whitead It looks as if the `base_url` is not set in `jupyterhub_config.py`. Try adding the following to your `jupyterhub_config.py`:
```
c.JupyterHub.base_url= '/'
```

This section and the following in the JupyterHub docs on services provide a bit more information on the url and the information passed between the Hub and the service:
https://jupyterhub.readthedocs.io/en/latest/services.html#properties-of-a-service

This is the environment variables passed from the Hub to the service:
```
JUPYTERHUB_SERVICE_NAME: 'cull-idle'
JUPYTERHUB_API_TOKEN: API token assigned to the service
JUPYTERHUB_API_URL: http://127.0.0.1:8080/hub/api
JUPYTERHUB_BASE_URL: https://mydomain[:port]
JUPYTERHUB_SERVICE_PREFIX: /services/cull-idle/
```

**Comment by whitead** [comment] 2016-09-20 10:34
Hi, thank you for the reply. From what I understand, that is default value. I tried setting it to different options (including `'/'`) though and there was no change. I should mention that the `NoneType` problem is the `self.server` which is an `orm.py` `Server` class.

**Comment by willingc** [comment] 2016-09-20 11:11
@whitead Since services are still under development for the upcoming release, it's possible that you have uncovered a bug. Thanks for the additional detail. We'll take a look at the underlying code. If possible, please run with `--debug` and share with us. Thanks.

cc @minrk

**Comment by whitead** [comment] 2016-09-20 11:39
Well the services look like they'll be great when ready! I am on latest git repositories for everything, including Dockerspawner (where I just did a PR by the way) and configurable-http-proxy.

Here's more of the surrounding logfile. I've omitted my whitelist of users:

```
[I 2016-09-20 11:34:39.035 JupyterHub app:1431] Hub API listening on http://172.17.0.1:8081/hub/
[I 2016-09-20 11:34:39.040 JupyterHub app:1166] Starting proxy @ http://127.0.0.1:8000/
[D 2016-09-20 11:34:39.040 JupyterHub app:1167] Proxy cmd: ['configurable-http-proxy', '--ip', '127.0.0.1', '--port', '8000', '--api-ip', '127.0.0.1', '--api-port', '8001', '--default-target', 'http://172.17.0.1:8081', '--error-target', 'http://172.17.0.1:8081/hub/error', '--log-level', 'debug', '--ssl-key', '/etc/jupyterhub/ssl/jhub.key', '--ssl-cert', '/etc/jupyterhub/ssl/jhub.crt']
11:34:39.273 - info: [ConfigProxy] Proxying https://127.0.0.1:8000 to http://172.17.0.1:8081
11:34:39.277 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[D 2016-09-20 11:34:39.346 JupyterHub app:1195] Proxy started and appears to be up
[I 2016-09-20 11:34:39.347 JupyterHub service:220] Starting service 'cull-idle': ['python', 'cull_idle_severs.py', '--timeout=25']
[C 2016-09-20 11:34:39.350 JupyterHub app:1444] Failed to start service cull-idle
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/app.py", line 1442, in start
        yield service.start()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/services/service.py", line 228, in start
        env['JUPYTERHUB_SERVICE_PREFIX'] = self.server.base_url
    AttributeError: 'NoneType' object has no attribute 'base_url'

[D 2016-09-20 11:34:39.351 JupyterHub application:642] Exiting application: jupyterhub
```

**Comment by whitead** [comment] 2016-09-20 12:27
So I won't pretend to understand if this is right or wrong, but here's a patch that fixes my problem. I'm pretty sure the missing ```@gen.coroutine``` is a bug, but I'm not sure if just removing the api prefix is correct. The issue is that managed services don't get access to an `orm.server` (see `jupyterhub/app.py:1020`) so they can't ever have an api prefix set.

```diff
diff --git a/jupyterhub/services/service.py b/jupyterhub/services/service.py
index bfa1736..b0e9d40 100644
--- a/jupyterhub/services/service.py
+++ b/jupyterhub/services/service.py
@@ -82,6 +82,7 @@ class _ServiceSpawner(LocalProcessSpawner):
             return
         return super().make_preexec_fn(name)

+    @gen.coroutine
     def start(self):
         """Start the process"""
         env = self.get_env()
@@ -213,6 +214,7 @@ class Service(LoggingConfigurable):
             managed=' managed' if self.managed else '',
         )

+    @gen.coroutine
     def start(self):
         """Start a managed service"""
         if not self.managed:
@@ -225,7 +227,6 @@ class Service(LoggingConfigurable):
         env['JUPYTERHUB_API_TOKEN'] = self.api_token
         env['JUPYTERHUB_API_URL'] = self.hub_api_url
         env['JUPYTERHUB_BASE_URL'] = self.base_url
-        env['JUPYTERHUB_SERVICE_PREFIX'] = self.server.base_url
         env['JUPYTERHUB_SERVICE_URL'] = self.url

         self.spawner = _ServiceSpawner(
``` 

I'll just leave this open if you don't mind and so we can see if @minrk finds this useful.

**Comment by willingc** [comment] 2016-09-20 13:01
@whitead Thanks! Definitely useful since you've identified a root cause. Yes, please leave it open for @minrk. I'm going to look at the managed services tests as well.

**Comment by danielfrg** [comment] 2016-09-20 21:25
I also tried it and found the same error and same solution but I think instead of removing that env it has to be set to `self.proxy_path`.

```python
env['JUPYTERHUB_SERVICE_PREFIX'] = self.proxy_path
```

**Comment by danielfrg** [comment] 2016-09-20 21:50
I also think the spawned processes for services are not being terminated but that might just be me testing.

**Comment by minrk** [comment] 2016-09-21 10:40
Great, thanks! The missing `coroutine` isn't a bug because these methods have no `yield`s, and service spawning is not async, unlike single-user servers and Spawners in general. The bug is that URL envs are being set, even for services that don't have a URL. It should be fixed #768.

**Comment by whitead** [comment] 2016-09-21 16:38
Interesting. With my version of Tornado it won't allow me to yield a non-coroutine and gave an error on [this line](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/app.py#L1442). That's why I had to add the coroutine decorators.

**Closed** 2016-09-22 09:57 UTC
Labels: bug

**Comment by minrk** [comment] 2016-09-22 10:04
You're right that you can't yield a non-async method. That's a typo in start, fix incoming.

**Comment by minrk** [comment] 2016-09-22 10:05
#769 removes an incorrect yield.
