### ISSUE TITLE
documentation page "JupyterHub REST API" is empty

### ISSUE THREAD

**Issue by suevii** [jupyterhub/jupyterhub#3938] opened 2022-06-09 04:31 UTC
### Bug description

Hi, when I was reading the doc I found this page empty:
https://jupyterhub.readthedocs.io/en/latest/reference/rest-api.html#
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/20682164/172764130-701c3883-a25d-41ee-ba6a-b3a52f2c8c1d.png">
Want to know if it's deprecated or just forgot to fulfill.

#### Expected behaviour
The page is removed if it's deprecated.

#### Actual behaviour
This page is empty:
https://jupyterhub.readthedocs.io/en/latest/reference/rest-api.html#

### How to reproduce

1. open https://jupyterhub.readthedocs.io/en/latest/reference/rest-api.html#

### Your personal set up

 - OS:
 macOS 10.15.7 (19H1824)
 - Version(s):
 Chrome Version 102.0.5005.61 (Official Build) (x86_64)
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by GeorgianaElena** [comment] 2022-09-05 13:49
I will close this issue since it could not be reproduced and it seems it's a personal settings problem, rather than a JupyterHub bug. Please feel free to reopen or open a new one if you spot other issues happening. Thanks ✨

**Closed by GeorgianaElena** 2022-09-05 13:49 UTC
Labels: bug
