### ISSUE TITLE
Server process being moved to first user's systemd cgroup

### ISSUE THREAD

**Issue by cmaves** [jupyterhub/jupyterhub#2120] opened 2018-08-30 15:26 UTC
**Description**
When running Jupyterhub as a systemd service as described by [Run jupyterhub as a system service](https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service), the `/opt/anaconda/bin/jupyterhub` process is started under the services's cgroup (`named=systemd:/system.slice/jupyterhub.service`)

However when the first user logs in, the original `jupyterhub` process is moved to that user's cgroup (i.e. `named=systemd/user.slice/user-1000.slice`). All single-user instances are then spawned under this user's cgroup. 

This bug occurs in the latest version of Jupyterhub (0.9.2 on Anaconda 5.2) and on version 0.7.2 on Anaconda 4.4, on multiple Linux distros.

**To Reproduce**
1. Install Jupyterhub using `conda install -c conda-forge jupyterhub` per the installation guide.
2. Generate the config: `jupyterhub --generate-config -f /etc/jupyterhub/jupyterhub_config.py`
3. Install the service file provided [here](https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service#ubuntudebian-anaconda3-with-systemd)
4. Reload systemd service files: `systemctl daemon-reload`
5. Start `jupyterhub.service`
6. Login as a user

**Expected behavior**
The server process (`/opt/anaconda/bin/jupyterhub`) should always remain in the `named=systemd:/system.slice/jupyterhub.service` cgroup. The single-user instance would preferably get added to their respective user's cgroup, but remaining in the service cgroup would be acceptable.

**Desktop (not really relevant as this is a server issue):**
 - OS: Mac OS X, Arch Linux
 - Safari, Chrome, Firefox

**Additional context**
This bug is an issue because many systems use systemd's cgroups as a resource limiting mechanism. This bug loads every single-user jupyterhub instance under one user, preventing effective resource management, and allowing other users to consume resources of another user.

**Comment by cmaves** [comment] 2018-09-04 16:02
After looking into, the issue is the `PAMAuthenticator.pre_spawn_start` is responsible for starting the pam:session using `pamela.open_session(username)`. This function is run from the main process. Instead `pamela.open_session(username)` needs to be run in the preexec_fn when spawning the single user process. `pamela.close_session(username)` needs to by the singleuser process upon exit.

**Comment by jhermann** [comment] 2018-09-07 11:31
Cannot reproduce this – notebook servers and kernels appear in the service's cgroup.

```
   CGroup: /system.slice/jupyterhub.service
           ├─9310 /bin/bash /usr/sbin/jupyterhub-launcher
           ├─9321 /opt/venvs/jupyterhub/bin/python /usr/sbin/jupyterhub --url=http://:8000 --log-level=INFO --pid-file=/var/run/jupyterhub/…
           ├─9328 /usr/bin/nodejs /opt/venvs/jupyterhub/bin/configurable-http-proxy --ip  --port 8000 --api-ip 127.0.0.1 --api-port 8001 …
           ├─9365 /opt/venvs/jupyterhub/bin/python /opt/venvs/jupyterhub/bin/sudospawner
           ├─9366 /opt/venvs/jupyterhub/bin/python /opt/venvs/jupyterhub/bin/jupyterhub-singleuser --port=46192
           └─9430 /opt/venvs/jupyterhub/bin/python -m ipykernel_launcher -f /home/…
```

Python 3.6.6, Ubuntu Xenial, hub 0.9.2, notebook==5.5.0, sudospawner==0.5.2.

**Comment by cmaves** [comment] 2018-09-07 17:12
I was a unclear when I posted the initial issue. When running jupyterhub as a service, I used the second section with the  service file shown below with anaconda. SudoSpawner isn't used at all. I believe if SudoSpawner is used, because jupyterhub is not running as root, opening a PAM session probably fails, preventing the bug.
```
[Unit]
Description=Jupyterhub
After=syslog.target network.target

[Service]
User=root
Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/anaconda3/bin"
ExecStart=/opt/anaconda3/bin/jupyterhub -f /etc/jupyterhub/jupyterhub_config.py

[Install]
WantedBy=multi-user.target
```

**Comment by paulkerry1** [comment] 2020-03-04 15:14
Hi
I'm also experiencing this issue, but am not using anaconda and have a slightly different jupyterhub systemd startup file.
I am using the systemdspawner and see the same as @cmaves:
on startup "systemd-cgls" shows the jupyterhub.service (jupyterhub, node/configurable-http-proxy and cull_idle_servers.py processes in my case) running under the system.slice
When the first user connects, the jupyterhub process is moved into their user-nnnn.slice and will remain there until I "systemctl stop user-nnnn.slice" at which point, due to having "Restart=always"
and "RestartSec=10" in the jupyterhub systemd startup file, the jupyterhub process is stopped and then started again, appearing back in the system.slice until the next user connects.

This is on Debian 10 with manually installed jupyterhub 1.1.0 and jupyterhub-systemdspawner 0.13

Cheers
Paul.

**Comment by jhermann** [comment] 2020-03-04 16:44
This is pure speculation, I have these in my unit file, might make a difference…

```ini
ProtectSystem=full
ProtectControlGroups=true
```

**Comment by paulkerry1** [comment] 2020-03-05 08:52
@jhermann - that made no difference I'm afraid, but thanks for the suggestion.

**Comment by paulkerry1** [comment] 2020-03-05 13:27
The same thing happens if I use the default "jupyterhub.spawner.LocalProcessSpawner" instead of jupyterhub-systemdspawner.
I've also tried using the older /etc/init.d/jupyterhub method from...
https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service
and that does the same.

**Comment by cmaves** [comment] 2020-03-05 16:47
Depends what you mean by works as intended. If your goal is simply to keep all the Jupyterhub process in that Jupyterhub slice then SudoSpawner should work. 

However if your goal is to actually put Notebooks in their appropriate user slice similiar to when a user starts an SSH session then no this will not work.

The reason `ProtectControlGroups=true` probably didn't work is because I believe it is actually Systemd that moves the process into a seperate CGroup when the first PAM session is opened, so that configuration doesn't make a difference.

**Comment by paulkerry1** [comment] 2020-03-10 13:24
Thanks - it's the second option that I'm trying to do, making the process go into the relevant user slice.
I also notice that if I run the startup process manually as root, then the process will remain in the root user slice which also isn't what I want to do.

**Comment by cmaves** [comment] 2020-03-10 14:45
You could try [disabling sessions with in your config](https://jupyterhub.readthedocs.io/en/stable/api/auth.html) using the `open_sessions` parameter of `PAMAuthenticator`. This should prevent the session from being moved to the first user's slice. 

Then you may be able to use `systemdspawner` to do your resource limiting.

**Comment by paulkerry1** [comment] 2020-03-11 11:25
Many thanks for that suggestion - I've got it working now.

For info, adding...
`c.PAMAuthenticator.open_sessions = False`
keeps the jupyterhub process in the jupyterhub.service part of the system.slice at all times.
Using `systemdspawner` with a separate slice following https://github.com/jupyterhub/systemdspawner/issues/39 keeps all user processes in that slice, to which I can set limits.

**Comment by manics** [comment] 2022-05-22 13:50
Closing, sounds like this was resolved as far as JupyterHub is concerned. systemdspawner is in a separate repo.

**Closed by manics** 2022-05-22 13:50 UTC
Labels: needs: testing
