### ISSUE TITLE
Auto login without providing credentials after logout

### ISSUE THREAD

**Issue by major-project-1921** [jupyterhub/jupyterhub#4323] opened 2023-01-30 05:08 UTC
1. I am using Jupyterhub with Kubernetes.
2. Implemented Keycloak authentication using GenericOAuthenticator class.
3. On clicking logout, I am redirected to login page which is correct.
4. On clicking login button, I am automatically gettting logged in as the previous logged out user.

What is needed?
1. Once logout, the cookies storing user data, session, oauth state need to be cleared.
2. On clicking login again, one should be asked to choose account if they are multiple and if not should be asked for password.

Setup:
Jupyterhub- Version - 1.2.5
Helm - Version - 1.2.1

**Comment by minrk** [comment] 2023-01-30 15:14
**summary**

This is a duplicate of https://github.com/jupyterhub/oauthenticator/issues/472 , so I will close here and we can continue there if you have further questions. The short answer is presented [here](https://github.com/jupyterhub/oauthenticator/issues/472#issuecomment-982599875), and if you want logout of JupyterHub to also imply logout of keycloak (not usually desirable with oauth, but can make sense), you can:

```python
c.OAuthenticator.logout_redirect_url = "https://keycloak.../logout"
```

---

More background:

This behavior is not uncommon when using an oauth provider. This is keycloak's behavior because you're still logged in to keycloak, it has a record that you've authorized jupyterhub as an oauth client, so login with jupyterhub goes:

1. you have no jupyterhub credentials, hub redirects to keycloak to begin oauth
2. keycloak sees you are already logged in 
3. keycloak sees you have already authorized jupyterhub
4. keycloak redirects back to the application to complete oauth

If _either_ 2 or 3 had been revoked (up to keycloak, not generally jupyterhub), you'll get a prompt to re-establish one or both of those. It's up to the OAuth provider whether it prompts you to confirm login (e.g. multiple account selection) to confirm these points.

Logging out of JupyterHub doesn't generally log out of the oauth _provider_ - that would mean logging out of Google, GitHub, etc. when you leave JupyterHub, which would be very rarely desirable.

For single-purpose keycloak, it can make sense to further logout of keycloak since you could view it as 'part' of the jupyterhub application (JupyterHub has no way of knowing that). For this, you can use `OAuthenticator.logout_redirect_url` to start _another_ request after completing JupyterHub logout.

**Closed by minrk** 2023-01-30 15:14 UTC
