### ISSUE TITLE
JupyterHub behind Proxy causes "ERR_NETWORK_CHANGED" on Chrome

### ISSUE THREAD

**Issue by katsar0v** [jupyterhub/jupyterhub#1495] opened 2017-10-20 09:50 UTC
**How to reproduce the issue**
Create 2 docker containers: 1 nginx proxy (use official jupyterhub documentation), 1 JupyterHub with DockerSpawner behind it (use official jupyterhub documentation)

**What you expected to happen**

jupyterhub to work as usual behind localhost.com (localhost.com -> proxy -> jupyterhub)

**What actually happens**

It seems to actually work perfectly fine on Firefox, but on Chrome I get "ERR_NETWORK_CHANGED" error and I need to refresh in order to continue.

**Share what version of JupyterHub you are using**

0.8.0 

**JupyterHub Logs**
The following logs are only when logging in with Chrome

```
[D 2017-10-20 09:55:54.929 JupyterHub base:267] Setting cookie for admin: jupyter-hub-token, {'httponly': True}
[I 2017-10-20 09:55:54.929 JupyterHub base:345] User logged in: admin
[D 2017-10-20 09:55:54.930 JupyterHub dockerspawner:375] Getting container 'jupyter-admin'
[I 2017-10-20 09:55:54.935 JupyterHub dockerspawner:383] Container 'jupyter-admin' is gone
[W 2017-10-20 09:55:54.935 JupyterHub dockerspawner:354] container not found
[D 2017-10-20 09:55:54.935 JupyterHub base:420] Initiating spawn for admin
[D 2017-10-20 09:55:55.010 JupyterHub dockerspawner:375] Getting container 'jupyter-admin'
[D 2017-10-20 09:55:55.010 JupyterHub base:426] 0/100 concurrent spawns
[D 2017-10-20 09:55:55.012 JupyterHub base:429] 1 active servers
[I 2017-10-20 09:55:55.014 JupyterHub dockerspawner:383] Container 'jupyter-admin' is gone
[D 2017-10-20 09:55:55.017 JupyterHub dockerspawner:451] Starting host with config: {'cpuset_cpus': '0-0', 'binds': {'jupyterhub-user-admin': {'bind': '/home/jovyan/work', 'mode': 'rw'}}, 'mem_limit': '1024m', 'links': {}, 'memswap_limit': '2048m', 'network_mode': 'jupyterenv-network'}
[I 2017-10-20 09:55:55.139 JupyterHub dockerspawner:477] Created container 'jupyter-admin' (id: 99d5c34) from image jupyterenv/minimal-notebook
[I 2017-10-20 09:55:55.139 JupyterHub dockerspawner:494] Starting container 'jupyter-admin' (id: 99d5c34)
[D 2017-10-20 09:55:55.475 JupyterHub spawner:727] Polling subprocess every 30s
[I 2017-10-20 09:55:56.891 JupyterHub log:122] 200 GET /hub/api (@172.18.0.7) 0.61ms
09:55:57.419 - error: [ConfigProxy] Proxy error:  Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketCloseListener (http.js:1522:23)
    at Socket.emit (events.js:95:17)
    at TCP.close (net.js:465:12)
09:55:57.420 - error: [ConfigProxy] 503 POST /hub/login?next=

```

**Comment by willingc** [comment] 2017-11-06 17:44
Hi @katsar0v, Sorry for the delay in responding.

After the refresh in Chrome, does JupyterHub work properly?

**Comment by katsar0v** [comment] 2017-11-15 09:49
Yes it works, but this is not the issue, it is the error Chrome shows.

**Comment by minrk** [comment] 2017-11-15 09:58
Do you have a VPN or similar? The socket hangup in the proxy indicates that the connection was dropped upstream, and ERR_NETWORK_CHANGED might be indicating the same thing from the other side. This seems like a networking problem in between the browser and the Hub that jupyterhub doesn't have any control over.

**Comment by katsar0v** [comment] 2017-11-27 09:55
No VPN, happens only behind a proxy and chrome (almost always when spawning a container with any jupyter image in dockerspawner)

**Comment by ZelphirKaltstahl** [comment] 2018-01-15 14:54
I think I am experiencing the same issue, but with Jupyter Lab. It seems it is independent from Jupyter Notebook vs Jupyter Lab then. I am also using JupyterHub, so I am guessing it is some issue with one of the three:

* the NGINX configuration
* Chromium making weird requests which are unexpected (some page preload optimization?)
* the JupyterHub Tornado server and its configuration

I also have docker containers for NGINX and JupyterHub and dockerspawner starts a container for a user. Although the container is started, Chromium claims, that the Python kernel could not be started. Here are some errors on the console:

![image](https://user-images.githubusercontent.com/11130348/34947710-3bbf3cb6-fa0b-11e7-8bdf-503adc952c24.png)

In the logs of JupyterHub I do not see obviously error output:

    [D 2018-01-15 14:38:03.194 JupyterHub dockerspawner:375] Getting container 'jupyter-admin-4'
    [D 2018-01-15 14:38:03.204 JupyterHub dockerspawner:361] Container da00494 status: {'Dead': False,
         'Error': '',
         'ExitCode': 0,
         'FinishedAt': '0001-01-01T00:00:00Z',
         'OOMKilled': False,
         'Paused': False,
         'Pid': 27404,
         'Restarting': False,
         'Running': True,
         'StartedAt': '2018-01-15T14:37:33.178452529Z',
         'Status': 'running'}

So there everything _seems_ to be OK, but maybe it is not logging the critical logs. Also the container for the user is up and running, as `docker ps -a` tells me:

    CONTAINER ID        IMAGE        COMMAND                  CREATED             STATUS              PORTS                                            NAMES
    51bd3a6a0809        user-image   "tini -- start-singl…"   11 minutes ago      Up 11 minutes       8888/tcp                                         jupyter-admin-4

**Comment by katsar0v** [comment] 2018-01-29 09:50
Has somebody else also succeeded to replicate the issue behind nginx? I still get this, on Chrome / Chromium only.

**Comment by willingc** [comment] 2018-05-02 04:57
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻

**Comment by katsar0v** [comment] 2018-07-25 12:10
This happens in the new version as well, when jupyterhub is behind nginx and `self.authenticator.auto_login` is True

**Comment by andreamazzoni** [comment] 2019-06-12 21:15
Same for me. Https behind traefik and dockerspawner. Only with chrome.

**Comment by katsar0v** [comment] 2019-06-16 20:36
@willingc mind re-opening?

**Comment by willingc** [comment] 2019-06-17 01:28
@katsar0v @andreamazzoni Are you able to reproduce these issues? If so, any info that you can share would be appreciated. Thanks!

**Comment by katsar0v** [comment] 2019-06-17 10:51
@willingc am able to reproduce this. Inspecting further, the cause might not be JupyterHub at all, it's just docker changing networks and when JupyterHub is behing a proxy, it is getting disturbed under Chrome.
Here are my simple (rough) steps to reproduce this:
1. Create docker-compose file with jupyterhub behing proxy (and own docker network)
2. Run jupyterhub. It should be working fine. Leave the tab open in Chrome. (**happens only under chrome**)
3. Stop all containers and remove them (with -f if needed)
4. Delete networks in docker.
5. Re-deploy (by running `docker-compose up -d` for example) and refresh the tab. Chrome will show "ERR_NETWORK_CHANGED" while docker is messing up with networks.

If anyone else can confirm this, I'd like to take the issue into the official docker community. 
Firefox behaves normally and ok in this case.

**Comment by andreamazzoni** [comment] 2019-06-17 14:36
@willingc try with this repo: https://github.com/andreamazzoni/jupyterhub

1. docker pull jupyter/base-notebook:latest
2. make create-self-signed-certificate
3. docker-compose up
4. login with admin/password
5. select first entry from the drop-down
6. with chrome you get ERR_NETWORK_CHANGED, with firefox you get your jupyterlab instance.

**Comment by katsar0v** [comment] 2019-06-23 16:50
Escalated the bug to Chromium. **Notice**: the misbehaviour is missing when ipv6 is disabled.

https://bugs.chromium.org/p/chromium/issues/detail?id=974711#c4

**Comment by consideRatio** [comment] 2020-05-21 06:14
I ran into this while developing BinderHub on my computer with a local kubernetes cluster running lots of docker containers locally.

This was also for me only an issue on my Chrome and not on my Firefox. Thanks for opening this issue and following this up thoroughly @katsar0v!

**Comment by manics** [comment] 2021-02-17 19:43
https://github.com/jupyterhub/jupyterhub/issues/1495#issuecomment-502633790 suggests the problem is Docker and not JupyterHub. Can we close this issue?

**Comment by consideRatio** [comment] 2021-02-17 20:50
Let's close!

**Closed by consideRatio** 2021-02-17 20:50 UTC
Labels: needs: upstream action
