### ISSUE TITLE
Session restoration question

### ISSUE THREAD

**Issue by ckald** [jupyterhub/jupyterhub#137] opened 2015-01-28 21:33 UTC
Hello,

Currently session restoration works fine for me only during short disconnections and in the same browser tab. My main concern is that I can't run a lengthy computation and return to the same context later. Am I doing something wrong or is this a bug?

Additionally, kernel sometimes can be lost without any visible reason, but I can't report anything certain or reproducible here.

**Comment by minrk** [comment] 2015-01-28 21:39
(Also not a JupyterHub issue) What are the visual indications of the lost connection? What is the cause of the lost connection? Is the computer going to sleep? How long has the session been running? Where is the client and where is the server running?

What does "lost" mean? Did the kernel shutdown, or just become unresponsive? Does refreshing the page fix it, or does the kernel need to be restarted?

**Comment by dsblank** [comment] 2015-01-28 21:43
I have seen this behavior for many months now.  Refreshing the page will reconnect.

**Comment by minrk** [comment] 2015-01-28 21:49
This may, in fact, be a JupyterHub (or rather, Configurable-HTTP-Proxy) issue, if keep-alives are being ignored. They are being sent, however, so it would be surprising.

**Comment by ckald** [comment] 2015-01-28 21:51
Basically, ipython does not run any cells and after I refresh the page the session is a new one — all variables are lost.

Kernel connection indicator and notifications usually show nothing in this case (btw, to my experience, even notification `Kernel is busy` and page title prefix `(Busy)` do not work adequately — they can disappear after some time).

There is no apparent reason for the lost connection (sometimes it might be a few second network disconnection, but I understand that this should not be a problem).

My sessions typically can run for hours, but because of this behaviour I have to be conservative and make each cell to produce a DB-backed result.

Kernel restart does not help neither. I usually just close the tab and reopen the notebook

**Comment by minrk** [comment] 2015-01-28 21:56
If refreshing the page loses variables, that means that the kernel process itself is dying, which is most often caused by crashing C code (user code, not in IPython, which has no C code). How are you spawning the single-user servers?

**Comment by ckald** [comment] 2015-01-28 21:59
Default spawner. Jupyterhub process belongs to the `root` user. I wasn't paying much attention to the process output in the terminal, but haven't noticed nothing suspicious

**Comment by ckald** [comment] 2015-01-28 22:05
What "user C code" do you mean? I've noticed this behaviour while working with nothing but a SQLite database and a simple peewee ORM (Python-only as far as I understand)

**Comment by minrk** [comment] 2015-01-28 22:24
sorry, user code can be any library called by the user. I'm very surprised that the kernel appears to have been destroyed. There will be output indicating this in the single-user server's logs. When you say variables have been lost, do you mean that when you execute code, the variables are no longer defined, or that some visual representations in the output are lost? When you refresh the page, does the prompt start counting from 1 again?

**Comment by ckald** [comment] 2015-01-28 22:28
NameError is thrown as if the variable haven't been defined. 

The output usually is the same (however, I had few cases when after long disconnection I was able to see the missing output of the computation — for example, updated progressbar)

Can't say for sure about the prompt, but I think it does start from 1. Will pay attention next time

**Comment by minrk** [comment] 2015-01-28 22:43
Can you post logs from the server when this happens? Should include log output from both JupyterHub and SingleUserServer

**Comment by ckald** [comment] 2015-01-28 22:48
Where can I find them?

**Comment by minrk** [comment] 2015-01-28 22:49
It logs to stderr, so it will depend on how you started JupyterHub. If you started it in a terminal, it will be in the terminal. If you piped output to files, it will be in those files.

**Comment by ckald** [comment] 2015-02-02 13:07
Hi, I haven't been working lately with a Jupyter intense enough to reproduce the problem, but here is something that might be related: https://gist.github.com/ckald/7df0e2cc96cb9277d404

**Comment by willingc** [comment] 2016-06-07 04:07
Hi all, I'm going to close this issue since it's over a year old. If this behavior is still being observed, please comment here and I will be happy to reopen. Thanks!

**Closed by willingc** 2016-06-07 04:07 UTC
