### ISSUE TITLE
Question: user-redirect extension

### ISSUE THREAD

**Issue by msuperina** [jupyterhub/jupyterhub#2464] opened 2019-03-11 11:47 UTC
As per [UserUrlHandler](https://github.com/jupyterhub/jupyterhub/blob/b1606f21e6afbcce6b9fd4bbdd07b29448a8f3f5/jupyterhub/handlers/base.py#L1143) 
```
If a user, alice, requests /user/bob/notebooks/mynotebook.ipynb,
she will be redirected to /hub/user/bob/notebooks/mynotebook.ipynb,
which will be handled by this handler,
which will in turn send her to /user/alice/notebooks/mynotebook.ipynb.
Note that this only occurs if bob's server is not already running.
```

I was thinking of creating an extension to redirect all alice requests to `/user/bob/notebooks/mynotebook.ipynb` to `/user/alice/notebooks/mynotebook.ipynb` whether or not bob's server is running.
And I was wondering, is there any scenario I should take into account which could turn this extension into a bad idea ?

**Comment by minrk** [comment] 2019-03-28 13:48
I don't think this is how it should be done. Instead, the JupyterLab "copy shareable link" should be modified via an extension to copy the actually correct shareable url (`/user-redirect/notebooks/mynotebook.ipynb`), rather than trying to get the wrong url to do what might sometimes be the right thing.

One of the reasons being, alice visiting bob's URL *may well make sense* if bob has given alice permission to access his server, e.g. for real-time collaboration on documents. Trying to guess what should happen is something I'd like to do less of, not more, since it's a source of various problems and lots of complexity.

Closing as duplicate of #2017

**Closed by minrk** 2019-03-28 13:48 UTC
Labels: enhancement, question
