### ISSUE TITLE
JupyterHub fails to start proxy, fails

### ISSUE THREAD

**Issue by datakid** [jupyterhub/jupyterhub#2239] opened 2018-10-15 04:34 UTC
Previously I could reboot the JupyterHub server and JH would just come back up.

Recently I applied some CentOS updates, and it's completely stopped working. 

I can run JH manually from the command line successfully as the root user, but when I run it as the jupyter user it fails with `Message: 'Failed to start proxy'`

Removing the pid files doesn't change the result.

The logs show

```
 15:05:01 comp39 audit: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=jupyterhub comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
 15:05:01 comp39 jupyterhub: 15:05:01.718 [ConfigProxy] #033[32minfo#033[39m: Proxying https://10.126.17.229:443 to (no default)
 15:05:01 comp39 jupyterhub: 15:05:01.720 [ConfigProxy] #033[32minfo#033[39m: Proxy API at http://127.0.0.1:8001/api/routes
 15:05:01 comp39 jupyterhub: 15:05:01.723 [ConfigProxy] #033[31merror#033[39m: Uncaught Exception
 15:05:12 comp39 jupyterhub: --- Logging error ---
 15:05:12 comp39 jupyterhub: Traceback (most recent call last):
 15:05:12 comp39 jupyterhub:  File "/usr/lib64/python3.6/logging/__init__.py", line 993, in emit
 15:05:12 comp39 jupyterhub:    msg = self.format(record)
 15:05:12 comp39 jupyterhub:  File "/usr/lib64/python3.6/logging/__init__.py", line 839, in format
 15:05:12 comp39 jupyterhub:    return fmt.format(record)
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib64/python3.6/site-packages/tornado/log.py", line 193, in format
 15:05:12 comp39 jupyterhub:    formatted = self._fmt % record.__dict__
 15:05:12 comp39 jupyterhub: KeyError: 'highlevel'
 15:05:12 comp39 jupyterhub: Call stack:
 15:05:12 comp39 jupyterhub:  File "/usr/local/bin/jupyterhub", line 4, in <module>
 15:05:12 comp39 jupyterhub:    main()
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1968, in launch_instance
 15:05:12 comp39 jupyterhub:    loop.start()
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib64/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
 15:05:12 comp39 jupyterhub:    self.asyncio_loop.run_forever()
 15:05:12 comp39 jupyterhub:  File "/usr/lib64/python3.6/asyncio/base_events.py", line 422, in run_forever
 15:05:12 comp39 jupyterhub:    self._run_once()
 15:05:12 comp39 jupyterhub:  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1434, in _run_once
 15:05:12 comp39 jupyterhub:    handle._run()
 15:05:12 comp39 jupyterhub:  File "/usr/lib64/python3.6/asyncio/events.py", line 145, in _run
 15:05:12 comp39 jupyterhub:    self._callback(*self._args)
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1956, in launch_instance_async
 15:05:12 comp39 jupyterhub:    await self.start()
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1865, in start
 15:05:12 comp39 jupyterhub:    await self.proxy.start()
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/proxy.py", line 535, in start
 15:05:12 comp39 jupyterhub:    self._check_previous_process()
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/proxy.py", line 472, in _check_previous_process
 15:05:12 comp39 jupyterhub:    self.log.warning("Found proxy pid file: %s", pid_file)
 15:05:12 comp39 jupyterhub: Message: 'Found proxy pid file: %s'
 15:05:12 comp39 jupyterhub: Arguments: ('/srv/jupyterhub/jupyterhub-proxy.pid',)
 15:05:12 comp39 jupyterhub: --- Logging error ---
 15:05:12 comp39 jupyterhub: Traceback (most recent call last):
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/proxy.py", line 482, in _check_previous_process
 15:05:12 comp39 jupyterhub:    self._check_pid(pid)
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/proxy.py", line 456, in _check_pid
 15:05:12 comp39 jupyterhub:    os.kill(pid, 0)
 15:05:12 comp39 jupyterhub: ProcessLookupError: [Errno 3] No such process
 15:05:12 comp39 jupyterhub: During handling of the above exception, another exception occurred:
 15:05:12 comp39 jupyterhub: Traceback (most recent call last):
 15:05:12 comp39 jupyterhub:  File "/usr/lib64/python3.6/logging/__init__.py", line 993, in emit
 15:05:12 comp39 jupyterhub:    msg = self.format(record)
 15:05:12 comp39 jupyterhub:  File "/usr/lib64/python3.6/logging/__init__.py", line 839, in format
 15:05:12 comp39 jupyterhub:    return fmt.format(record)
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib64/python3.6/site-packages/tornado/log.py", line 193, in format
 15:05:12 comp39 jupyterhub:    formatted = self._fmt % record.__dict__
 15:05:12 comp39 jupyterhub: KeyError: 'highlevel'
 15:05:12 comp39 jupyterhub: Call stack:
 15:05:12 comp39 jupyterhub:  File "/usr/local/bin/jupyterhub", line 4, in <module>
 15:05:12 comp39 jupyterhub:    main()
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1968, in launch_instance
 15:05:12 comp39 jupyterhub:    loop.start()
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib64/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
 15:05:12 comp39 jupyterhub:    self.asyncio_loop.run_forever()
 15:05:12 comp39 jupyterhub:  File "/usr/lib64/python3.6/asyncio/base_events.py", line 422, in run_forever
 15:05:12 comp39 jupyterhub:    self._run_once()
 15:05:12 comp39 jupyterhub:  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1434, in _run_once
 15:05:12 comp39 jupyterhub:    handle._run()
 15:05:12 comp39 jupyterhub:  File "/usr/lib64/python3.6/asyncio/events.py", line 145, in _run
 15:05:12 comp39 jupyterhub:    self._callback(*self._args)
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1956, in launch_instance_async
 15:05:12 comp39 jupyterhub:    await self.start()
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1865, in start
 15:05:12 comp39 jupyterhub:    await self.proxy.start()
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/proxy.py", line 535, in start
 15:05:12 comp39 jupyterhub:    self._check_previous_process()
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/proxy.py", line 484, in _check_previous_process
 15:05:12 comp39 jupyterhub:    self.log.warning("Proxy no longer running at pid=%s", pid)
 15:05:12 comp39 jupyterhub: Message: 'Proxy no longer running at pid=%s'
 15:05:12 comp39 jupyterhub: Arguments: (1056,)
 15:05:12 comp39 jupyterhub: --- Logging error ---
 15:05:12 comp39 jupyterhub: Traceback (most recent call last):
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1865, in start
 15:05:12 comp39 jupyterhub:    await self.proxy.start()
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/proxy.py", line 601, in start
 15:05:12 comp39 jupyterhub:    await server.wait_up(1)
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/utils.py", line 165, in wait_for_server
 15:05:12 comp39 jupyterhub:    timeout=timeout
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/utils.py", line 155, in exponential_backoff
 15:05:12 comp39 jupyterhub:    raise TimeoutError(fail_message)
 15:05:12 comp39 jupyterhub: TimeoutError: Server at 10.126.17.229:443 didn't respond in 1 seconds
 15:05:12 comp39 jupyterhub: During handling of the above exception, another exception occurred:
 15:05:12 comp39 jupyterhub: Traceback (most recent call last):
 15:05:12 comp39 jupyterhub:  File "/usr/lib64/python3.6/logging/__init__.py", line 993, in emit
 15:05:12 comp39 jupyterhub:    msg = self.format(record)
 15:05:12 comp39 jupyterhub:  File "/usr/lib64/python3.6/logging/__init__.py", line 839, in format
 15:05:12 comp39 jupyterhub:    return fmt.format(record)
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib64/python3.6/site-packages/tornado/log.py", line 193, in format
 15:05:12 comp39 jupyterhub:    formatted = self._fmt % record.__dict__
 15:05:12 comp39 jupyterhub: KeyError: 'highlevel'
 15:05:12 comp39 jupyterhub: Call stack:
 15:05:12 comp39 jupyterhub:  File "/usr/local/bin/jupyterhub", line 4, in <module>
 15:05:12 comp39 jupyterhub:    main()
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1968, in launch_instance
 15:05:12 comp39 jupyterhub:    loop.start()
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib64/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
 15:05:12 comp39 jupyterhub:    self.asyncio_loop.run_forever()
 15:05:12 comp39 jupyterhub:  File "/usr/lib64/python3.6/asyncio/base_events.py", line 422, in run_forever
 15:05:12 comp39 jupyterhub:    self._run_once()
 15:05:12 comp39 jupyterhub:  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1434, in _run_once
 15:05:12 comp39 jupyterhub:    handle._run()
 15:05:12 comp39 jupyterhub:  File "/usr/lib64/python3.6/asyncio/events.py", line 145, in _run
 15:05:12 comp39 jupyterhub:    self._callback(*self._args)
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1956, in launch_instance_async
 15:05:12 comp39 jupyterhub:    await self.start()
 15:05:12 comp39 jupyterhub:  File "/usr/local/lib/python3.6/site-packages/jupyterhub/app.py", line 1867, in start
 15:05:12 comp39 jupyterhub:    self.log.critical("Failed to start proxy", exc_info=True)
 15:05:12 comp39 jupyterhub: Message: 'Failed to start proxy'
 15:05:12 comp39 jupyterhub: Arguments: ()
 15:05:12 comp39 systemd: jupyterhub.service: Main process exited, code=exited, status=1/FAILURE
 15:05:12 comp39 systemd: jupyterhub.service: Unit entered failed state.
 15:05:12 comp39 audit: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=jupyterhub comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
 15:05:12 comp39 systemd: jupyterhub.service: Failed with result 'exit-code'.
 15:06:17 comp39 audit: USER_AUTH pid=1496 uid=0 auid=0 ses=3 msg='op=PAM:authentication grantors=pam_rootok acct="jupyter" exe="/usr/bin/su" hostname=comp39.unix.company.com addr=? terminal=pts/2 res=success'
 15:06:17 comp39 audit: USER_ACCT pid=1496 uid=0 auid=0 ses=3 msg='op=PAM:accounting grantors=pam_succeed_if acct="jupyter" exe="/usr/bin/su" hostname=comp39.unix.company.com addr=? terminal=pts/2 res=success'
 15:06:17 comp39 audit: CRED_ACQ pid=1496 uid=0 auid=0 ses=3 msg='op=PAM:setcred grantors=pam_rootok acct="jupyter" exe="/usr/bin/su" hostname=comp39.unix.company.com addr=? terminal=pts/2 res=success'
 15:06:17 comp39 su: (to jupyter) root on pts/2
 15:06:17 comp39 audit: USER_START pid=1496 uid=0 auid=0 ses=3 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_xauth acct="jupyter" exe="/usr/bin/su" hostname=comp39.unix.company.com addr=? terminal=pts/2 res=success'
 15:09:17 comp39 audit: USER_END pid=1496 uid=0 auid=0 ses=3 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_xauth acct="jupyter" exe="/usr/bin/su" hostname=comp39.unix.company.com addr=? terminal=pts/2 res=success'
 15:09:17 comp39 audit: CRED_DISP pid=1496 uid=0 auid=0 ses=3 msg='op=PAM:setcred grantors=pam_rootok acct="jupyter" exe="/usr/bin/su" hostname=comp39.unix.company.com addr=? terminal=pts/2 res=success'
 15:09:19 comp39 audit: USER_AUTH pid=1575 uid=0 auid=0 ses=3 msg='op=PAM:authentication grantors=pam_rootok acct="jupyter" exe="/usr/bin/su" hostname=comp39.unix.company.com addr=? terminal=pts/2 res=success'
 15:09:19 comp39 audit: USER_ACCT pid=1575 uid=0 auid=0 ses=3 msg='op=PAM:accounting grantors=pam_succeed_if acct="jupyter" exe="/usr/bin/su" hostname=comp39.unix.company.com addr=? terminal=pts/2 res=success'
 15:09:19 comp39 su: (to jupyter) root on pts/2
 15:09:19 comp39 audit: CRED_ACQ pid=1575 uid=0 auid=0 ses=3 msg='op=PAM:setcred grantors=pam_rootok acct="jupyter" exe="/usr/bin/su" hostname=comp39.unix.company.com addr=? terminal=pts/2 res=success'
 15:09:19 comp39 audit: USER_START pid=1575 uid=0 auid=0 ses=3 msg='op=PAM:session_open grantors=pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_xauth acct="jupyter" exe="/usr/bin/su" hostname=comp39.unix.company.com addr=? terminal=pts/2 res=success'
```

**To Reproduce**
Reboot or `systemctl restart jupyterhub`

**Server (please complete the following information):**
CentOS 7.5.5
Jupyter user has read/write on /srv/jupyterhub and /etc/jupyterhub but no home directory. Only used for this service.

[root@comp39 log]# python36 --version 
Python 3.6.6 
[root@comp39 log]# pip list | grep jupyter
jupyter-client               5.2.3    
jupyter-console              6.0.0    
jupyter-core                 4.4.0    
jupyterhub                   0.9.4    
jupyterhub-ldapauthenticator 1.2.2    
[root@comp39 log]# pip list | grep spaw
sudospawner                  0.5.2    
[root@comp39 log]# npm ls -g| head
/usr/lib
├─┬ configurable-http-proxy@4.0.1

**jupyterhub.py** 
```
c.Application.log_datefmt = '%Y-%m-%d %H:%M:%S'
c.Application.log_format = '[%(name)s]%(highlevel)s %(message)s'
c.Application.log_level = 30
c.JupyterHub.bind_url = 'https://10.126.17.229:443'
c.JupyterHub.cookie_secret_file = '/etc/jupyterhub/jupyterhub_cookie_secret'
c.JupyterHub.db_url = 'sqlite:///jupyterhub.sqlite'
c.JupyterHub.hub_ip = '0.0.0.0'
c.JupyterHub.pid_file = '/srv/jupyterhub/jupyter.pid'
c.JupyterHub.proxy_class = 'jupyterhub.proxy.ConfigurableHTTPProxy'
c.JupyterHub.redirect_to_server = True
c.JupyterHub.spawner_class='sudospawner.SudoSpawner'
c.JupyterHub.ssl_cert = '/etc/ssl/certs/jupyter-selfsigned.crt'
c.JupyterHub.ssl_key = '/etc/jupyterhub/jupyter-selfsigned.key'
c.Spawner.ip = '10.126.17.229'
c.Spawner.notebook_dir = '~/notebooks/'
c.Authenticator.admin_users = {'ladmin','madmin'}
c.Authenticator.whitelist = {
        'user1',
        'user2',
        'user3',
        'user4',
        'user5',
        'user6',
        'user7',
        'user8',
        'user9',
        'user10',
        'user11',
        'user12',
        'user13',
        'user14',
        'user15',
        'user16',
        'user17',
        'user18',
        'user19',
        'user20'}
c.LocalAuthenticator.create_system_users = True
c.PAMAuthenticator.check_account = True
c.PAMAuthenticator.encoding = 'utf8'
c.PAMAuthenticator.open_sessions = False
c.PAMAuthenticator.service = 'login'
```
**systemd file**
```
[Unit]
Description=Jupyterhub
After=network-online.target

[Service]
User=jupyter
Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin:/root/bin"
ExecStart=/usr/local/bin/jupyterhub -f /etc/jupyterhub/jupyterhub_config.py
WorkingDirectory=/srv/jupyterhub/

[Install]
WantedBy=multi-user.target
```

**Comment by goforgold** [comment] 2019-05-27 06:07
I could fix this quickly by deleting the proxy pid file

`rm /data/shared/jupyterhub/jupyterhub-proxy.pid`

For me the service failed to start after I stopped and started EC2 instance from AWS console.

**Comment by fishbeef** [comment] 2019-09-19 06:19
This did not fix it for me

**Comment by manniche** [comment] 2019-11-07 13:29
The problem is with the configuration of the logger:

```
c.Application.log_format = '[%(name)s]%(highlevel)s %(message)s'
```

See also https://github.com/ipython/traitlets/issues/268 for a detailed explanation

**Comment by manics** [comment] 2021-02-17 21:03
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!

**Closed by manics** 2021-02-17 21:03 UTC
