### ISSUE TITLE
"await" option for server spawn API endpoints

### ISSUE THREAD

**Issue by jrouly** [jupyterhub/jupyterhub#3577] opened 2021-08-19 19:05 UTC
### Proposed change

Right now the various server spawn endpoints (e.g. `POST /users/{name}/server`) return 201 _or possibly_ 202.

They return 202 when the spawner's status is `pending` (see [here](https://github.com/jupyterhub/jupyterhub/blob/main/jupyterhub/apihandlers/users.py#L477-L480) and [here](https://github.com/jupyterhub/jupyterhub/blob/main/jupyterhub/apihandlers/users.py#L496-L499)).

It would be nice to introduce an `?await=true` parameter on these routes which, when set, would cause the API to block until the spawner is no longer pending (and has either succeeded or failed).

This could be accomplished by `await`ing a `Promise` that resolves when `not spawner.pending`.

### Alternative options

Alternatively, the spawn endpoints could return a spawn ID which could be looked up on a dedicated spawn resource endpoint to track the status of a particular spawn. This would be a larger feature-add and higher lift.

### Who would use this feature?

REST API consumers.

I have an EKS cluster running the jupyterhub Helm chart, and we've defined a health check against the spawn endpoint for a default user to verify that servers can indeed be spawned (we've had intermittent issues with image pulling recently). We recently discovered that the endpoint may return `202` in conditions where the server does not actually spawn successfully.

### (Optional): Suggest a solution

This could be accomplished by `await`ing a `Promise` that resolves when `not spawner.pending` in the `UserServerAPIHandler`.

**Comment by minrk** [comment] 2021-09-23 09:52
I think the progress API provides this behavior already - an EventStream that publishes events until the server is ready.

It does happen to be *two* requests instead of one, but progress always works even if servers are fully ready when the request begins, and doesn't suffer from various timeout issues that might be caused by sending no data for 3-5 minutes in response to a regular POST requests.

[here is an example][example] of using the API to start a server and wait for it to be ready, without any polling requests.

[example]: https://github.com/jupyterhub/jupyterhub/blob/70ac143cfebbeb6e09c36e4ce75674e1b0ddcd3a/examples/server-api/start-stop-server.py#L98-L107

**Comment by manics** [comment] 2022-05-22 15:10
Closing as this was answered

**Closed by manics** 2022-05-22 15:10 UTC
Labels: question
