### ISSUE TITLE
configurable-http-proxy: error: "value" required in setHeader("x-forwarded-host", value)

### ISSUE THREAD

**Issue by willfurnass** [jupyterhub/jupyterhub#1137] opened 2017-05-16 14:24 UTC
We've set up JupyterHub 0.7.2 and `configurable-http-proxy 2.0.0` (both installed from conda-forge) on a Centos 7 VM behind a Cisco Application Control Engine module that does TLS offloading.  I've therefore configured JH not to use SSL by commenting out the `ssl_cert` and `ssl_key` params in the JH config file.

We then get the above error.  Stack trace below:

```
[I 2017-05-16 15:10:28.216 JupyterHub app:1453] Hub API listening on http://172.30.XX.YY:8081/hub/
[W 2017-05-16 15:10:28.219 JupyterHub app:1174] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else
[I 2017-05-16 15:10:28.219 JupyterHub app:1176] Starting proxy @ http://*:8443/
[D 2017-05-16 15:10:28.220 JupyterHub app:1177] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8443', '--api-ip', '127.0.0
15:10:28.463 - info: [ConfigProxy] Proxying http://*:8443 to http://172.30.XX.YY:8081
15:10:28.467 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[D 2017-05-16 15:10:28.527 JupyterHub app:1205] Proxy started and appears to be up
[I 2017-05-16 15:10:28.528 JupyterHub app:1485] JupyterHub is now running at http://127.0.0.1:8443/
15:10:36.495 - debug: [ConfigProxy] PROXY WEB / to http://172.30.XX.YY:8081
15:10:36.513 - error: [ConfigProxy] Error in handler for GET /:  Error: "value" required in setHeader("x-forwarded-host", value)
at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:355:11)
at new ClientRequest (_http_client.js:85:14)
at Object.exports.request (http.js:31:10)
at Array.stream (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/node_modules/http-proxy/lib/http
at ProxyServer.<anonymous> (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/node_modules/http-pro
at /usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/lib/configproxy.js:441:30
at Object.<anonymous> (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/lib/configproxy.js:324:17)
at Object.value (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/lib/store.js:30:12)
at Object.value (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/lib/store.js:66:14)
at Object.<anonymous> (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/lib/configproxy.js:322:20
```

Observed behaviour: holding page (presented by Cisco ACE).
Expected behaviour: access to JupyterHub web UI.

Worth noting that we had a very similar config with JupyterHub 0.3 which worked fine.

**Comment by minrk** [comment] 2017-05-20 23:23
It looks like the tracebacks are truncated, perhaps by your shell? It might be helpful if we could see the full traceback if you can produce them again.

If you upgraded recently, this could be a recent change in the node-http-proxy library.

It could be related to the Application Control Engine in front setting or failing to set expected headers. Can you test connecting to the proxy directly, just to isolate the cause?

**Comment by willfurnass** [comment] 2017-05-22 15:58
Whoops; here's an untruncated stack trace: 
```
[I 2017-05-22 15:25:07.496 JupyterHub app:1453] Hub API listening on http://172.30.XX.YY:8081/hub/
[W 2017-05-22 15:25:07.500 JupyterHub app:1174] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2017-05-22 15:25:07.500 JupyterHub app:1176] Starting proxy @ http://143.167.VV.WW:8443/
[D 2017-05-22 15:25:07.500 JupyterHub app:1177] Proxy cmd: ['configurable-http-proxy', '--ip', '143.167.VV.WW', '--port', '8443', '--api-ip', '127.0.0.1', '--api-port', '8001', '--default-target', 'http://172.30.XX.YY:8081', '--error-target', 'http://172.30.XX.YY:8081/hub/error', '--log-level', 'debug']
15:25:07.738 - info: [ConfigProxy] Proxying http://143.167.VV.WW:8443 to http://172.30.XX.YY:8081
15:25:07.743 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[D 2017-05-22 15:25:07.807 JupyterHub app:1205] Proxy started and appears to be up
[I 2017-05-22 15:25:07.808 JupyterHub app:1485] JupyterHub is now running at http://143.167.VV.WW:8443/
15:26:05.735 - debug: [ConfigProxy] PROXY WEB / to http://172.30.XX.YY:8081
15:26:05.755 - error: [ConfigProxy] Error in handler for GET /:  Error: "value" required in setHeader("x-forwarded-host", value)
at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:355:11)
at new ClientRequest (_http_client.js:85:14)
at Object.exports.request (http.js:31:10)
at Array.stream (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:111:74)
May 22 15:26:05 jh-prod.shef.ac.uk jupyterhub[33038]: at ProxyServer.<anonymous> (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/node_modules/http-pro
xy/lib/http-proxy/index.js:80:21)
at /usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/lib/configproxy.js:441:30
at Object.<anonymous> (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/lib/configproxy.js:324:17)
at Object.value (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/lib/store.js:30:12)
at Object.value (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/lib/store.js:66:14)
at Object.<anonymous> (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/lib/configproxy.js:322:20)
15:26:05.766 - debug: [ConfigProxy] PROXY WEB / to http://172.30.XX.YY:8081
15:26:05.771 - error: [ConfigProxy] Error in handler for GET /:  Error: "value" required in setHeader("x-forwarded-host", value)
at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:355:11)
at new ClientRequest (_http_client.js:85:14)
at Object.exports.request (http.js:31:10)
at Array.stream (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:111:74)
at ProxyServer.<anonymous> (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/node_modules/http-pro
xy/lib/http-proxy/index.js:80:21)
at /usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/lib/configproxy.js:441:30
at Object.<anonymous> (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/lib/configproxy.js:324:17)
at Object.value (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/lib/store.js:30:12)
at Object.value (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/lib/store.js:66:14)
at Object.<anonymous> (/usr/local/packages/apps/conda/envs/jupyterhub/lib/node_modules/configurable-http-proxy/lib/configproxy.js:322:20
```

NB `jhprod` is the hostname of the box running jupyterhub and configurable-http-proxy.

Bypassing the Cisco ACE module and connecting to configurable-node-proxy directly works fine.

Also, I swapped out JupyterHub + configurable-http-proxy for a Flask app that just prints out HTTP headers of requests.  Here's what I get when I then connect it from my laptop via the Cisco ACE module:

```
<general_cisco_ace_ip_addr> - - [22/May/2017 15:37:15] "GET / HTTP/1.0" 200 -
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0
X-Forwarded-For: <my_laptop_ip>
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Cache-Control: no-cache
Accept-Language: en-US,en;q=0.5
Host: <cisco_ace_ip_for_jupyterhub_service>
Pragma: no-cache
X-Cluster-Client-Ip: <my_laptop_ip>
Cookie: _xsrf=....
Connection: Keep-Alive
Upgrade-Insecure-Requests: 1
Accept-Encoding: gzip, deflate, br
Dnt: 1
```

**Comment by minrk** [comment] 2017-06-07 14:02
That's indeed very odd. It appears to be a bug in node-http-proxy. Can you share `npm list -g`? It looks like this should be fixed in node-http-proxy 1.15 or later, based on [this](https://github.com/nodejitsu/node-http-proxy/commit/b781af641ade623b7a1537e32cf9f8fffd3e551e) .

**Comment by minrk** [comment] 2017-06-07 15:03
Ah, I see that you have configurable-http-proxy from conda. This package needed an update, and should be okay now. If you `conda upgrade configurable-http-proxy`, you should get an updated version without this issue.

**Comment by willingc** [comment] 2017-07-16 16:02
Closing this issue since it appears to be resolved. Please feel free to leave an issue at [jupyter/help](https://github.com/jupyter/help) or leave a comment requesting this issue be reopened. Thanks to all!

**Closed by willingc** 2017-07-16 16:02 UTC
