### ISSUE TITLE
Can't launch jupyterhub

### ISSUE THREAD

**Issue by hnmn** [jupyterhub/jupyterhub#1018] opened 2017-03-11 14:01 UTC
can't launch jupyterhub . when i run 'jupyterhub' Command even i run 'jupyterhub --generate-config' it shows following error .i have python3.6 and latest pip3 .

Here is troubleshoot :

```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/jupyterhub", line 3, in <module>
    from jupyterhub.app import main
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/jupyterhub/app.py", line 60, in <module>
    from .auth import Authenticator, PAMAuthenticator
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/jupyterhub/auth.py", line 15, in <module>
    import pamela
  File "/data/data/com.termux/files/usr/lib/python3.6/site-packages/pamela.py", line 82, in <module>
    PAM_STRERROR = LIBPAM.pam_strerror
  File "/data/data/com.termux/files/usr/lib/python3.6/ctypes/__init__.py", line 357, in __getattr__
    func = self.__getitem__(name)
  File "/data/data/com.termux/files/usr/lib/python3.6/ctypes/__init__.py", line 362, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: undefined symbol: pam_strerror
```

**Comment by minrk** [comment] 2017-03-13 12:08
That is strange indeed. On What OS / distro / version?

**Comment by simopal6** [comment] 2017-04-03 08:44
Same error, on Slackware 14.1

**Comment by willingc** [comment] 2017-04-28 21:21
I'm going to go ahead and close this as it is likely the underlying distro or installation does not have the shared libraries/dll correctly installed [ref on ctypes](https://docs.python.org/3/library/ctypes.html#finding-shared-libraries). If you are experiencing this error still, please send us additional details and we would be happy to reopen this issue. Thanks! :sunny:

**Closed by willingc** 2017-04-28 21:21 UTC
Labels: needs: more user information, question

**Comment by romainx** [comment] 2020-05-07 10:05
Hello,

Just to share, I ran into the same issue with a base image [Red Hat UBI Minimal](https://developers.redhat.com/products/rhel/ubi/) `8.1`.

The root cause was that the `PAM` library is not installed by default. It can be fixed by installing it `microdnf install pam`.

Maybe it could be added to the [Prerequisites](https://jupyterhub.readthedocs.io/en/stable/quickstart.html#prerequisites) section of the documentation. I can draft a PR if you are OK 😄  ?

Best

## Note

Here is snippet of the `Dockerfile` with the fix.

```diff
+ RUN microdnf -y install \
+   pam && \
+   microdnf clean all

ARG jhub_version="1.1.0"

RUN conda install --channel conda-forge --quiet --yes \
    "jupyterhub=${jhub_version}" && \
    conda clean --all -f -y

EXPOSE 8000

CMD ["jupyterhub"]
```

**Comment by manics** [comment] 2020-05-07 10:06
@romainx PRs are always welcome!

**Comment by romainx** [comment] 2020-05-08 04:14
@manics thanks for the quick reply. PR #3040 done.
Hope it helps.
Best.

**Comment by Geekly** [comment] 2022-05-20 16:35
Realizing this is an old issue, but it kept showing up in my own search, so I thought I would include my fix here. I was running into this issue on a Synology NAS.

Inside pamela.py, `cytpes.CDLL.find_library()` was not finding "libpam.so". It wouldn't do it at the python prompt either.

I added `cdll` to the imports:

`from ctypes import cdll`

and replaced 

`LIBPAM = CDLL(find_library("pam"))`

with

`LIBPAM = cdll.LoadLibrary("libpam.so")`

This seemed to fix it. I'm still not sure what was going on with find_library() but I suspect it was a Synology OS issue.

**Comment by piaoyidaodi** [comment] 2023-12-28 07:19
> Realizing this is an old issue, but it kept showing up in my own search, so I thought I would include my fix here. I was running into this issue on a Synology NAS.
> 
> Inside pamela.py, `cytpes.CDLL.find_library()` was not finding "libpam.so". It wouldn't do it at the python prompt either.
> 
> I added `cdll` to the imports:
> 
> `from ctypes import cdll`
> 
> and replaced
> 
> `LIBPAM = CDLL(find_library("pam"))`
> 
> with
> 
> `LIBPAM = cdll.LoadLibrary("libpam.so")`
> 
> This seemed to fix it. I'm still not sure what was going on with find_library() but I suspect it was a Synology OS issue.

Very useful to me. Synology DS918+ DSM 6.2.1，Thank you.
