### ISSUE TITLE
Fail to open PAM session

### ISSUE THREAD

**Issue by gracehllee** [jupyterhub/jupyterhub#471] opened 2016-03-08 20:56 UTC
I can't find any solution, 
I login in jupyterhub web GUI using username in system, it show errors:
![screen shot 2016-03-08 at 2 54 02 pm](https://cloud.githubusercontent.com/assets/9956970/13616075/f17d2c32-e53d-11e5-8263-af384b1f5176.png)

**Comment by minrk** [comment] 2016-03-09 09:56
Exceptions in preexec can be hard to debug because you don't get tracebacks. But most often, they are caused by permission issues. What user is running the Hub?

**Comment by gracehllee** [comment] 2016-03-10 15:25
Using root run the jupyterhub,
I create 3 users without passwords in system, only first one could login, the others can't login..
the error message is PAM authentication failed, Failed login for None

Any suggestion for this case?

**Comment by yuvipanda** [comment] 2016-04-01 00:46
Is this related to https://github.com/jupyter/jupyterhub/commit/40368b8f555f04ffdd662ffe99d32392a088b1d2?

**Comment by minrk** [comment] 2016-04-01 05:53
yes, probably. I think the PAM session actions we are doing are just completely wrong. I think maybe it should be disabled by default while we figure out what the right thing to do is.

**Comment by willingc** [comment] 2016-06-06 13:51
@minrk Is this an issue that still should be open or has PAM session code been updated enough to close this?

**Comment by minrk** [comment] 2016-06-06 18:45
This is still an issue. I've added an option to skip the session stuff entirely, but there isn't a way to have session open/close work correctly with this.

**Comment by skruse** [comment] 2018-09-03 12:46
I think pam_open_session needs an handle on which pam_authenticate was run successfully before.

At least I tested this successfully by adding the open/close session calls to authenticate in pamela.

**Comment by dclong** [comment] 2020-03-12 04:32
I've encountered the same error with JupyterLab 2.0.1 and JupyterHub 1.1.0. It works fine for JupyterLab 1.2 though. It there a compatible issue with JupyterLab 2.0?
```
[W 2020-03-11 21:17:12.174 JupyterHub auth:956] Failed to open PAM session for dclong: [PAM Error 14] Cannot make/remove an entry for the specified session
[W 2020-03-11 21:17:12.174 JupyterHub auth:957] Disabling PAM sessions from now on.
[I 2020-03-11 21:17:12.180 JupyterHub spawner:1417] Spawning jupyterhub-singleuser --port=53669 --notebook-dir=/workdir --NotebookApp.default_url=/lab
[I 2020-03-11 21:17:13.139 JupyterHub log:174] 302 GET /hub/spawn -> /hub/spawn-pending/dclong (dclong@172.17.0.1) 1006.07ms
[I 2020-03-11 21:17:13.149 JupyterHub pages:347] dclong is pending spawn
[I 2020-03-11 21:17:13.154 JupyterHub log:174] 200 GET /hub/spawn-pending/dclong (dclong@172.17.0.1) 7.48ms
[I 2020-03-11 21:17:13.351 SingleUserNotebookApp handlers:164] [beakerx] enabled
[I 2020-03-11 21:17:13.703 SingleUserNotebookApp extension:157] JupyterLab extension loaded from /usr/local/lib/python3.7/dist-packages/jupyterlab
[I 2020-03-11 21:17:13.703 SingleUserNotebookApp extension:158] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 2020-03-11 21:17:13.760 SingleUserNotebookApp singleuser:561] Starting jupyterhub-singleuser server version 1.1.0
[I 2020-03-11 21:17:13.764 JupyterHub base:855] User dclong took 1.626 seconds to start
[I 2020-03-11 21:17:13.765 JupyterHub proxy:262] Adding user dclong to proxy /user/dclong/ => http://127.0.0.1:53669
[I 2020-03-11 21:17:13.767 JupyterHub log:174] 200 GET /hub/api (@127.0.0.1) 0.92ms
[I 2020-03-11 21:17:13.767 SingleUserNotebookApp notebookapp:1924] Serving notebooks from local directory: /workdir
[I 2020-03-11 21:17:13.767 SingleUserNotebookApp notebookapp:1924] The Jupyter Notebook is running at:
[I 2020-03-11 21:17:13.767 SingleUserNotebookApp notebookapp:1924] http://127.0.0.1:53669/user/dclong/
[I 2020-03-11 21:17:13.767 SingleUserNotebookApp notebookapp:1925] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
21:17:13.768 [ConfigProxy] info: Adding route /user/dclong -> http://127.0.0.1:53669
21:17:13.769 [ConfigProxy] info: Route added /user/dclong -> http://127.0.0.1:53669
21:17:13.769 [ConfigProxy] info: 201 POST /api/routes/user/dclong 
[I 2020-03-11 21:17:13.770 JupyterHub users:609] Server dclong is ready
[I 2020-03-11 21:17:13.770 JupyterHub log:174] 200 GET /hub/api/users/dclong/server/progress (dclong@172.17.0.1) 519.57ms
[I 2020-03-11 21:17:13.772 SingleUserNotebookApp singleuser:542] Updating Hub with activity every 300 seconds
[I 2020-03-11 21:17:13.788 JupyterHub log:174] 200 POST /hub/api/users/dclong/activity (dclong@127.0.0.1) 14.15ms
[I 2020-03-11 21:17:13.792 JupyterHub log:174] 302 GET /hub/spawn-pending/dclong -> /user/dclong/ (dclong@172.17.0.1) 2.39ms
[I 2020-03-11 21:17:13.825 JupyterHub log:174] 302 GET /hub/api/oauth2/authorize?client_id=jupyterhub-user-dclong&redirect_uri=%2Fuser%2Fdclong%2Foauth_callback&response_type=code&state=[secret] -> /user/dclong/oauth_callback?code=[secret]&state=[secret] (dclong@172.17.0.1) 13.16ms
[I 2020-03-11 21:17:13.858 JupyterHub log:174] 200 POST /hub/api/oauth2/token (dclong@127.0.0.1) 21.94ms
[I 2020-03-11 21:17:13.871 JupyterHub log:174] 200 GET /hub/api/authorizations/token/[secret] (dclong@127.0.0.1) 10.54ms
[I 2020-03-11 21:17:13.871 SingleUserNotebookApp auth:981] Logged-in user {'kind': 'user', 'name': 'dclong', 'admin': True, 'groups': [], 'server': '/user/dclong/', 'pending': None, 'created': '2020-03-12T04:16:40.537189Z', 'last_activity': '2020-03-12T04:17:13.866028Z', 'servers': None}
[I 2020-03-11 21:17:14.377 JupyterHub log:174] 200 GET /hub/api/authorizations/token/[secret] (dclong@127.0.0.1) 8.67ms
[I 2020-03-11 21:17:15.459 SingleUserNotebookApp build_handler:47] Build is up to date
21:21:40.763 [ConfigProxy] info: 200 GET /api/routes 
[I 2020-03-11 21:21:40.770 JupyterHub proxy:320] Checking routes
[I 2020-03-11 21:22:18.765 JupyterHub log:174] 200 POST /hub/api/users/dclong/activity (dclong@127.0.0.1) 12.27ms
21:26:40.780 [ConfigProxy] info: 200 GET /api/routes 
[I 2020-03-11 21:26:40.785 JupyterHub proxy:320] Checking routes
[I 2020-03-11 21:27:27.258 JupyterHub log:174] 200 POST /hub/api/users/dclong/activity (dclong@127.0.0.1) 10.76ms
```

**Comment by consideRatio** [comment] 2020-10-18 11:48
## Suggested action points
- [ ] Validate this is this still an issue for JupyterHub 1.2.0b1 or later
- [ ] Describe how to reproduce it

**Comment by manics** [comment] 2021-02-17 19:05
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems and believe it's a bug in JupyterHub please open a new issue with full instructions for reproducing your deployment. Thanks! If you want some configuration help please post on the [Jupyter Community Forum](https://discourse.jupyter.org/)

**Closed by manics** 2021-02-17 19:05 UTC
Labels: bug, enhancement
