### ISSUE TITLE
pyspark run in worker with python3 causing issues with ambari awareness script (related #889)

### ISSUE THREAD

**Issue by beeva-gerardovazquez** [jupyterhub/jupyterhub#913] opened 2016-12-21 09:08 UTC
**How to reproduce the issue**

Hadoop Cluster deployed with HDP 2.5 - installed spark and spark2
Installed inside anaconda2 env

>> kernel file for pyspark <<
{
 "display_name": "pyspark",
 "language": "python",
 "argv": [
  "/opt/anaconda2/bin/python2.7",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ],
 "env": {
  "SPARK_HOME": "/usr/hdp/current/spark-client/",
  "PYTHONPATH": "/usr/hdp/current/spark-client/python:/usr/hdp/current/spark-client/python/build:/usr/hdp/current/spark-client/lib:/usr/hdp/current/spark-client/python/lib/py4j-0.9-src.zip",
  "PYSPARK_PYTHON" : "/opt/anaconda2/bin/python2.7",
  "PYSPARK_DRIVER_PYTHON" : "/opt/anaconda2/bin/python2.7",
  "PYTHONSTARTUP": "/usr/hdp/current/spark-client/python/pyspark/shell.py",
  "PYSPARK_SUBMIT_ARGS": "--master yarn-client --num-executors 2 --driver-memory 3g --executor-memory 2g  pyspark-shell"
 }
}
>>  <<

**What you expected to happen**
been able to start a pyspark-shell

**What actually happens**
the pyspark-shell start throwing out errors relating executors trying to run a python2 script with python3

**Share what version of JupyterHub you are using**
0.7

Error found in console

```
16/11/29 16:24:20 WARN ScriptBasedMapping: Exception running /etc/hadoop/conf/topology_script.py some.ip.address
ExitCodeException exitCode=1:   File "/etc/hadoop/conf/topology_script.py", line 63
    print rack
             ^
SyntaxError: Missing parentheses in call to 'print'

	at `org.apache.hadoop.util.Shell.runCommand(Shell.java:576)`

```

Workaround:
set in spark-env.sh
export PATH=/opt/anaconda2/bin:$PATH

**Comment by minrk** [comment] 2016-12-21 11:31
Is this in a terminal in JupyterHub? Kernelspecs only affect Jupyter kernels, not other terminal programs. You may want to set those environment variables for your user in general, in addition to just the single kernel, which will only affect notebooks.

**Comment by beeva-gerardovazquez** [comment] 2016-12-21 11:58
I'm staring manually jupyterhub from a conda environment
When the pyspark kernel starts the output is written into the console, is where I found that traces.

**Comment by minrk** [comment] 2016-12-21 15:01
Hm, can you show the environment variables in the subprocess? It sounds like there's something that is hardcoded to use `python` instead of `PYSPARK_PYTHON`.

**Comment by beeva-gerardovazquez** [comment] 2016-12-22 07:22
For the process running in the jupyterhub server. 

# ps w 30860 
  PID TTY      STAT   TIME COMMAND
30860 ?        Ssl    0:57 /opt/anaconda2/bin/python2.7 -m ipykernel -f /home/api-ingestion/.local/share/jupyter/runtime/kernel-67559645-c646-478d-93d5-180e4c7a9dd5.json

# strings -a /proc/30860/environ 
PYTHONPATH=/usr/hdp/current/spark-client/python:/usr/hdp/current/spark-client/python/build:/usr/hdp/current/spark-client/lib:/usr/hdp/current/spark-client/python/lib/py4j-0.9-src.zip
HOME=/home/api-ingestion
PYSPARK_DRIVER_PYTHON=/opt/anaconda2/bin/python2.7
CONDA_DEFAULT_ENV=jupyterhub
SHELL=/bin/bash
SPARK_HOME=/usr/hdp/current/spark-client/
JPY_PARENT_PID=20912
USER=api-ingestion
PATH=/opt/anaconda2/envs/jupyterhub/bin:/opt/anaconda2/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
PYSPARK_SUBMIT_ARGS=--master yarn-client --num-executors 2 --driver-memory 3g --executor-memory 2g  pyspark-shell
PYTHONSTARTUP=/usr/hdp/current/spark-client/python/pyspark/shell.py
LANG=en_US.UTF-8
PYSPARK_PYTHON=/opt/anaconda2/bin/python2.7

**Comment by mariusvniekerk** [comment] 2016-12-22 11:36
So this is an issue caused by your yarn topology.py file not being compatible with python 3. 

Ambari has been known to lay down non python 3 compatible things. 

You can avoid it by 

Fixing the Topology.py. 
Prepending your path so that python results in py2

**Comment by beeva-gerardovazquez** [comment] 2016-12-22 16:50
@mariusvniekerk yes, as seen in #889

Idea was to add the issue with more info as is not only related to Toree but will jump in any ambari deployed cluster trying to run pyspark from jupyterhub. And great if anyone finds another workaround :)

**Comment by willingc** [comment] 2017-02-13 23:30
@minrk Should we close this issue as "out of scope" for JupyterHub since it is related to ambari and python2? Comments could still be added in the closed issue.

**Comment by minrk** [comment] 2017-02-14 13:02
@willingc yes, thanks

**Closed by minrk** 2017-02-14 13:02 UTC
Labels: reference

**Comment by sajanraj** [comment] 2020-09-04 13:32
is there any fix to avoid these warnings?

--------------------------------------------------------------------------------------------------------------

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
20/09/04 13:21:40 WARN ScriptBasedMapping: Exception running /etc/hadoop/conf/topology_script.py 172.31.12.12 
ExitCodeException exitCode=1:   File "/etc/hadoop/conf/topology_script.py", line 63
    print rack

----------------------------------------------------

The entire code topology_script is written in python 2 causing this issue.
