### ISSUE TITLE
can not start cull_idle_servers

### ISSUE THREAD

**Issue by ktong** [jupyterhub/jupyterhub#1456] opened 2017-09-27 19:21 UTC
**How to reproduce the issue**

configure cull_idea_servers as below then start jupyterhub:
```
    c.JupyterHub.services = [
        {
            'name': 'cull-idle',
            'admin': True,
            'command': 'python cull_idle_servers.py --timeout=3600'.split(),
        }
    ]
```

**What you expected to happen**
cull_idea_servers runs.

**What actually happens**
cull_idea-servers quit with exception.
```
[I 2017-09-27 18:57:49.984 JupyterHub service:266] Starting service 'cull-idle': ['python3', 'cull_idle_servers.py', '--timeout=86400', '--cull_every=600']

Traceback (most recent call last):
  File "cull_idle_servers.py", line 89, in <module>
    loop.run_sync(cull)
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "cull_idle_servers.py", line 55, in cull_idle
    resp = yield client.fetch(req)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/stack_context.py", line 316, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tornado/simple_httpclient.py", line 307, in _on_timeout
    raise HTTPError(599, error_message)
tornado.httpclient.HTTPError: HTTP 599: Timeout while connecting
```

**Share what version of JupyterHub you are using**
Jupyterhub 0.8.0rc2

Running `jupyter troubleshoot` from the command line, if possible, and posting
its output would also be helpful.

```
$PATH:
	/usr/local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin

sys.path:
	/usr/local/bin
	/srv/jupyterhub
	/usr/lib/python35.zip
	/usr/lib/python3.5
	/usr/lib/python3.5/plat-x86_64-linux-gnu
	/usr/lib/python3.5/lib-dynload
	/usr/local/lib/python3.5/dist-packages
	/usr/lib/python3/dist-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.5.3 (default, Jan 19 2017, 14:11:04)
	[GCC 6.3.0 20170118]

platform.platform():
	Linux-4.4.52+-x86_64-with-Ubuntu-17.04-zesty

which -a jupyter:
	/usr/local/bin/jupyter
	/usr/local/bin/jupyter
```

**Comment by yuvipanda** [comment] 2017-09-27 19:35
I've run into this issue too in https://phabricator.wikimedia.org/T175202

**Comment by ktong** [comment] 2017-09-27 20:09
Got another exception:
```
[I 2017-09-27 20:05:23.184 JupyterHub app:1584] JupyterHub is now running at http://:8000/
Traceback (most recent call last):
  File "cull_idle_servers.py", line 116, in <module>
    loop.run_sync(cull)
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "cull_idle_servers.py", line 58, in cull_idle
    resp = yield client.fetch(req)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python3.5/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
tornado.httpclient.HTTPError: HTTP 403: Forbidden
```
Environment
```
environ({'JPY_API_TOKEN': 'XXXX', 'JUPYTERHUB_API_TOKEN': 'XXXX', 'JUPYTERHUB_USER': '', 'PYTHONPATH': '/srv/jupyterhub', 'JUPYTERHUB_API_URL': 'http://XXXX-jupyterhub:8081/hub/api', 'JUPYTERHUB_CLIENT_ID': 'service-cull-idle', 'JUPYTERHUB_SERVICE_NAME': 'cull-idle', 'JUPYTERHUB_HOST': '', 'JUPYTERHUB_BASE_URL': '/', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'JUPYTERHUB_OAUTH_CALLBACK_URL': 'oauth_callback'})
```

**Comment by ktong** [comment] 2017-09-27 21:11
It looks race condition between jupyterhub and cull_idle_servers. Change loop.run_sync(cull) to loop.call_later(30, cull) solves it.

**Comment by minrk** [comment] 2017-09-28 09:19
For the failure to connect, I found that this was caused by a [bug in minikube](https://github.com/kubernetes/minikube/issues/1568) where pods cannot connect to their own service IP.

For the 403, we can delay startup. In the case of cull-idle-servers, while there may be an error on the first request, it will resolve itself once everything is running, so it isn't a problem.

**Comment by ktong** [comment] 2017-09-28 13:35
Thanks @minrk. 

My cluster is running on GKE, does it impact by the bug in mini kub?

**Comment by minrk** [comment] 2017-09-28 14:25
I'll check. I didn't think GKE exhibited the timeout bug. It could be caused by slow startup of the Hub.

**Comment by willingc** [comment] 2017-11-06 17:42
@minrk Do you think we should label this as a bug or document as a configuration limitation?

**Comment by minrk** [comment] 2017-11-08 12:16
I think we can delay the start of services until the Hub socket is bound, which ought to resolve this.

**Comment by manics** [comment] 2020-04-18 19:02
Closing, it's been a while and work has been done on the culling script.

**Closed by manics** 2020-04-18 19:02 UTC
Labels: bug
