### ISSUE TITLE
Address family not supported by protocol

### ISSUE THREAD

**Issue by kotfic** [jupyterhub/jupyterhub#76] opened 2014-10-24 07:25 UTC
Hi,  I am having trouble connecting after installing jupyterhub with my current config.  This may just be a bad interaction with pyenv, or i have a misconfigured 'localhost' definition in my hosts file,  however a plan run gives me the following error:

```
(jupyter)kotfic@carasgaladon:~/jupyter$ jupyterhub --log=DEBUG
[D 03:16:07.605 JupyterHubApp] Connecting to db: sqlite:///jupyterhub.sqlite
[I 03:16:07.659 JupyterHubApp] Not using whitelist. Any authenticated user will be allowed.
[D 03:16:07.661 JupyterHubApp] Loaded users: 
      kotfic admin
[C 03:16:07.674 JupyterHubApp] Failed to start proxy
    Traceback (most recent call last):
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/jupyterhub/app.py", line 727, in start
        IOLoop().run_sync(self.start_proxy)
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/ioloop.py", line 418, in run_sync
        return future_cell[0].result()
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/gen.py", line 175, in wrapper
        yielded = next(result)
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/jupyterhub/app.py", line 522, in start_proxy
        if self.proxy.public_server.is_up() and \
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/jupyterhub/orm.py", line 109, in is_up
        socket.create_connection((self.ip or 'localhost', self.port))
      File "/home/kotfic/.pyenv/versions/2.7.8/lib/python2.7/socket.py", line 571, in create_connection
        raise err
    error: [Errno 97] Address family not supported by protocol
```

If i specify the IP on the command line the server appears to start, but I get some of these address family not supported errors when launching the actual notebook.  The weird thing is the notebook appears to work fine despite these errors. 

```
(jupyter)kotfic@carasgaladon:~/jupyter$ jupyterhub --ip=127.0.0.1 --log=DEBUG
[D 03:17:13.776 JupyterHubApp] Connecting to db: sqlite:///jupyterhub.sqlite
[I 03:17:13.844 JupyterHubApp] Not using whitelist. Any authenticated user will be allowed.
[D 03:17:13.846 JupyterHubApp] Loaded users: 
      kotfic admin
[I 03:17:13.856 JupyterHubApp] Starting proxy: [u'configurable-http-proxy', '--ip', u'127.0.0.1', '--port', '8000', '--api-ip', u'localhost', '--api-port', '8001', '--default-target', 'http://localhost:8081']
03:17:13.941 - info: [ConfigProxy] Proxying http://127.0.0.1:8000 to http://localhost:8081
03:17:13.944 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
[D 03:17:13.963 JupyterHubApp] Proxy started and appears to be up
[I 03:17:35.062 JupyterHubApp] 302 GET / (127.0.0.1) 0.67ms
[E 03:17:35.091 JupyterHubApp] Could not open static file u'/home/kotfic/.pyenv/versions/jupyter/share/jupyter/static/images/favicon.ico'
[I 03:17:35.092 JupyterHubApp] 200 GET /hub/ (127.0.0.1) 19.04ms
[I 03:17:35.206 JupyterHubApp] 200 GET /hub/static/images/jupyterlogo.png?v=68cb965d07a1e888b7b0bfc4914f2ec7 (127.0.0.1) 9.41ms
[I 03:17:35.210 JupyterHubApp] 200 GET /hub/static/css/style.min.css?v=0557022b5c4d60842f9b5d3fab57cff2 (127.0.0.1) 3.07ms
[I 03:17:35.213 JupyterHubApp] 200 GET /hub/static/components/requirejs/require.js?v=640929dac3c23a448d2eebc37bc32062 (127.0.0.1) 1.82ms
[W 03:17:35.261 JupyterHubApp] 404 GET /hub/static/images/favicon.ico (127.0.0.1) 0.81ms
[I 03:17:37.703 JupyterHubApp] 200 GET /hub/login (127.0.0.1) 17.53ms
[I 03:17:45.759 JupyterHubApp] Spawning [u'jupyterhub-singleuser', u'--user=kotfic', '--port=39866', u'--cookie-name=jupyter-hub-token-kotfic', u'--base-url=/user/kotfic', u'--hub-prefix=/hub/', '--hub-api-url=http://localhost:8081/hub/api']
[D 03:17:45.763 JupyterHubApp] Polling subprocess every 30s
[E 03:17:45.783 JupyterHubApp] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/iostream.py", line 461, in _handle_events
        self._handle_connect()
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/iostream.py", line 1095, in _handle_connect
        self.close()
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/iostream.py", line 388, in close
        self._maybe_run_close_callback()
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/iostream.py", line 412, in _maybe_run_close_callback
        future.set_exception(self.error or StreamClosedError())
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/concurrent.py", line 150, in set_exception
        self._set_done()
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/concurrent.py", line 177, in _set_done
        cb(self)
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/tcpclient.py", line 114, in on_connect_done
        self.on_timeout()
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/tcpclient.py", line 129, in on_timeout
        self.try_connect(iter(self.secondary_addrs))
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/tcpclient.py", line 96, in try_connect
        future = self.connect(af, addr)
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/tcpclient.py", line 176, in _create_stream
        stream = IOStream(socket.socket(af),
      File "/home/kotfic/.pyenv/versions/2.7.8/lib/python2.7/socket.py", line 187, in __init__
        _sock = _realsocket(family, type, proto)
    error: [Errno 97] Address family not supported by protocol
[E 03:17:45.784 JupyterHubApp] Exception in callback None
    Traceback (most recent call last):
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/ioloop.py", line 837, in start
        handler_func(fd_obj, events)
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/iostream.py", line 461, in _handle_events
        self._handle_connect()
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/iostream.py", line 1095, in _handle_connect
        self.close()
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/iostream.py", line 388, in close
        self._maybe_run_close_callback()
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/iostream.py", line 412, in _maybe_run_close_callback
        future.set_exception(self.error or StreamClosedError())
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/concurrent.py", line 150, in set_exception
        self._set_done()
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/concurrent.py", line 177, in _set_done
        cb(self)
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/tcpclient.py", line 114, in on_connect_done
        self.on_timeout()
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/tcpclient.py", line 129, in on_timeout
        self.try_connect(iter(self.secondary_addrs))
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/tcpclient.py", line 96, in try_connect
        future = self.connect(af, addr)
      File "/home/kotfic/.pyenv/versions/jupyter/lib/python2.7/site-packages/tornado/tcpclient.py", line 176, in _create_stream
        stream = IOStream(socket.socket(af),
      File "/home/kotfic/.pyenv/versions/2.7.8/lib/python2.7/socket.py", line 187, in __init__
        _sock = _realsocket(family, type, proto)
    error: [Errno 97] Address family not supported by protocol
2014-10-24 03:17:46.048 [SingleUserNotebookApp] Using existing profile dir: u'/home/kotfic/.ipython/profile_default'
2014-10-24 03:17:46.057 [SingleUserNotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
2014-10-24 03:17:46.070 [SingleUserNotebookApp] Serving notebooks from local directory: /home/kotfic
2014-10-24 03:17:46.071 [SingleUserNotebookApp] 0 active kernels 
2014-10-24 03:17:46.071 [SingleUserNotebookApp] The IPython Notebook is running at: http://localhost:39866/user/kotfic/
2014-10-24 03:17:46.071 [SingleUserNotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 03:17:46.083 JupyterHubApp] Failed to connect to http://localhost:39866/user/kotfic ([Errno 97] Address family not supported by protocol)
INFO:tornado.access:302 GET /user/kotfic (127.0.0.1) 1.63ms
[D 03:17:46.343 JupyterHubApp] Server at http://localhost:39866/user/kotfic responded with 302
[I 03:17:46.344 JupyterHubApp] Adding user kotfic to proxy /user/kotfic => http://localhost:39866
[D 03:17:46.349 JupyterHubApp] Fetching POST http://localhost:8001/api/routes/user/kotfic
[I 03:17:46.399 JupyterHubApp] 302 POST /hub/login?next= (127.0.0.1) 708.86ms
[I 03:17:46.416 JupyterHubApp] 302 GET /hub/ (127.0.0.1) 5.43ms
[I 03:17:46.438 JupyterHubApp] 200 GET /hub/home (127.0.0.1) 14.02ms
[I 03:17:46.529 JupyterHubApp] 200 GET /hub/static/js/home.js (127.0.0.1) 1.37ms
[I 03:17:46.548 JupyterHubApp] 200 GET /hub/static/components/jquery/jquery.min.js (127.0.0.1) 0.95ms
[I 03:17:46.550 JupyterHubApp] 200 GET /hub/static/js/jhapi.js (127.0.0.1) 0.93ms
[I 03:17:46.590 JupyterHubApp] 200 GET /hub/static/js/utils.js (127.0.0.1) 0.65ms
[I 03:17:55.429 JupyterHubApp] 200 GET /hub/admin (127.0.0.1) 39.32ms
[I 03:17:55.561 JupyterHubApp] 200 GET /hub/static/js/admin.js (127.0.0.1) 1.09ms
[I 03:17:55.582 JupyterHubApp] 200 GET /hub/static/components/moment/moment.js (127.0.0.1) 1.09ms
[I 03:17:55.594 JupyterHubApp] 200 GET /hub/static/components/bootstrap/js/bootstrap.min.js (127.0.0.1) 0.85ms
[I 03:18:18.882 JupyterHubApp] 302 GET /hub/user/kotfic/ (127.0.0.1) 38.77ms
[I 03:18:18.901 JupyterHubApp] 200 GET /hub/api/authorizations/3990f48cd635485aa884100a867deb7f (127.0.0.1) 5.14ms
INFO:tornado.access:302 GET /user/kotfic/ (127.0.0.1) 10.09ms
2014-10-24 03:18:39.377 [SingleUserNotebookApp] Kernel started: 6b7f1e6f-9eba-453f-8076-63d7552041ca
```

Please let me know if you need additional information!
Thanks!
/kotfic

**Comment by willingc** [comment] 2016-06-07 04:15
Closing this issue since it appears to be resolved. I'm marking this as "reference" since others may benefit from @kotfic's comments. Thanks to all!

**Closed by willingc** 2016-06-07 04:15 UTC

**Comment by AlbanWende** [comment] 2018-12-12 20:22
I was saved by a solution: kill a spy software "RelevantKnowledge". It would work. https://stackoverflow.com/questions/16373906/address-family-not-supported-by-protocol-family-socketexception-on-a-specific

**Comment by nic-hartley** [comment] 2019-04-04 19:46
I ran into this issue trying to run `scapy` from WSL -- it worked fine when run from CMD. I'm not sure what the issue is, to be honest, but WSL has so many unimplemented edges that it's probably going to be fixed as more work is completed on it.

(I'm not trying to reopen this issue, just provide a possible workaround if it's not working)
